### ISSUE TITLE
获取微博的问题

### ISSUE THREAD

**Issue by zkx34** [sinaweibosdk/weibo_android_sdk#102]
我通过这个API:
  mStatusesAPI.friendsTimeline(0L, maxId, 20, 1, false, 0, false, mListener);
获取更多微博，就是获取发布时间更早的微博。
但是获取到一定的数量之后，就会报NullPointerException,
我断点测试了一下发现，获取到150条微博后，这之后就没有数据了，是不是最多只能获取150条？

**Comment by unvchan** [comment]
我也发现是这样的。获取150条之后获取内容返回的结果没数据
