### ISSUE TITLE
微博分享报错

### ISSUE THREAD

**Issue by yaodatou** [sinaweibosdk/weibo_android_sdk#105]
11-09 11:58:10.031: E/Parcel(3529): Class not found when unmarshalling: com.sina.weibo.sdk.api.TextObject
11-09 11:58:10.031: E/Parcel(3529): java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
11-09 11:58:10.031: E/Parcel(3529):     at java.lang.Class.classForName(Native Method)
11-09 11:58:10.031: E/Parcel(3529):     at java.lang.Class.forName(Class.java:309)
11-09 11:58:10.031: E/Parcel(3529):     at java.lang.Class.forName(Class.java:273)
11-09 11:58:10.031: E/Parcel(3529):     at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
11-09 11:58:10.031: E/Parcel(3529):     at android.os.Parcel.readParcelable(Parcel.java:2245)
11-09 11:58:10.031: E/Parcel(3529):     at android.os.Parcel.readValue(Parcel.java:2152)
11-09 11:58:10.031: E/Parcel(3529):     at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
11-09 11:58:10.031: E/Parcel(3529):     at android.os.BaseBundle.unparcel(BaseBundle.java:221)
11-09 11:58:10.031: E/Parcel(3529):     at android.os.BaseBundle.getString(BaseBundle.java:918)
11-09 11:58:10.031: E/Parcel(3529):     at android.content.Intent.getStringExtra(Intent.java:5767)
11-09 11:58:10.031: E/Parcel(3529):     at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2365)
11-09 11:58:10.031: E/Parcel(3529):     at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1848)
11-09 11:58:10.031: E/Parcel(3529):     at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6000)
11-09 11:58:10.031: E/Parcel(3529):     at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5784)
11-09 11:58:10.031: E/Parcel(3529):     at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:143)
11-09 11:58:10.031: E/Parcel(3529):     at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3977)
11-09 11:58:10.031: E/Parcel(3529):     at android.os.Binder.execTransact(Binder.java:461)
11-09 11:58:10.031: E/Parcel(3529): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.sdk.api.TextObject" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
11-09 11:58:10.031: E/Parcel(3529):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-09 11:58:10.031: E/Parcel(3529):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-09 11:58:10.031: E/Parcel(3529):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-09 11:58:10.031: E/Parcel(3529):     ... 17 more
11-09 11:58:10.031: E/Parcel(3529):     Suppressed: java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
11-09 11:58:10.031: E/Parcel(3529):         at java.lang.Class.classForName(Native Method)
11-09 11:58:10.031: E/Parcel(3529):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-09 11:58:10.031: E/Parcel(3529):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-09 11:58:10.031: E/Parcel(3529):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-09 11:58:10.031: E/Parcel(3529):         ... 18 more
11-09 11:58:10.031: E/Parcel(3529):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
11-09 11:58:10.041: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:10.041: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:10.041: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:10.041: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:10.051: E/Zygote(20690): MountEmulatedStorage()
11-09 11:58:10.051: E/Zygote(20690): v2
11-09 11:58:10.051: E/Zygote(20690): accessInfo : 0
11-09 11:58:10.051: E/SELinux(20690): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
11-09 11:58:10.611: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:10.611: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:10.611: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:10.611: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:10.621: E/Zygote(20729): MountEmulatedStorage()
11-09 11:58:10.621: E/Zygote(20729): v2
11-09 11:58:10.621: E/Zygote(20729): accessInfo : 0
11-09 11:58:10.621: E/SELinux(20729): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
11-09 11:58:10.681: E/Parcel(3529): Class not found when unmarshalling: com.sina.weibo.sdk.api.TextObject
11-09 11:58:10.681: E/Parcel(3529): java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
11-09 11:58:10.681: E/Parcel(3529):     at java.lang.Class.classForName(Native Method)
11-09 11:58:10.681: E/Parcel(3529):     at java.lang.Class.forName(Class.java:309)
11-09 11:58:10.681: E/Parcel(3529):     at java.lang.Class.forName(Class.java:273)
11-09 11:58:10.681: E/Parcel(3529):     at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
11-09 11:58:10.681: E/Parcel(3529):     at android.os.Parcel.readParcelable(Parcel.java:2245)
11-09 11:58:10.681: E/Parcel(3529):     at android.os.Parcel.readValue(Parcel.java:2152)
11-09 11:58:10.681: E/Parcel(3529):     at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
11-09 11:58:10.681: E/Parcel(3529):     at android.os.BaseBundle.unparcel(BaseBundle.java:221)
11-09 11:58:10.681: E/Parcel(3529):     at android.os.BaseBundle.getString(BaseBundle.java:918)
11-09 11:58:10.681: E/Parcel(3529):     at android.content.Intent.getStringExtra(Intent.java:5767)
11-09 11:58:10.681: E/Parcel(3529):     at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2365)
11-09 11:58:10.681: E/Parcel(3529):     at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1848)
11-09 11:58:10.681: E/Parcel(3529):     at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6000)
11-09 11:58:10.681: E/Parcel(3529):     at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5784)
11-09 11:58:10.681: E/Parcel(3529):     at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:143)
11-09 11:58:10.681: E/Parcel(3529):     at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3977)
11-09 11:58:10.681: E/Parcel(3529):     at android.os.Binder.execTransact(Binder.java:461)
11-09 11:58:10.681: E/Parcel(3529): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.sdk.api.TextObject" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
11-09 11:58:10.681: E/Parcel(3529):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-09 11:58:10.681: E/Parcel(3529):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-09 11:58:10.681: E/Parcel(3529):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-09 11:58:10.681: E/Parcel(3529):     ... 17 more
11-09 11:58:10.681: E/Parcel(3529):     Suppressed: java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
11-09 11:58:10.681: E/Parcel(3529):         at java.lang.Class.classForName(Native Method)
11-09 11:58:10.681: E/Parcel(3529):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-09 11:58:10.681: E/Parcel(3529):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-09 11:58:10.681: E/Parcel(3529):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-09 11:58:10.681: E/Parcel(3529):         ... 18 more
11-09 11:58:10.681: E/Parcel(3529):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
11-09 11:58:10.711: E/ActivityManager(3529): isAutoRunBlockedApp:: com.sina.weibo, Auto Run OFF
11-09 11:58:10.851: E/NFC(20690): isAndroidBeamAllowed - Begin
11-09 11:58:10.981: E/SysUtils(20690): ApplicationContext is null in ApplicationStatus
11-09 11:58:11.061: E/ActivityThread(20690): Failed to find provider info for com.google.settings
11-09 11:58:11.141: E/Parcel(3529): Class not found when unmarshalling: com.sina.weibo.sdk.api.TextObject
11-09 11:58:11.141: E/Parcel(3529): java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
11-09 11:58:11.141: E/Parcel(3529):     at java.lang.Class.classForName(Native Method)
11-09 11:58:11.141: E/Parcel(3529):     at java.lang.Class.forName(Class.java:309)
11-09 11:58:11.141: E/Parcel(3529):     at java.lang.Class.forName(Class.java:273)
11-09 11:58:11.141: E/Parcel(3529):     at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
11-09 11:58:11.141: E/Parcel(3529):     at android.os.Parcel.readParcelable(Parcel.java:2245)
11-09 11:58:11.141: E/Parcel(3529):     at android.os.Parcel.readValue(Parcel.java:2152)
11-09 11:58:11.141: E/Parcel(3529):     at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
11-09 11:58:11.141: E/Parcel(3529):     at android.os.BaseBundle.unparcel(BaseBundle.java:221)
11-09 11:58:11.141: E/Parcel(3529):     at android.os.BaseBundle.getString(BaseBundle.java:918)
11-09 11:58:11.141: E/Parcel(3529):     at android.content.Intent.getStringExtra(Intent.java:5767)
11-09 11:58:11.141: E/Parcel(3529):     at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2365)
11-09 11:58:11.141: E/Parcel(3529):     at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1848)
11-09 11:58:11.141: E/Parcel(3529):     at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6000)
11-09 11:58:11.141: E/Parcel(3529):     at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5784)
11-09 11:58:11.141: E/Parcel(3529):     at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:143)
11-09 11:58:11.141: E/Parcel(3529):     at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3977)
11-09 11:58:11.141: E/Parcel(3529):     at android.os.Binder.execTransact(Binder.java:461)
11-09 11:58:11.141: E/Parcel(3529): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.sdk.api.TextObject" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
11-09 11:58:11.141: E/Parcel(3529):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-09 11:58:11.141: E/Parcel(3529):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-09 11:58:11.141: E/Parcel(3529):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-09 11:58:11.141: E/Parcel(3529):     ... 17 more
11-09 11:58:11.141: E/Parcel(3529):     Suppressed: java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
11-09 11:58:11.141: E/Parcel(3529):         at java.lang.Class.classForName(Native Method)
11-09 11:58:11.141: E/Parcel(3529):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-09 11:58:11.141: E/Parcel(3529):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-09 11:58:11.141: E/Parcel(3529):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-09 11:58:11.141: E/Parcel(3529):         ... 18 more
11-09 11:58:11.141: E/Parcel(3529):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
11-09 11:58:11.161: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:11.161: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:11.161: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:11.161: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:11.171: E/Zygote(20828): MountEmulatedStorage()
11-09 11:58:11.171: E/Zygote(20828): v2
11-09 11:58:11.171: E/Zygote(20828): accessInfo : 0
11-09 11:58:11.171: E/SELinux(20828): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
11-09 11:58:11.251: E/ActivityManager(3529): isAutoRunBlockedApp:: com.sina.weibo, Auto Run OFF
11-09 11:58:11.251: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:11.251: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:11.251: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:11.251: E/ActivityManager(3529): checkUser: useridlist=null, currentuser=0
11-09 11:58:11.261: E/Zygote(20858): MountEmulatedStorage()
11-09 11:58:11.261: E/Zygote(20858): v2
11-09 11:58:11.261: E/Zygote(20858): accessInfo : 0
11-09 11:58:11.261: E/SELinux(20858): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
11-09 11:58:11.801: E/ActivityManager(3529): isAutoRunBlockedApp:: com.sina.weibo, Auto Run OFF
11-09 11:58:11.811: E/ActivityManager(3529): isAutoRunBlockedApp:: com.sina.weibo, Auto Run OFF

新浪的大爷，请帮忙解决一下啦

**Comment by ikan56** [comment]
微博更新到5.6.0后出现这个问题，sdk demo也有这个问题。

**Comment by kaiqiangzhang** [comment]
isAutoRunBlockedApp:: 我也遇到了同样的问题

**Comment by jiaowenzheng** [comment]
同上啊！

**Comment by jiaowenzheng** [comment]
跳转到了发布页面，点击发布，就挂了，

**Comment by BriceChou** [comment]
same as #162 issue.

**Comment by kevin-nazgul** [comment]
昨天解决过一个一样的问题，我这边出现的原因是因为在AndroidManifest.xml里面有两个activity写了下面的Filter
```java
<intent-filter>
    <action android:name="com.sina.weibo.sdk.action.ACTION_SDK_REQ_ACTIVITY" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```
这样子分享触发后，由于有两个activity都满足，因此会在系统UI显示一个选择菜单，所以这个Intent会发往system:ui，造成这种堆栈。

解决办法：
保证只有一个activity有这种filter。

**Comment by ikkyu0319** [comment]
@kevin-nazgul 我这没有两个activity写 Filter

也报了 Class not found when unmarshalling: com.sina.weibo.sdk.api.TextObject ，求助~
