### ISSUE TITLE
用Android Studio写新的项目时候,如何导入.so库

### ISSUE THREAD

**Issue by AllenVork** [sinaweibosdk/weibo_android_sdk#107]
我直接将它的so库的jniLibs复制到我项目里面去后,如何去写gradle脚本来include进去?

**Comment by zkx34** [comment]
sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

**Comment by jorry** [comment]
在  build.gradle 中添加


   //noinspection all
    task copyNativeLibs(type: Copy) {
        // third party lib so
        from(new File(projectDir, 'libs')) { include '**/*.so' }
        into new File(buildDir, 'native-libs')
    }
    tasks.withType(JavaCompile) {
        compileTask ->
            //noinspection all
            compileTask.dependsOn copyNativeLibs
    }
    //noinspection all
    tasks.withType(com.android.build.gradle.tasks.PackageApplication) {
        pkgTask ->
            pkgTask.jniFolders = new HashSet<File>()
            pkgTask.jniFolders.add(new File(buildDir, 'native-libs'))
    }

**Comment by yongjhih** [comment]
See also: https://github.com/8tory/weibo-android-sdk , See also: https://github.com/8tory/weibo-android-sdk-core
