### ISSUE TITLE
分享网页时缩略图无法显示（android sdk 3.1.2）

### ISSUE THREAD

**Issue by su1216** [sinaweibosdk/weibo_android_sdk#113]
当我尝试使用微博android sdk分享网页时，缩略图无法显示。文字和链接都正 常，app已经通过审核。
下面是具体log。
注： 在/storage/sdcard1/sina/weibo/thirdapp_pic/文件夹下有一些pic_开头的 文件，发现是我分享时传给sdk的 缩略图。
请问如何解决此问题？多谢
12-07 12:25:54.490  5406 11363 E ImageLoader: UIL doesn't support scheme(protocol) by default [/storage/sdcard1/sina/weibo/thirdapp_pic/pic_1449462354216]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
12-07 12:25:54.490  5406 11363 E ImageLoader: java.lang.UnsupportedOperationException: UIL doesn't support scheme(protocol) by default [/storage/sdcard1/sina/weibo/thirdapp_pic/pic_1449462354216]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
12-07 12:25:54.490  5406 11363 E ImageLoader:     at com.sina.weibo.universalimageloader.core.download.BaseImageDownloader.getStreamFromOtherSource(BaseImageDownloader.java:233)
12-07 12:25:54.490  5406 11363 E ImageLoader:     at com.sina.weibo.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:97)
12-07 12:25:54.490  5406 11363 E ImageLoader:     at com.sina.weibo.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:292)
12-07 12:25:54.490  5406 11363 E ImageLoader:     at com.sina.weibo.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:275)
12-07 12:25:54.490  5406 11363 E ImageLoader:     at com.sina.weibo.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:231)
12-07 12:25:54.490  5406 11363 E ImageLoader:     at com.sina.weibo.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:137)
12-07 12:25:54.490  5406 11363 E ImageLoader:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-07 12:25:54.490  5406 11363 E ImageLoader:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-07 12:25:54.490  5406 11363 E ImageLoader:     at java.lang.Thread.run(Thread.java:841)

**Comment by vforandroid** [comment]
同样是，并且发现是新版新浪微博的问题，老版是ok的。

**Comment by vforandroid** [comment]
看了log，因为是微博使用ImageLoader时候姿势不对。。。
猜测是所有图片都用了ImageLoader，但是对于路径类型的URI没有处理。。。

E/ImageLoader(25497): UIL doesn't support scheme(protocol) by default [/storage/emulated/0/sina/weibo/thirdapp_pic/pic_1449819797233]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
E/ImageLoader(25497): java.lang.UnsupportedOperationException: UIL doesn't support scheme(protocol) by default [/storage/emulated/0/sina/weibo/thirdapp_pic/pic_1449819797233]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
E/ImageLoader(25497):   at com.sina.weibo.universalimageloader.core.download.BaseImageDownloader.getStreamFromOtherSource(BaseImageDownloader.java:233)
E/ImageLoader(25497):   at com.sina.weibo.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:97)
E/ImageLoader(25497):   at com.sina.weibo.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:292)
E/ImageLoader(25497):   at com.sina.weibo.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:275)
E/ImageLoader(25497):   at com.sina.weibo.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:231)
E/ImageLoader(25497):   at com.sina.weibo.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:137)
E/ImageLoader(25497):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/ImageLoader(25497):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/ImageLoader(25497):   at java.lang.Thread.run(Thread.java:818)

**Comment by snzang** [comment]
遇到同样的问题，提示UIL doesn't support scheme(protocol) by default [/storage/emulated/0/sina/weibo/thirdapp_pic/pic_1451980708192]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
希望新浪官方尽快解决
