### ISSUE TITLE
分享时微博崩溃，复现率100%

### ISSUE THREAD

**Issue by su1216** [sinaweibosdk/weibo_android_sdk#114]
step-by-step
1.安装微博app（安装完成后不要打开）
2.通过android 3.1.2 sdk进行微博分享，微博崩溃。

log：

12-08 09:21:49.844 E/AndroidRuntime( 2644): FATAL EXCEPTION: main
12-08 09:21:49.844 E/AndroidRuntime( 2644): Process: com.sina.weibo, PID: 2644
12-08 09:21:49.844 E/AndroidRuntime( 2644): java.lang.RuntimeException: Unable to start receiver com.sina.weibo.sdk.internal.SdkRegisterReceiver: java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.datasource.db.SinaWeiboDBImpl" on path: DexPathList[[zip file "/data/app/com.sina.weibo-1.apk", zip file "/data/data/com.sina.weibo/code_cache/secondary-dexes/com.sina.weibo-1.apk.classes2.zip", zip file "/data/user/0/com.sina.weibo/app_dex/sync395c870b5443a2489f97488379c38542.jar", zip file "/data/user/0/com.sina.weibo/app_dex/weiboad16.jar"],nativeLibraryDirectories=[/data/app-lib/com.sina.weibo-1, /vendor/lib, /system/lib]]
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2431)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at android.app.ActivityThread.access$1800(ActivityThread.java:141)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at android.os.Handler.dispatchMessage(Handler.java:102)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at android.os.Looper.loop(Looper.java:136)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at android.app.ActivityThread.main(ActivityThread.java:5072)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at java.lang.reflect.Method.invokeNative(Native Method)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at java.lang.reflect.Method.invoke(Method.java:515)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at dalvik.system.NativeStart.main(Native Method)
12-08 09:21:49.844 E/AndroidRuntime( 2644): Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.datasource.db.SinaWeiboDBImpl" on path: DexPathList[[zip file "/data/app/com.sina.weibo-1.apk", zip file "/data/data/com.sina.weibo/code_cache/secondary-dexes/com.sina.weibo-1.apk.classes2.zip", zip file "/data/user/0/com.sina.weibo/app_dex/sync395c870b5443a2489f97488379c38542.jar", zip file "/data/user/0/com.sina.weibo/app_dex/weiboad16.jar"],nativeLibraryDirectories=[/data/app-lib/com.sina.weibo-1, /vendor/lib, /system/lib]]
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.sina.weibo.datasource.p.<init>(SinaWeiboDB.java:150)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.sina.weibo.datasource.p.a(SinaWeiboDB.java:198)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.sina.weibo.sdk.internal.d.<init>(SdkDBSource.java:18)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.sina.weibo.sdk.internal.d.a(SdkDBSource.java:24)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.sina.weibo.sdk.internal.b.<init>(SdkController.java:66)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.sina.weibo.sdk.internal.b.a(SdkController.java:561)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.sina.weibo.sdk.internal.SdkRegisterReceiver.onReceive(SdkRegisterReceiver.java:11)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2424)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     ... 10 more
12-08 09:21:49.844 E/AndroidRuntime( 2644): Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.datasource.db.SinaWeiboDBImpl" on path: DexPathList[[zip file "/data/app/com.sina.weibo-1.apk", zip file "/data/data/com.sina.weibo/code_cache/secondary-dexes/com.sina.weibo-1.apk.classes2.zip", zip file "/data/user/0/com.sina.weibo/app_dex/sync395c870b5443a2489f97488379c38542.jar", zip file "/data/user/0/com.sina.weibo/app_dex/weiboad16.jar"],nativeLibraryDirectories=[/data/app-lib/com.sina.weibo-1, /vendor/lib, /system/lib]]
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.sina.weibo.bundlemanager.i.a(ModuleManager.java:72)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.sina.weibo.datasource.p.<init>(SinaWeiboDB.java:145)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     ... 17 more
12-08 09:21:49.844 E/AndroidRuntime( 2644): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.datasource.db.SinaWeiboDBImpl" on path: DexPathList[[zip file "/data/app/com.sina.weibo-1.apk", zip file "/data/data/com.sina.weibo/code_cache/secondary-dexes/com.sina.weibo-1.apk.classes2.zip", zip file "/data/user/0/com.sina.weibo/app_dex/sync395c870b5443a2489f97488379c38542.jar", zip file "/data/user/0/com.sina.weibo/app_dex/weiboad16.jar"],nativeLibraryDirectories=[/data/app-lib/com.sina.weibo-1, /vendor/lib, /system/lib]]
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     at com.sina.weibo.bundlemanager.i.a(ModuleManager.java:69)
12-08 09:21:49.844 E/AndroidRuntime( 2644):     ... 18 more

**Comment by ironox** [comment]
我也碰到同样的问题了，这个有人解决了吗

**Comment by su1216** [comment]
@ironox 找了weibo的人帮忙问，对方说，下一版似乎能解决。。

**Comment by yipingw** [comment]
安装了微博后不打开然后做分享或单点登录确实有这个问题。

**Comment by kingson09** [comment]
@su1216 请问如何联系微博的人，各种联系不上

**Comment by su1216** [comment]
@kingson09 我认识微博内部的人，如果你也认识的话……

**Comment by jalonray** [comment]
后来呢？现在安装微博app不打开或者不登录，直接分享是auth failed
