### ISSUE TITLE
proguard

### ISSUE THREAD

**Issue by AllenVork** [sinaweibosdk/weibo_android_sdk#117]
请问,微博登陆的混淆规则是什么,我添加以下规则时还是有错误:
-dontwarn com.weibo.sdk.android.WeiboDialog
-dontwarn android.net.http.SslError
-dontwarn android.webkit.WebViewClient
-keep public class android.net.http.SslError{
     *;
}
-keep public class android.webkit.WebViewClient{
    *;
}
-keep public class android.webkit.WebChromeClient{
    *;
}
-keep public interface android.webkit.WebChromeClient$CustomViewCallback {
    *;
}
-keep public interface android.webkit.ValueCallback {
    *;
}
-keep class \* implements android.webkit.WebChromeClient {
    *;
}

**Comment by yongjhih** [comment]
See also: https://github.com/8tory/weibo-android-sdk/pull/8
