### ISSUE TITLE
注册service时DownloadService 未定义

### ISSUE THREAD

**Issue by Froyo91** [sinaweibosdk/weibo_android_sdk#121]
我在进行集成前准备，进行到第五步，也就是“在您的应用中注册 SDK 所需要的Activity,Service”时，发现DownloadService没有找到相应的定义，请问这个该怎么解决呢，谢谢~

**Comment by duansiman** [comment]
我也出现这情况，请问你解决了吗？

**Comment by androidchw** [comment]
我也是在这步出现这个问题了？有大神能够帮助解决一下的吗？

**Comment by liuhong1happy** [comment]
+1
