### ISSUE TITLE
IllegalArgumentException: Service Intent must be explicit

### ISSUE THREAD

**Issue by dev-sleepingcat** [sinaweibosdk/weibo_android_sdk#125]
如题，在5.x以上机器，分享到微博会报此错误，导致app直接crash。

java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.sina.weibo.remotessoservice }

在5.x机器以上，service的intent一定要显性声明，希望微博这边能够看下这个问题。

**Comment by OsBelief** [comment]
我也遇到这问题了，请问怎么解决？
