### ISSUE TITLE
有关新的接口问题

### ISSUE THREAD

**Issue by MichaelJokAr** [sinaweibosdk/weibo_android_sdk#127]
在新的接口里的发生一条微博接口里有微博可见性里有分组一项；但是新的接口里没有接口能让我获取分组，请问我该怎么获取分组？谢谢

**Comment by BriceChou** [comment]
1. 如果没有的话，可以自己通过查看 http://open.weibo.com/wiki/%E9%A6%96%E9%A1%B5 页面具体接口的具体返回数据类型。（可能他的API文档会返回不一样的实际的数据。）
2. 然后模仿他的接口实现方式，自己写接口实现功能！
