### ISSUE TITLE
Android应用打包后授权页面一闪而过的问题_Auth2.0

### ISSUE THREAD

**Issue by LittleProgrammer** [sinaweibosdk/weibo_android_sdk#13]
这里主要做一下分享，因为之前项目中遇到一个简单问题，折磨了好久最近终于解决，如果有朋友遇到跟我一样的问题，希望能帮到你们。

---

**首先说明一下新浪开发平台注册应用填写的应用信息**
Android包名：顾名思义，你的应用包名，AndroidManifest文件中package的值
Android签名：你的应用发布打包用到的.keystore的MD5值
Debug签名：你的应用测试用到的.keystore的MD5值

**下面说下我们遇到的问题，虽然很愚蠢，但是遇到了也很头疼**

**打包之前一切都是正常的，打包后授权页面一闪而过。**

我们在新浪开发平台“Android签名：”这一栏中填写了错误的签名，在这里不得不介绍下新浪提供的签名工具app_signatures.apk的用法。
1. 卸载你们的应用
2. 使用android默认.keystore打包APK，==>安装该APK==>利用SINA提供的工具生成debug签名==>填写到平台的
        “debug 签名”处
3. 卸载应用
4. 使用你们公司的.keystore打包APK，==>安装该APK==>利用SINA提供的工具生成release签名==>填写到平台上
        的“Android签名”处

正确的填写签名后就不会出现授权页一闪而过的问题了。

第一次发博，不喜勿喷，谢谢。。。

**Comment by jksfood** [comment]
楼主，按照你说的签名授权成功了，感谢，但为什么还是会出现授权画面一闪而过的现象？
