### ISSUE TITLE
WeiboParameters中有bug

### ISSUE THREAD

**Issue by liulinjie1990823** [sinaweibosdk/weibo_android_sdk#131]
public void put(String key, Object val) {
        this.mParams.put(key, val.toString());
    }
toString后导致设置的byteArrayOutputStream类型变成string类型，
导致如下代码判断有问题：
public boolean hasBinaryData() {
        Set keys = this.mParams.keySet();
        Iterator var3 = keys.iterator();

```
    Object value;
    do {
        if(!var3.hasNext()) {
            return false;
        }

        String key = (String)var3.next();
        value = this.mParams.get(key);
    } while(!(value instanceof ByteArrayOutputStream) && !(value instanceof Bitmap));

    return true;
}
```

导致gif分享需要使用下面代码实现(辛亏提供了setParams这个方法)：
 WeiboParameters params = new WeiboParameters(mAppKey);
        LinkedHashMap<String, Object> mParams = new LinkedHashMap();
        mParams.put("status", status);
        mParams.put("pic", byteArrayOutputStream);
        params.setParams(mParams);

**Comment by junchenChow** [comment]
`WeiboParameters params = new WeiboParameters(BuildConfig.SINA_APP_KEY);
        LinkedHashMap mParams = new LinkedHashMap();
        mParams.put("access_token", token);
        mParams.put("pic", Util.bmpToByteArray(GlideBitmapFactory.decodeFile(url), true));
        params.setParams(mParams);

        new AsyncWeiboRunner(context)
                .requestAsync(
                        "https://api.weibo.com/2/statuses/upload.json",
                        params,
                        "POST",
                        new RequestListener() {
                            @Override
                            public void onComplete(String s) {
                                Log.e("ShareSina:", "onComplete s :" + s);

                            }

                            @Override
                            public void onWeiboException(WeiboException e) {
                                Log.e("ShareSina:  ", "exception :" + e.getMessage());
                              
                            }
                        });`

`mParams.put("pic", Util.bmpToByteArray(GlideBitmapFactory.decodeFile(url), true));`我这一段是bitmap转byte［］，这个请求发送之后就报 unsupport mediatype (application/x-www-form-urlencoded)错误， 请问 微博分享gif 那个pic字段是要什么类型的东西
