### ISSUE TITLE
安卓版本SDK3.1.4授权页面空白

### ISSUE THREAD

**Issue by scottguosk** [sinaweibosdk/weibo_android_sdk#133]
安卓手机未安装微博客户端，调用sdk使用微博账号登录，弹出“登录-新浪微博”界面无内容。log中如下怀疑信息
“chromium: [INFO:CONSOLE(15)] "Viewport argument key "minimal-ui" not recognized and ignored.", source: https://passport.weibo.cn/signin/login?client_id……”

请问下如何解决？

**Comment by sparkrico** [comment]
遇到同样的问题，不知道有解决办法么
