### ISSUE TITLE
android6.0, couldn't find "libweibosdkcore.so", sdk3.1.4

### ISSUE THREAD

**Issue by AnswerZhao** [sinaweibosdk/weibo_android_sdk#134]
运行报错：
nativeLibraryDirectories=[/data/data/cn.artand.android/lib, /vendor/lib64, /system/lib64]]] couldn't find "libweibosdkcore.so"，急求解决

**Comment by eden57** [comment]
android studio 下用老土办法，src/main下建jniLibs，把.so连带文件夹一起拷贝进去，应该有用。

**Comment by BriceChou** [comment]
楼上+1，除此之外还需要将你测试机上的应用删掉，才能正常运行！
