### ISSUE TITLE
SDK proguard 混淆规则是什么？

### ISSUE THREAD

**Issue by xxvision** [sinaweibosdk/weibo_android_sdk#136]
混淆后就唤不起微博客户端来分享

**Comment by edwardaa** [comment]
不能指望新浪的人来回答问题，还得靠自己。

看bug日志，分析原因，添加规则。

对于分享功能：
```
-keep class com.sina.weibo.sdk.api.* { *; }
```
足够！

**Comment by edwardaa** [comment]
你要是图省事，对所有功能 （不推荐）：

```
-keep class com.sina.** { *; }
-keep interface com.sina.** { *; }
```

这种方式实际上就会忽略整个SDK的混淆。

**Comment by yongjhih** [comment]
See also: https://github.com/8tory/weibo-android-sdk/pull/8

**Comment by AITUncle** [comment]
> 不能指望新浪的人来回答问题，还得靠自己。
> 
> 看bug日志，分析原因，添加规则。
> 
> 对于分享功能：
> 
> ```
> -keep class com.sina.weibo.sdk.api.* { *; }
> ```
> 
> 足够！

readme里面让这么keep，也是醉了了。
这么大一个公司哎~没人管管么。
```
-keep class com.sina.weibo.sdk.** { *; }
```
