### ISSUE TITLE
添加视频后无法唤起微博客户端

### ISSUE THREAD

**Issue by runyan** [sinaweibosdk/weibo_android_sdk#137]
如果只分享文字和图片的时候可以正确唤起微博客户端，而添加视频之后无法唤起客户端iWeiBoShareAPI.sendRequest返回false
创建VideoObject的代码如下：
`private VideoObject getVideoObj() {
        VideoObject videoObject = new VideoObject();
        videoObject.title = "标题";
        videoObject.description = "描述";
        videoObject.actionUrl = "http://us.sinaimg.cn/001dhCNcjx06ZSY8wo2b0104010083Xg0k01.mp4";
        videoObject.dataUrl = "www.weibo.com";
        videoObject.dataHdUrl = "www.weibo.com";
        return videoObject;
    }`
sdk版本3.1.4

**Comment by CharonChui** [comment]
我也遇到同样的问题。兄弟解决了没有？

**Comment by runyan** [comment]
还没有

**Comment by leafseelight** [comment]
加入以下参数可以分享，但是分享出去后却变成网页链接。
`videoObject.identify = Utility.generateGUID();
        videoObject.title = "share title";
        videoObject.description = "share content";
        Bitmap bmp = BitmapFactory.decodeResource(activitySoftReference.get().getResources(),
                                                  R.drawable.ic_loading);
        videoObject.setThumbImage(bmp);`

**Comment by leafseelight** [comment]
> 10.2 如何实现LinkCard效果？
6.2.1（3）中分享视频所示效果是LinkCard效果，如下图左所示。分享普通链接是没有这种效果的。如果你想要你分享出去的内容展示成 LinkCard 的样子，其前提条件是你分享的链接支持 LinkCard。即 LinkCard 的分享开关，是基于分享出来的链接的域名。打个比方，开启 v.youku.com 的 LinkCard 开关，从而发布器中带这个链接的，都能呈现为 LinkCard，该功能并不是针对于某个特定的应用，而是针对于特殊的网内容的。 如果某个网站需要进行 LinkCard 商务合作，请联系 BD。详情请阅读：移动客户端接入（http://t.cn/aex4JF）

10.3 如何实现附件栏集成分享？
关于第三方应用注册到微博客户端效果，如下图右所示：
如果优质的第三方应用也想被显示在此处，也需要进行商务合作，默认情况下是不被显示在此处的。详情请阅读：移动客户端接入（http://t.cn/aex4JF）
注意：如果没有进行过商务合作，是无法进行该分享的。
