### ISSUE TITLE
新浪微博sso授权登录时一直提示网络不给力，稍候再试试吧（C401）

### ISSUE THREAD

**Issue by zhangjinhuang** [sinaweibosdk/weibo_android_sdk#142]
一开始用红米手机没有装新浪客户端时可以成功调起web页登录成功，但是换了另一台没有装新浪客户端的手机却不行了，另外当红米也装有新浪客户端时登录一直提示网络不给力，稍候再试试吧（C401)，其它手机也是这样，包名、授权回调页及签名都没有错了，但是现在就是一直登录不了，求解释，QQ：373899376

**Comment by liericiyan** [comment]
搞定了吗

**Comment by h3clikejava** [comment]
遇到同样的问题，红米2和Note2测试，wifi和4G均出现401，以为是SDK版本问题，从3.1.0升级到3.1.4还是不行！

**Comment by niceheart921** [comment]
我也遇上这个问题，解决了吗？

**Comment by playcode001** [comment]
应该是官方这个版本有问题

**Comment by wildlyz** [comment]
你遇到什么问题了

2016-04-18 

wildlyz 



发件人：playcode001 <notifications@github.com>
发送时间：2016-04-18 19:26
主题：Re: [sinaweibosdk/weibo_android_sdk] 新浪微博sso授权登录时一直提示网络不给力，稍候再试试吧（C401） (#142)
收件人："sinaweibosdk/weibo_android_sdk"<weibo_android_sdk@noreply.github.com>
抄送：

应该是官方这个版本有问题

**Comment by playcode001** [comment]
@wildlyz 
{"error":"unsupport_protocol","error_code":21320,"request":"/oauth2/sso_authorize","error_uri":"/oauth2/sso_authorize","error_description":"oauth2 must use https protocol."}

接口返回数据，是 http 请求，应该次版本 SDK 有问题
