### ISSUE TITLE
安卓SSO登录401到底是什么鬼

### ISSUE THREAD

**Issue by h3clikejava** [sinaweibosdk/weibo_android_sdk#144]
遇到同样的问题，红米2和Note2测试，wifi和4G均出现401，以为是SDK版本问题，从3.1.0升级到3.1.4还是不行！

**Comment by playcode001** [comment]
这个已经不是一个人的问题了

- appkey、签名等检查一百遍，都没有问题
- 通过抓包，定位到发的是http请求。返回数据是：
{"error":"unsupport_protocol","error_code":21320,"request":"/oauth2/sso_authorize","error_uri":"/oauth2/sso_authorize","error_description":"oauth2 must use https protocol."}
- 现在官方 SDK 运营实例，也出现同样问题，如下图所示。

![image](https://cloud.githubusercontent.com/assets/5078044/14602068/6fd2eeda-0598-11e6-82fb-39c9159e4bff.png)

一个对外提供服务的公司，一定要慎重对待外放的每一个版本，把有问题的版本放出来，就是坑爹，望尽快修复。

**Comment by wildlyz** [comment]
你是？
这是什么应用？

2016-04-18 

wildlyz 



发件人：playcode001 <notifications@github.com>
发送时间：2016-04-18 19:15
主题：Re: [sinaweibosdk/weibo_android_sdk] 安卓SSO登录401到底是什么鬼 (#144)
收件人："sinaweibosdk/weibo_android_sdk"<weibo_android_sdk@noreply.github.com>
抄送：

这个已经不是一个人的问题了
appkey、签名等检查一百遍，都没有问题 
通过抓包，定位到发的是http请求。返回数据是： {"error":"unsupport_protocol","error_code":21320,"request":"/oauth2/sso_authorize","error_uri":"/oauth2/sso_authorize","error_description":"oauth2 must use https protocol."} 
现在官方 SDK 运营实例，也出现同样问题，如下图所示。 

一个对外提供服务的公司，一定要慎重对待外放的每一个版本，把有问题的版本放出来，就是坑爹，望尽快修复。

**Comment by playcode001** [comment]
@wildlyz 官方放出来的demo

**Comment by wildlyz** [comment]
跟我有什么关系？我不是官方的

2016-04-18 

wildlyz 



发件人：playcode001 <notifications@github.com>
发送时间：2016-04-18 19:22
主题：Re: [sinaweibosdk/weibo_android_sdk] 安卓SSO登录401到底是什么鬼 (#144)
收件人："sinaweibosdk/weibo_android_sdk"<weibo_android_sdk@noreply.github.com>
抄送："刘永征"<wildlyz@126.com>

@wildlyz 官方放出来的demo

**Comment by bopro** [comment]
3.1.2同样问题，各种坑坑呀
