### ISSUE TITLE
接口文档总是与返回的对不上

### ISSUE THREAD

**Issue by MichaelJokAr** [sinaweibosdk/weibo_android_sdk#145]
看到你们写上了，你们一直在完善文档，但总是令人不满意；我认为最大的原因就是你们的接口文档总是与返回的东西不一样；几乎每个接口都是这样；无法与你们的文档对接上

**Comment by h3clikejava** [comment]
可能都是实习生写的吧

**Comment by a1018875550** [comment]
太不负责了，一点都没有大公司的样子

**Comment by BriceChou** [comment]
1. 是的，最新的返回数据跟文档都是两码事情！
2. 解决方法：通过使用Postman等插件，模拟发送JSON请求，便可以知道最新数据了。
