### ISSUE TITLE
新浪微博是不是已经挂了？Issues根本没人解决，而且还用jar包这么老土的引入方式

### ISSUE THREAD

**Issue by h3clikejava** [sinaweibosdk/weibo_android_sdk#146]
Rt

**Comment by heinika** [comment]
感觉属于没人管的状态。。

**Comment by yongjhih** [comment]
See also: https://github.com/8tory/weibo-android-sdk

**Comment by BriceChou** [comment]
1. 导入的Jar包少了很多功能。
2. 最好使用导入 Module的方式，比较靠谱，而且功能比较全。
3. 现在这个基本没人管，API与实际的返回JSON数据不相同。
