### ISSUE TITLE
无客户端，分享链接中带&符号分享成功，用客户端无法打开此链接。

### ISSUE THREAD

**Issue by kang2nana** [sinaweibosdk/weibo_android_sdk#147]
无微博客户端
分享链接中带& 符号， 分享成功后

用微博客户端无法打开此链接

因为： 链接中的符号&  变成了 &amp;  

请修改。。

**Comment by lindow2009** [comment]
我也遇到了这个问题，不知道怎么处理，请微博的人快点出来看看吧
