### ISSUE TITLE
sdk 分享图片压缩问题

### ISSUE THREAD

**Issue by csdnail** [sinaweibosdk/weibo_android_sdk#15]
现在sdk 用、ImageObject 传递 bitmap，图片总是被压缩，请问怎么可以不压缩的分享图片，比如只传递 uri 这样的？谢谢
ImageObject imageObject = new ImageObject();
imageObject.setImageObject(bitmap);

**Comment by edwardaa** [comment]
可直接设置图片数据：
```java
byte[] data = ...;
imageObject.imageData = data;
```
或则
```java
imageObject.imagePath = <local image path>;
```
