### ISSUE TITLE
使用sdk分享之后，不管是取消分享还是分享成功了，返回之后，app就进入后台

### ISSUE THREAD

**Issue by ghost** [sinaweibosdk/weibo_android_sdk#151]
如题，我使用weibo的Android sdk来做分享到微博功能的时候在Smartisan T1 以及sony z系列出现问题。
点击分享按钮之后，我会跳转到一个新的Activity，里面有各种分享按钮，如微信、qq、微博等。
对于分享到微博，不管是取消分享，还是分享成功，回调onResponse方法的时候，我在里面调用的finish函数来结束当前的Acitivty，在Smartisan T1 以及sony z系列手机出现app进入后天的情况，其它的手机正常。
请问如何处理这个问题

**Comment by naiyu** [comment]
解决了，将activity设置为android:launchMode="singleTask" 就好了

**Comment by zhang-yuehuan** [comment]
给楼主点赞，魅族手机mx4也有这个问题。看了楼主的解决方案给解决了，给楼主无数个赞。
