### ISSUE TITLE
快出个android studio版本的例子吧

### ISSUE THREAD

**Issue by liuju** [sinaweibosdk/weibo_android_sdk#156]
快出个android studio版本的例子吧，各种不方便

**Comment by jalonray** [comment]
一年没人维护了

**Comment by yongjhih** [comment]
See also: https://github.com/8tory/weibo-android-sdk

**Comment by BriceChou** [comment]
1.可以通过Android studio 的方式导入，我就是这么做的。
2. 具体步骤同 issue #171.
3. 希望能帮到你！
