### ISSUE TITLE
请问如何分享 本地或者 网络 gif图片呢 ？ 

### ISSUE THREAD

**Issue by hnyer** [sinaweibosdk/weibo_android_sdk#157]
我按照  

 mStatusesAPI.upload("发送gif带本地图片的微博", bitmap, null, null, mListener);
mStatusesAPI.uploadUrlText("发送gif一条带网络图片的微博"+System.currentTimeMillis(), photoURL

分享出去的gif的变成静态的图片。

**Comment by xiaoxiaocainiao** [comment]
搞定了么?

**Comment by Guoooooo** [comment]
请问分享gif解决了吗？一直没找到api

**Comment by WTree** [comment]
我搞定了，需要自己new一个hashMap ，把gif 转成ByteArrayOutputStream,然后put("pic",**) 再设置setParams，这样就可以传成功了
