### ISSUE TITLE
授权画面一闪而过

### ISSUE THREAD

**Issue by jksfood** [sinaweibosdk/weibo_android_sdk#158]
为什么我的授权界面一闪而过？授权应该是成功了，可是这样不行啊，总得给用户一个按确定的机会啊，在线等，。。。。。

**Comment by jksfood** [comment]
还有个问题，不知道跟这个有没有关系，微博后台录入签名时，怎么只有正式签名的 录入框，没有debug签名的录入框/??????我是用的android studio进行开发的

**Comment by Hard2Get** [comment]
同样出现了这个问题
