### ISSUE TITLE
ActivityThread: Failed to find provider info for com.sina.weibo.sdkProvider

### ISSUE THREAD

**Issue by zhang-yuehuan** [sinaweibosdk/weibo_android_sdk#159]
微博客户端第一次安装，从未点击启动，然后单击我们的app选择微博账号登录，则会报这个错误，并且启动缓慢，有时会导致ANR.(无论我是在UI线程还是新启线程唤起微博登录都会有这个问题)，libs下的so文件也已拷贝到项目中~  请问有人遇到过么？

**Comment by imknown** [comment]
+1
