### ISSUE TITLE
auth fail!!!!

### ISSUE THREAD

**Issue by woniu0936** [sinaweibosdk/weibo_android_sdk#161]
使用魅族魅蓝3(yunOS 3.1.6)，分享没问题，换成坚果手机(android 5.1.1)或者魅族pro5(android 5.1.1)报的是auth faild!!!!

**Comment by Ws5120** [comment]
你与解决吗

**Comment by h3clikejava** [comment]
Are U O Right?

**Comment by SHR-NAME** [comment]
我也出现这种情况
