### ISSUE TITLE
分享成功，回调失败，onNewIntent不被执行

### ISSUE THREAD

**Issue by Lyon1994** [sinaweibosdk/weibo_android_sdk#164]
分享成功，回调失败，onNewIntent不被执行；
分享失败，回调失败，onNewIntent不被执行；
取消分享，回调失败，onNewIntent不被执行； 
@sinaweibosdk

**Comment by wildlyz** [comment]
加上SO文件就可以了‘

2016-05-19 

wildlyz 



发件人：Lyon Yan <notifications@github.com>
发送时间：2016-05-19 17:23
主题：[sinaweibosdk/weibo_android_sdk] 分享成功，回调失败，onNewIntent不被执行 (#164)
收件人："sinaweibosdk/weibo_android_sdk"<weibo_android_sdk@noreply.github.com>
抄送：

分享成功，回调失败，onNewIntent不被执行；
分享失败，回调失败，onNewIntent不被执行；
取消分享，回调失败，onNewIntent不被执行； 
@sinaweibosdk

**Comment by Lyon1994** [comment]
@wildlyz 这个我加过了，但是还是不行

**Comment by Lyon1994** [comment]
@sinaweibosdk

**Comment by Lyon1994** [comment]
![device-2016-05-19-173700](https://cloud.githubusercontent.com/assets/8456652/15389250/87388cde-1de8-11e6-8af1-f0fefdb10dfe.png)
so文件我都加过了，用的是3.1.4的sdk，怎样解决呢？ @wildlyz @sinaweibosdk

**Comment by wildlyz** [comment]
这个你是在哪看到的  把链接
给我下

2016-05-19 

wildlyz 



发件人：Lyon Yan <notifications@github.com>
发送时间：2016-05-19 17:40
主题：Re: [sinaweibosdk/weibo_android_sdk] 分享成功，回调失败，onNewIntent不被执行 (#164)
收件人："sinaweibosdk/weibo_android_sdk"<weibo_android_sdk@noreply.github.com>
抄送："刘永征"<wildlyz@126.com>,"Mention"<mention@noreply.github.com>


so文件我都加过了，用的是3.1.4的sdk，怎样解决呢？ @wildlyz @sinaweibosdk

**Comment by Lyon1994** [comment]
@wildlyz 图片是我自己截的，所用的库是当前所在的github库，所有的参考文档都是新浪微博官网给的
