### ISSUE TITLE
文件不存在(C8998)

### ISSUE THREAD

**Issue by tanjinc** [sinaweibosdk/weibo_android_sdk#165]
第三方登陆老是弹出“文件不存在(C8998)”toast。

**Comment by BenZstory** [comment]
同问，卡在这里不能获取授权

**Comment by h3clikejava** [comment]
同问，卡在这里不能获取授权

**Comment by pheynix** [comment]
同问，卡在这里不能获取授权

**Comment by ting0220** [comment]
大家都没解决呢吗？

**Comment by Yufeikang** [comment]
大家有解决这个问题吗

**Comment by Yufeikang** [comment]
已解决 http://bbs.umeng.com/thread-17766-1-1.html

**Comment by shijia109** [comment]
同问

**Comment by shijia109** [comment]
就没有一个官方的解释吗？我用的原生微博，不是友盟集成的

**Comment by ting0220** [comment]
好像是因为没有打签名包，我试了一下，当你打签名包之后貌似就没有问题了

**Comment by gzfgeh** [comment]
1、包名签名一致，其中不包含空格和不一样字符
2、微博平台设置 授权回调地址和xml中配置一致https://api.weibo.com/oauth2/default.html
3、安卓手机上面报文件找不到C8998

**Comment by Demarcia-cn** [comment]
通常debug版会报这个错误，签名即可。

**Comment by imknown** [comment]
@Demarcia-cn 蜜汁挖坟

**Comment by angularzues** [comment]
签名是 release 的，回调地址都一样，还是报了这个错误，求解

**Comment by linbiaojj** [comment]
最近微博分享遇到这个问题，分享之后微博客户端提示发布微博失败存入草稿箱，草稿箱那显示(C8998)文件不存在。然而微博网页分享是正常的。网上搜的都是说签名跟回调地址的，已经确认这两个没问题。
官方的人邮件微博私信都不回复，感觉都*光了。
