### ISSUE TITLE
SSO授权，如果客户端未登录，应用调用后登录，微博崩溃

### ISSUE THREAD

**Issue by wjk2015** [sinaweibosdk/weibo_android_sdk#167]
可用sdk demo重现，微博版本v6.5.0，mi5，华为p6均可重现，其他机型未试。

**Comment by hustwht** [comment]
still have this problem. please fix. Nexus5

**Comment by hustwht** [comment]
still have this problem. please fix. Nexus5

**Comment by shijia109** [comment]
太垃圾了，新浪就爱用不用的态度，连个管事的都没有

**Comment by shanshanpt** [comment]
+1
