### ISSUE TITLE
魅族手机未安装微博客户端时分享崩溃,日志如下

### ISSUE THREAD

**Issue by CharlesZqikai** [sinaweibosdk/weibo_android_sdk#168]
java.lang.NullPointerException

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.kekejl.company/com.sina.weibo.sdk.component.WeiboSdkBrowser}: java.lang.NullPointerException

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)

......

Caused by:

java.lang.NullPointerException:

com.sina.weibo.sdk.component.WeiboSdkBrowser.a(WeiboSdkBrowser.java:513)

com.sina.weibo.sdk.component.WeiboSdkBrowser.a(WeiboSdkBrowser.java:144)

com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(WeiboSdkBrowser.java:126)

android.app.Activity.performCreate(Activity.java:5231)

android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)

android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)

android.app.ActivityThread.access$800(ActivityThread.java:138)

android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)

android.os.Handler.dispatchMessage(Handler.java:102)

android.os.Looper.loop(Looper.java:136)

android.app.ActivityThread.main(ActivityThread.java:5024)

java.lang.reflect.Method.invokeNative(Native Method)

java.lang.reflect.Method.invoke(Method.java:515)

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)

com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)

dalvik.system.NativeStart.main(Native Method)

**Comment by fanweiguo** [comment]
我的也遇到这个情况了 三星I9300

**Comment by CharlesZqikai** [comment]
微博团队,有人给个回复么?

**Comment by BriceChou** [comment]
@CharlesZqikai 
这个我不知道是不是手机的原因导致的，但是可以给你一个思路，你可以按照这个思路检查一下;

1. 我想问问你是只导入了jar包，还是导入了Moudle 进行引用的？是否添加了.so文件？
2. 你在你的Android manifest 文件中是否添加了
 ```xml
<activity android:name="com.sina.weibo.sdk.component.WeiboSdkBrowser"
            android:configChanges="keyboardHidden|orientation"
            android:exported="false"
            android:windowSoftInputMode="adjustResize" />
```
这个是必要的，调用WeiboSdkBrowser的。
3. 如果你添加了，但是还是报错了，很有可能你没有覆写回调接口
```java
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        // Without this callback function,we can't use the SSO handler.
        if (mSsoHandler != null) {
            mSsoHandler.authorizeCallBack(requestCode, resultCode, data);
        }
    }
```
4. 以上希望能够给您一点启示，也希望能够帮助到您！

**Comment by CharlesZqikai** [comment]
hi,
    首先十分感谢您能给予帮助,
     我按照您说的2、3点又检查了下，没有问题！清单文件有配置,回调也添加了!

    至于第一点我导入了Moudle进行引用的，也添加了.so文件!
    目前我所拥有的4部测试机均可以正常分享,只有从bug统计平台上抓出来了上面一条log,且只有一个机型.
    不知是不是没有适配到该机型?

                                                            再次表示感谢!
    
 



charleszhuqikai@foxmail.com
 
发件人： Mingliang ZHOU
发送时间： 2016-07-20 12:35
收件人： sinaweibosdk/weibo_android_sdk
抄送： CharlesZqikai; Mention
主题： Re: [sinaweibosdk/weibo_android_sdk] 魅族手机未安装微博客户端时分享崩溃,日志如下 (#168)
@CharlesZqikai 
这个我不知道是不是手机的原因导致的，但是可以给你一个思路，你可以按照这个思路检查一下;
我想问问你是只导入了jar包，还是导入了Moudle 进行引用的？是否添加了.so文件？
你在你的Android manifest 文件中是否添加了 xml <activity android:name="com.sina.weibo.sdk.component.WeiboSdkBrowser" android:configChanges="keyboardHidden|orientation" android:exported="false" android:windowSoftInputMode="adjustResize" /> 这个是必要的，调用WeiboSdkBrowser的。
如果你添加了，但是还是报错了，很有可能你没有覆写回调接口
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        // Without this callback function,we can't use the SSO handler.
        if (mSsoHandler != null) {
            mSsoHandler.authorizeCallBack(requestCode, resultCode, data);
        }
    }
以上希望能够给您一点启示，也希望能够帮助到您！
