### ISSUE TITLE
现在还不能以dependency的方式集成到android studio中是吗?

### ISSUE THREAD

**Issue by wang850228803** [sinaweibosdk/weibo_android_sdk#171]

**Comment by BriceChou** [comment]
1.可以的，你将WeiboSDK以module的形式添加到Android studio中。
2. 然后，在你的app module中添加 dependency module的形式即可。
3. 备注：导入WeiboSDK的形式以Eclipse adt的方式添加即可。
4. 希望能帮到您！

**Comment by yongjhih** [comment]
See also: https://github.com/8tory/weibo-android-sdk
