### ISSUE TITLE
混淆 proguard.rules

### ISSUE THREAD

**Issue by CSnowStack** [sinaweibosdk/weibo_android_sdk#172]
混淆代码在哪?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by yongjhih** [comment]
See also: https://github.com/8tory/weibo-android-sdk/blob/master/weibo-android-sdk/weibo-android-sdk.pro
