### ISSUE TITLE
分享成功，但不触发回调的建议（以及解决方案）

### ISSUE THREAD

**Issue by Lyon1994** [sinaweibosdk/weibo_android_sdk#173]
![sina_error](https://cloud.githubusercontent.com/assets/8456652/16557434/50b8dc38-4212-11e6-86ca-09a69f43e1fc.png)

如有这样的地方，求在文档中注明，这还是我反编译jar文件才发现的，不是每一个人都喜欢用activity去实现其他的接口的，你们这样操作，还不在文档中说明不是浪费我们时间么？希望诸位作者，以后可以注意些，这个错误浪费了我很多时间

另外由于jar包封装，调试的log并不会被打印，尽管你做了打印操作，但是并不会看到你们的log提示，请换种提示方式

**Comment by Lyon1994** [comment]
另外由于jar包封装，调试的log并不会被打印，所以才不会发现你们的log提示，请换种提示方式

**Comment by BriceChou** [comment]
1. 干嘛还反编译它的jar包，jar包里面的功能好少，最好直接导入Module的形式,添加WeiboSDK.
2. 那里面的API会有详细的说明，也会打印出你需要的log。（ps:我用的是 Android studio）
3. 尽量少用jar包，费时间还费心，关键是返回的数据有的会跟实际解析的不一样，你还得重改它的接口。
4. 希望能帮到你！

**Comment by Lyon1994** [comment]
@BriceChou 
1，我用的是eclipse，公司电脑太卡，用不起as，log日志自然打印不出来
2，不能因为大部分人都用as，新浪sdk就不用把开发文档写详细，很明显的问题
3，开发文档不详细，这个很让人费解，新浪人员就不会在方法前写个注释么？（至少我贴出的那段代码没有）
4，我用eclipse，暂时用不起来as，但是不要忽略用eclipse的用户

**Comment by BriceChou** [comment]
@Lyon1994 
1. WeiboSDK 官方文档里面用的就是 Eclipse adt.
2. 其次，官方文档跟实际的返回的json数据可能会不一样的。
3. 最好使用Postman这类的插件，模拟发送JSON请求。
4. 更多的接口，你可以参考http://open.weibo.com/wiki/%E5%BE%AE%E5%8D%9AAPI
5. 哈哈～～还有我不是官方人员，我是路过的路人甲，只是最近在做Weibo.
    所以，才来路过看看.

**Comment by Lyon1994** [comment]
@BriceChou 好吧，你说的我都知道，所有分享的步骤我都弄好了，只是对新浪微博的文档进行吐槽罢了，一个需要传递context对象的方法，也没说明context对象一定要activity的实例，log日志也不是一定就能打印出来的，做个异常抛出也比这个强啊........................................

**Comment by BriceChou** [comment]
@Lyon1994 同感，哈哈～～感觉这一堆issue都没人管，我们是不是该集体跑去它们的官微吐槽，才能被看见啊！

**Comment by Lyon1994** [comment]
@BriceChou 我把代码贴出来就是为了大家不要犯和我同样的错误....
开源这东西，大家互相帮助吧

**Comment by ExenVitor** [comment]
我刚遇到这个问题，看了下源码非常无语。。。正想上来吐槽一下就看到这个issue了。。。我们的App代码结构为了解耦是不允许在ShareActivity上直接继承平台相关的接口的。
需要Activity的代码是这一段：
```
Activity act = (Activity)handler;    
String callPkg = act.getCallingPackage();
LogUtil.d(TAG, "handleWeiboResponse getCallingPackage : " + callPkg);
if(TextUtils.isEmpty(transaction)) {
    LogUtil.e(TAG, "handleWeiboResponse faild intent _weibo_transaction is null");
    return false;
} else if(!ApiUtils.validateWeiboSign(this.mContext, appPackage) && !appPackage.equals(act.getPackageName())) {
    LogUtil.e(TAG, "handleWeiboResponse faild appPackage validateSign faild");
    return false;
}
```
我认为如果只是需要PackageName和CallingPackage的话有很多种做法吧，这样做让开发者很不方便，只能希望以后的版本能把这个地方稍微修改下

**Comment by vivian8725118** [comment]
也遇到这个坑了，感觉写死成Activity很无力

**Comment by loganguo** [comment]
handleWeiboResponse方法需要的intent参数，是不是要加入“_weibo_appPackage”和“_weibo_appPackage”这两个字段才行。但是不知道“_weibo_appPackage”这个字段对应的值是什么。求解？

**Comment by onion4** [comment]
这么做判断的意图是什么？
