### ISSUE TITLE
Crash when W/chromium(21039): [WARNING:password_handler.cc(206)]

### ISSUE THREAD

**Issue by ranjankumar03** [sinaweibosdk/weibo_android_sdk#175]
I am getting this on hitting custom url from webview on android device. Can anyone help on this?

**Comment by BriceChou** [comment]
@ranjankumar03 
Hi guys,nice to meet u.
First , Can you provide more details for this problem ? 
And what are you planning to do with this Weibo SDK?

**Comment by ranjankumar03** [comment]
@BriceChou 
Thanks. Finally resolved the issue.
