### ISSUE TITLE
com.sina.weibo.sdk.exception.WeiboAuthException: sso package or sign error

### ISSUE THREAD

**Issue by Joy-Whale** [sinaweibosdk/weibo_android_sdk#178]
以前一直没有这个问题，确认包名和签名没问题，但一直提示这个Error，导致SSO授权失败！

**Comment by BriceChou** [comment]
@Joy-Whale 
给您一个思路，你检查一下，看看有没有问题，也希望能够帮助到您！
1. 您的这个包名和签名，有没有填到 [我的应用]
(http://open.weibo.com/apps)  Link URL: http://open.weibo.com/apps 这个页面上？
2. 请您再次确认您的这个包名，跟您实际用的是同一个包名？多一个空格或者少一个空格都会报错，我刚刚去把我的应用包名多添加了一个空格，就报了跟您一样的错误.
3. 请您再次核对，您实际开发用的包名，与您在 “我的应用”中填的包名是一致的。
4. 如果还是报错了，您可能需要添加 .keystore 这个文件.
以上，希望能够帮助到您！
