### ISSUE TITLE
oss web认证，登录页面打开空白

### ISSUE THREAD

**Issue by cococa** [sinaweibosdk/weibo_android_sdk#180]
mSsoHandler.authorizeWeb(new AuthListener());   android 手机上无客户端，一直打不开web 认证的页面，打开后就一直空白

**Comment by BriceChou** [comment]
@cococa 
你可以参考这个 issue #168 上我的回答。
1. 如果您采用了authorizeWeb的方式，必须在manifest文件中，声明添加 WeiboSDK browser.
2. 其次，你需要添加.keystore文件，这个在官方的指导手册上有具体说明文档，如何添加。
3. 最后，

**Comment by cococa** [comment]
@BriceChou 谢谢，WeiboSdkBrowser已经申明了，keystore 的签名和网站的一直，而且我在调试ssohanler 的时候时候打印出的签名也是一致的，我这个问题很奇怪，我重新创建一个项目，然后用一样的key 包名 签名 回调页，跳转到web 是能做登录认证的，但是在自己的正式项目上始终都不能打开，进度条加载完毕后就一直是空白的页面

**Comment by JeffWangGithub** [comment]
遇到了同样的问题

**Comment by cococa** [comment]
呵呵，解决了，是因为组里别的开发设置了webview暂停，@JeffWangGithub  可以检查下看看

**Comment by JeffWangGithub** [comment]
好的，非常感谢，一会儿回去试试


发自 网易邮箱大师
在2016年08月30日 11:55，cocoa 写道:

呵呵，解决了，是因为组里别的开发设置了webview暂停，@JeffWangGithub 可以检查下看看

**Comment by lookis** [comment]
遇到同样的问题，检查过上面提到的两项设置，而且我这边没有设计webview暂停，我这边遇到的异常是：SSLHandshakeException

`10-31 14:44:43.756 7324-21769/com.ihangju D/AidTask: AidTask.java(348) loadAidFromNet: loadAidFromNet WeiboException Msg : javax.net.ssl.SSLHandshakeException
10-31 14:44:43.756 7324-21769/com.ihangju E/AidTask: AidTask.java(209) run: AidTaskInit WeiboException Msg : javax.net.ssl.SSLHandshakeException
10-31 14:44:43.766 7324-7324/com.ihangju W/AwContents: nativeOnDraw failed; clearing to background color.`

**Comment by HolickABC** [comment]
没错 就是暂停的问题  已解决

**Comment by jiantao88** [comment]
1.必须在manifest文件中，声明添加 WeiboSdkBrowser.
2.不执行webview的pauseTimers()方法(即不启用webview的暂停渲染)
