### ISSUE TITLE
vivo手机分享报错

### ISSUE THREAD

**Issue by lindow2009** [sinaweibosdk/weibo_android_sdk#181]
vivo手机分享新浪微博，直接报错
07-26 18:00:55.790 25359 25359 E Parcel  : Class not found when unmarshalling: com.sina.weibo.sdk.api.h
07-26 18:00:55.790 25359 25359 E Parcel  : java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.h
07-26 18:00:55.790 25359 25359 E Parcel  :  at java.lang.Class.classForName(Native Method)
07-26 18:00:55.790 25359 25359 E Parcel  :  at java.lang.Class.forName(Class.java:324)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.os.Parcel.readParcelableCreator(Parcel.java:2383)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.os.Parcel.readParcelable(Parcel.java:2337)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.os.Parcel.readValue(Parcel.java:2243)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.os.Parcel.readArrayMapInternal(Parcel.java:2592)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.os.BaseBundle.unparcel(BaseBundle.java:221)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.os.BaseBundle.putString(BaseBundle.java:430)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.content.Intent.putExtra(Intent.java:6447)
07-26 18:00:55.790 25359 25359 E Parcel  :  at com.sina.weibo.bundlemanager.c.b.newActivity(InstrumentationHook.java:137)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2548)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.app.ActivityThread.access$1000(ActivityThread.java:170)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.os.Handler.dispatchMessage(Handler.java:102)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.os.Looper.loop(Looper.java:148)
07-26 18:00:55.790 25359 25359 E Parcel  :  at android.app.ActivityThread.main(ActivityThread.java:5550)
07-26 18:00:55.790 25359 25359 E Parcel  :  at java.lang.reflect.Method.invoke(Native Method)
07-26 18:00:55.790 25359 25359 E Parcel  :  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:751)
07-26 18:00:55.790 25359 25359 E Parcel  :  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
07-26 18:00:55.790 25359 25359 E Parcel  : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.sdk.api.h" on path: DexPathList[[zip

麻烦新浪微博的哥们好好的维护下这个SDK好么，这么多issue都不解决，而且SDK做成这样，和微信，qq的比起来差太远了，客服什么的就不说了，大写的一个服字
希望新版本好好的修复下这些bug

**Comment by BriceChou** [comment]
自立更生，丰衣足食！
