### ISSUE TITLE
最新版本3.1.4jar无法使用AbsOpenAPI类

### ISSUE THREAD

**Issue by BladeCode** [sinaweibosdk/weibo_android_sdk#183]
项目导入最新SDK的jar，发现提供的文档和jar内容有明显不同
![AbsOpenAPI](http://7xs1zb.com1.z0.glb.clouddn.com/weibo_bug.png)

**Comment by BriceChou** [comment]
@BladeCode 
1. 导入的官方jar包是没有API的，只有直接使用的接口；
2. 如果您需要自己实现某些API接口，比如：AbsOpenAPI类，您需要在Android Studio 中导入 Module 或者 在 Eclipse ADT 中导入Library，之后您可以在您的项目中使用相关的API接口进行重写。
3. 官方提供的文档存在大量的出入，包括返回的JSON数据也会不一样，建议使用Postman此类工具，先进行Request请求获取到实际的JSON数据，然后再进行接口重写解析。
以上，希望能够帮助到您！如果需要了解更多在开发中遇见的问题，您可以查看相关issue，祝你工作愉快!
