### ISSUE TITLE
在小屏幕（智能手表）设备上开发，授权登录不好实现 

### ISSUE THREAD

**Issue by zhoujunhua** [sinaweibosdk/weibo_android_sdk#185]
我们公司计划在智能手表设备上开发微博相关功能，但是存在以下问题：
1、智能手表（Android5.1系统）设备上没有新浪微博客户端。
2、屏幕比较小，当使用网页授权的形式时，布局排版拥挤，交互效果极差，基本无法使用。
不知道有没有什么好的办法解决，求解？

**Comment by BriceChou** [comment]
@zhoujunhua 
* 这个项目貌似没有人在维护，不过这个问题我曾经看过，当时是想知道那个Web授权的窗体是怎么弹出来的，然后看微博的源码，发现这个你可以自己重写。
* 它本质上是调用了一个底层的 android chromium,打开一个网页链接，之后再在外层包装了一个窗体，之后你就看见了那个所谓的网页授权窗体。
所以，我觉得您还是通过加载一个 moudle 的方式，或者导入library的方式（请注意：不是使用导入jar包的方式）。最后，你可以研究一下它的窗体实现方式，然后根据实际情况仿照写一个就可以了。
