### ISSUE TITLE
SDK包含支付功能，如何去掉

### ISSUE THREAD

**Issue by szpnygo** [sinaweibosdk/weibo_android_sdk#188]
百度平台个人开发者不允许上传含有支付功能的。

但是微博SDK含有支付功能，我并不需要支付功能，我只是用了一键登录，怎么办？

**Comment by BriceChou** [comment]
@szpnygo 
#### 你下载一个老版本不就可以了。3.14 以前的版本都不支持支付功能的。
* 1. 你Fork这个项目，之后同步到你的本地;
* 2. 然后进行版本回退，退回到3.1.1的版本;
* 3. 最后把里面的Jar包或者Library添加到你的项目即可。

**Comment by szpnygo** [comment]
@BriceChou 我直接从包里把一个Pay的包删掉了，试试能审核过不

**Comment by huangbaohuacn** [comment]
@szpnygo 可以通过吗？

**Comment by szpnygo** [comment]
@huangbaohuacn 通过了，我解压删除api/pay这个包，再打包回去。就可以了。审核也通过了
