### ISSUE TITLE
回调白屏

### ISSUE THREAD

**Issue by ramesyang** [sinaweibosdk/weibo_android_sdk#191]
在使用SDK进行客户端分享后，不管成功或失败，有时候都会白屏。不知道是啥原因！shareSDK的官方更新2.6.6版本的时候说解决了这个问题，[点此](http://wiki.mob.com/sharesdk-android-%E6%9B%B4%E6%96%B0%E5%8E%86%E5%8F%B2/)。但是客服不给说是怎么解决的，唉！如果有人有遇到这个问题的，请一起交流交流！

**Comment by BriceChou** [comment]
* Weibo SDK 什么时候还有这个官方网站啊？
* 这里难道不是它的唯一官方代码所在地？？？？？

**Comment by StrangerMosr** [comment]
同样的问题，主要是你们把后台微博的所有进程杀掉 再分享回来必定白屏。看了一下 Activity主题透明时候必现！还有一个问题，如果不写公共的Activity进行分享，回调回来两个Activity 都设置了Action 他都不知道往哪里跳
