### ISSUE TITLE
Android分享到微博，支持图片吗

### ISSUE THREAD

**Issue by amyliu1062** [sinaweibosdk/weibo_android_sdk#196]
`WeiboMultiMessage weiboMessage = new WeiboMultiMessage();
            weiboMessage.textObject = textObject;
            weiboMessage.imageObject = imageObject;
 // 2. 初始化从第三方到微博的消息请求
        SendMultiMessageToWeiboRequest request = new SendMultiMessageToWeiboRequest();
        // 用transaction唯一标识一个请求
        request.transaction = String.valueOf(System.currentTimeMillis());
        request.multiMessage = weiboMessage;
        // 3. 发送请求消息到微博，唤起微博分享界面
        mWeiBoAPI.sendRequest(this, request);
`
使用这种方式分享图文，没有任何反应

**Comment by BriceChou** [comment]
@amyliu1062 
* 这个微博API是支持图片分享的，你可以看看 #177 的 issue，你是不是报了同样的错误！
* 希望能够帮助到您！

**Comment by shanshanpt** [comment]
能够分享多张图片？不能吧？
