### ISSUE TITLE
没有微博客户端，走H5分享，无法登陆，点击登陆按钮日志如下

### ISSUE THREAD

**Issue by kshw123** [sinaweibosdk/weibo_android_sdk#198]
I/chromium: [INFO:CONSOLE(893)] "Uncaught ReferenceError: jsError is not defined", source: https://passport.weibo.cn/js/signin/weibologin.js?v=2016090801 (893)

**Comment by woxingxiao** [comment]
+1

**Comment by q397580458** [comment]
+1，同时在努比亚手机上，安装了微博客户端，也会走H5授权，

**Comment by wxqee** [comment]
＋1

**Comment by pgsheng** [comment]
+1，前二十几天测试还可以登录，现在点击网页登录没响应，新浪微博的人都不维护了吗，

**Comment by hamberluo** [comment]
+1

**Comment by shanshanpt** [comment]
+1

**Comment by zewenwang** [comment]
+1 未安装微博客户端，走H5分享调起失败，并且把本地的cookie全部清除了，

**Comment by liuyuejinqiu** [comment]
+1 未安装客户端，H5分享失败
