### ISSUE TITLE
新浪微博分享失败

### ISSUE THREAD

**Issue by 18311023368** [sinaweibosdk/weibo_android_sdk#20]
测试步骤:
1.新浪微博客户端安装未登录
2.在第三方应用内点击微博分享按钮进入到微博登录页面
3.输入账号密码登录成功后直接返回第三方应用中提示auth failed  
     WBConstants.ErrorCode.ERR_FAIL
4.再次点击微博分享按钮才可以进入到微博发布页面进行分享
问题：新浪客户端没有登录第一次分享不成功
正常现象：在登录成功后应该直接进入微博发布页面进行分享

**Comment by BTyang** [comment]
现在还是有这个问题啊。
4.再次点击微博分享按钮才可以进入到微博发布页面进行分享  demo里的情况是只要不关闭WBShareActivity重新进入，点击分享按钮永远是auth failed。

**Comment by tianzhijiexian** [comment]
不是很容易复现，但是确实会出现

**Comment by MrUncleYzw** [comment]
为什么我每次第一次安装了微博，在用自己的应用去分享，第一次总会不成功（必现，不装微博app使用网页端分享没问题），又是甚至要进行3-4次才会成功之后才会正常使用分享。是第一次没登录还是什么？错误码是2

**Comment by tianzhijiexian** [comment]
@MrUncleYzw 试试通过这个库解决下问题

**Comment by SHR-NAME** [comment]
我也遇到了这种情况，提示auth failed，但是进入微博客户端之后，杀死第三方应用从新进入，然后分享就可以了。这个怎么解决？

**Comment by Freerain9** [comment]
我也碰到了同样的问题 第一次分享不成功 感觉挺郁闷的

**Comment by oOEdoOo** [comment]
删除微博，重新安装，然后在应用里点分享，这个错误必现，一年了都没人理这个错么？

**Comment by oOEdoOo** [comment]
两年了！
