### ISSUE TITLE
未安装微博客户端时，调用H5分享，出现错误：upload pic faild

### ISSUE THREAD

**Issue by zewenwang** [sinaweibosdk/weibo_android_sdk#200]
调用"http://service.weibo.com/share/mobilesdk_uppic.php"后，返回{"code":0,"data":""}，
执行：`req.sendSdkErrorResponse(WeiboSdkBrowser.this, "upload pic faild");`

用WeiboSDKDemo_3.1.4.apk分享文字+图片，出现相同问题

**Comment by zewenwang** [comment]
请尽快解决

**Comment by liuyuejinqiu** [comment]
同样遇到此问题，给新浪发了邮件，现在没收到相关回复，不知原因在哪

**Comment by zhenghaiqiang** [comment]
遇到了同样的问题，线上的几个版本都不能分享了

**Comment by zewenwang** [comment]
没人维护， 只能把微博H5分享去掉了
