### ISSUE TITLE
google市场漏洞问题

### ISSUE THREAD

**Issue by andrewhunter0** [sinaweibosdk/weibo_android_sdk#203]
Google市场报如下的警告，不修复将被下线，这个问题如何处理，我见最新SDK也并没有处理onReceivedSslError方法，只是加了判断，然后Log了一个，if外面super.onReceivedSslError了一下：
public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error)
  {
    if (this.mCallBack != null) {
      this.mCallBack.onReceivedSslErrorCallBack(view, handler, error);
    }
    super.onReceivedSslError(view, handler, error);
  }
onReceivedSslErrorCallBack方法等于啥也没干
public void onReceivedSslErrorCallBack(WebView view, SslErrorHandler handler, SslError error)
  {
    LogUtil.d(TAG, "onReceivedSslErrorCallBack.........");
  }
等于没有处理，这样能通过Google市场的检查么？

Google报问题如下：
Your app(s) listed at the end of this email are still using an unsafe implementation of the WebViewClient.onReceivedSslErrorHandler. You can also see the list of affected apps, as well as details such as version numbers and class names, on the Alerts page in your Developer Console.
Your current implementation ignores all SSL certificate validation errors, making your app vulnerable to man-in-the-middle attacks. An attacker could change the affected WebView's content, read transmitted data (such as login credentials), and execute code inside the app using JavaScript.

What’s happening

Starting November 25, 2016, Google Play will block publishing of any new apps or updates that contain this vulnerability. Your published APK version will remain unaffected, however any updates to the app will be rejected unless you address this vulnerability.

Action required

To properly handle SSL certificate validation, change your code to invoke SslErrorHandler.proceed() whenever the certificate presented by the server meets your expectations, and invoke SslErrorHandler.cancel() otherwise.
If you are using a 3rd party library that’s responsible for this, please notify the 3rd party and work with them to address the issue.
After making changes, sign in to your Developer Console and submit the updated version of your app.
Check back after five hours - we’ll show a warning message if the app hasn’t been updated correctly.

我准备将SDK里的onReceivedSslError方法直接干掉，或者使用handler.cancel();
不知道是否会对打开的web授权界面的时候有影响？自己测试是没有问题，既然没有问题，SDK没必要重写onReceivedSslError方法吧。

**Comment by plrthink** [comment]
你好，请问你是怎么更改的，我也遇到了这个问题，我还是新手，想自己更改代码，但不知从哪里去改
