### ISSUE TITLE
Issue run demo app in Android Studio

### ISSUE THREAD

**Issue by lieng** [sinaweibosdk/weibo_android_sdk#211]
<img width="1175" alt="screen shot 2016-11-16 at 2 43 41 pm" src="https://cloud.githubusercontent.com/assets/2325989/20368941/312dc0a0-ac0b-11e6-90d5-793b99224f89.png">

**Comment by shijia109** [comment]
有几张图片需要删掉，因为他们扩展名是png，实际不是png编码，studio跑不起来
