### ISSUE TITLE
登录过程提示输入验证码，但是验证码显示不出来，也无验证码输入框

### ISSUE THREAD

**Issue by luyun210** [sinaweibosdk/weibo_android_sdk#212]
机型为红米note3
![image](https://cloud.githubusercontent.com/assets/8034436/20391296/bd1e6472-ad0d-11e6-9cff-1815b4dca8cd.png)

**Comment by BriceChou** [comment]
估计是它更新了API接口，却没有更新当前WebSDK使用的UI。

**Comment by luyun210** [comment]
迅雷，喜马拉雅好多第三方的微博登录都有这个问题
