### ISSUE TITLE
使用签名工具（app_signatures.apk），没有生成出来签名？

### ISSUE THREAD

**Issue by e-lin** [sinaweibosdk/weibo_android_sdk#216]
我在Android Studio產生了app-debug.apk，然後把我自己的app安裝到手機上。然後使用簽名工具想生成MD5簽名。但是生成失敗。
我的app包名是「plaxx.co.xxx.xxx」

我給手機也安裝了weibo-android-sdk-demo的app，同樣嘗試用簽名工具想生成MD5簽名。輸入包名「com.sina.weibo.sdk.demo」，結果也沒生成簽名。

為什麼呢？

**Comment by e-lin** [comment]
結尾多一個空白所以沒生成。

**Comment by xiemuyou** [comment]
+1
