### ISSUE TITLE
Error:Could not find com.sina.weibo.sdk:openDefault:1.0.0

### ISSUE THREAD

**Issue by scutcl** [sinaweibosdk/weibo_android_sdk#229]
是不是新的依赖没有上传上去啊？

**Comment by imknown** [comment]
抽了, `aar 版本` 貌似是个谜
> https://bintray.com/thelasterstar/maven/openDefault

**Comment by Larnoo** [comment]
为啥默认的地址readme提供的地址不可用呢？@imknown
你给的这个可以

**Comment by imknown** [comment]
@Larnoo 估计是 `新浪微博` 由于某种原因, 发布到 `JFrog jcenter` 仓库 没过审.
> https://github.com/sinaweibosdk/weibo_android_sdk/commit/b17afef8d9e8b9c8291f85ca340d52016ab17b2f

所以得写上 他的  `Bintray` 私库:
> https://dl.bintray.com/thelasterstar/maven/

他的 `openDefault` 和 `core` 我分不清楚...

**Comment by imknown** [comment]
@jiachenning 看这里 https://github.com/sinaweibosdk/weibo_android_sdk/issues/229#issuecomment-286040517

**Comment by jiachenning** [comment]
@imknown  多谢，已经看到了。我再看一下这个仓库是不是微博官方的，还有readme和你都写着openDefault，链接里面是core。。。

**Comment by imknown** [comment]
@jiachenning 我分析是官方的. 无论是 创建时间, 还是 作者, 都和 github 的吻合. 不会这么巧吧.
- zhu xuesong: https://bintray.com/thelasterstar
- xuesong6: https://github.com/sinaweibosdk/weibo_android_sdk/commit/843d578604c46653b8dc12d1946b0b52fe66f972

**Comment by sinaweibosdk** [comment]
由于刚接手，官方的仓库还没找到对接人，先自己申请了一个，发布的时候好几个版本。
