### ISSUE TITLE
第一次授权分享到微博后，会直接返回分享页提示auth failed，等几分钟再分享又好了。。第一次授权必现

### ISSUE THREAD

**Issue by linxhome** [sinaweibosdk/weibo_android_sdk#231]
跟了一下代码，sdk里应该是lauch了微博客户端，然后客户端不知道什么原因直接认定auth failed，返回到分享页时就提示分享失败了，验证过token等值都没有问题，并且过一两分钟再分享，又可以了。认定应该是微博客户端的问题。 Web分享没有问题，然后新的版本里不支持在有客户端的情况下使用Web分享。

不知道这个问题能不能通过SDK解决，可以联系我提交bug info 。 mail : linxome@gmail.com

**Comment by sinaweibosdk** [comment]
这个问题存在于7.3.0以前版本的微博客户端中，接入sdk时为了防止该问题出现。当前的委婉解决方案是先确认是否已经登录授权，如果没有授权，先进行SSO授权再进行分享。

**Comment by imknown** [comment]
这个问题 文档里面提到了.
