### ISSUE TITLE
Error:Could not find com.sina.weibo.sdk:openDefault:1.0.0

### ISSUE THREAD

**Issue by NestleSprite** [sinaweibosdk/weibo_android_sdk#233]
？

**Comment by imknown** [comment]
Duplicate #229 .

**Comment by Larnoo** [comment]
Error:(120, 13) Failed to resolve: com.sina.weibo.sdk:openDefault:1.0.0

**Comment by titanseason** [comment]
我也是， compile 'com.sina.weibo.sdk:openDefault:1.0.0:openDefaultRelease@aar'
提示：Failed to resolve: com.sina.weibo.sdk:openDefault:1.0.0
