### ISSUE TITLE
为什么给出的Api文档和v3.2的sdk不一致？

### ISSUE THREAD

**Issue by Larnoo** [sinaweibosdk/weibo_android_sdk#234]
Readme中给出的API文档：http://sinaweibosdk.github.io/weibo_android_sdk/doc/

但是v3.2的Sdk中，像com.sina.weibo.sdk.api.WebpageObject都被移除了，但是Api文档中怎么都还有？

好不容易等到了Api文档，结果是错的....

**Comment by imknown** [comment]
~~感觉 `v3.2` 是 `新浪` 试水 `Gradle` 的 `试验品` + `半成品`. 实在是个 **`迷`**.~~
~~最近 `腾讯微信平台` 也开始搞 `gradle`, 也是 一堆问题.~~
~~`SDK demo 代码` 和 `文档` 的 质量, 咳咳...~~

**Comment by imknown** [comment]
`WebpageObject` 感觉 不能再用了, `singleMessage` 方法 我看 `v3.2` 新 Demo 已经移除了.

**Comment by czy1121** [comment]
唉，这么大个厂，一个gradle都搞不定么
