### ISSUE TITLE
v3.2.0 使用 UsersAPI 报405错

### ISSUE THREAD

**Issue by imknown** [sinaweibosdk/weibo_android_sdk#238]
代码逻辑 使用了 `v3.1.4` 的.
`v3.2.0` debug 拼接出来的 url 在 浏览器 可以获取到正确的 `json`.
但是 `v3.2.0` 使用 `OpenAPI` 的 `UsersAPI`, 直接 `405`.
> com.sina.weibo.sdk.exception.WeiboException: java.io.FileNotFoundException: https://api.weibo.com/2/users/show.json

反编译看, 原来是 `com.sina.weibo.sdk.net.NetworkManager` `v3.1.4` 用的是 `HttpClient`, `v3.2.0` 用的是 `HttpUrlConnection`

**Comment by lypoint** [comment]
我用v3.2.0分享微博时也是 java.io.FileNotFoundException，不过我看返回的ResponseCode应该是报了415错误。

**Comment by sinaweibosdk** [comment]
3.2版本已经取消了open api接口相关，下来是否继续存在还不确定。

**Comment by imknown** [comment]
@sinaweibosdk Hi, 谢谢回复. 这样的话 SDK 以后只能 `授权` 和 `分享`了吧. :crying_cat_face:

**Comment by LFen** [comment]
@sinaweibosdk 那是说3.2版本就拿不到用户的性别等详细信息了？

**Comment by DjcKen** [comment]
这个问题有人知道怎么解决吗？现在QQ群也满了，邮件发出去又被退回，真的是。。。难道没人维护？
