### ISSUE TITLE
SDK 3.2 版本获取用户信息报错

### ISSUE THREAD

**Issue by LFen** [sinaweibosdk/weibo_android_sdk#242]
微博SDK3.2版本，授权成功后，调用UsersAPI.show(long uid, RequestListener listener)这个接口去获取用户信息的时候，会报如下错误：
java.io.FileNotFoundException: https://api.weibo.com/2/users/show.json

上一个SDK版本是正常的。

**Comment by imknown** [comment]
Duplicate #238 .

**Comment by LFen** [comment]
那是说3.2版本就拿不到用户的性别等详细信息了？

**Comment by imknown** [comment]
极有可能.

**Comment by LFen** [comment]
这个版本一定要升级吗？因为我收到邮件说在6月30号之前要升级
不升级的话会有什么影响

**Comment by imknown** [comment]
@LFen 不知道, 我不是工作人员.
:(

**Comment by DjcKen** [comment]
同样遇到这个问题了。有解决方案吗？

**Comment by DjcKen** [comment]
同遇。

**Comment by tianzhijiexian** [comment]
微博这个还有人维护么？

**Comment by yunchengWan** [comment]
返回字段里面有com.sina.weibo.intent.extra.NICK_NAME以及com.sina.weibo.intent.extra.USER_ICON，这两个是基本信息么，USER_ICON是头像字段么

**Comment by LFen** [comment]
@yunchengWan 应该是，但是获取不到性别

**Comment by imknown** [comment]
@tianzhijiexian 惊现 Kale !!

**Comment by jiachenning** [comment]
@tianzhijiexian 现在应该是用户名叫xuesong的哥们在维护，但是貌似是个新手。。。

**Comment by wystyle1** [comment]
这个应该是sdk的网络请求bug，可以暂时用其他的请求框架去请求，是可以请求的

**Comment by imknown** [comment]
@wystyle1 对, 参看 #238
