### ISSUE TITLE
SDK3.2分享 WeiboMultiMessage 中没有mediaObject 如何分享链接啊

### ISSUE THREAD

**Issue by olivermsw** [sinaweibosdk/weibo_android_sdk#243]

**Comment by imknown** [comment]
参看
> https://github.com/sinaweibosdk/weibo_android_sdk/issues/234#issuecomment-287683640
> [WBShareActivity#sendMultiMessage](https://github.com/sinaweibosdk/weibo_android_sdk/blob/master/weibosdkdemo/app/src/main/java/com/sina/weibo/sdk/demo/WBShareActivity.java#L177)

**Comment by olivermsw** [comment]
1

**Comment by imknown** [comment]
@olivermsw 没有就删掉呗, 我都是完全按照 新SDK 重写了.
