### ISSUE TITLE
Open API 新旧接口无法分享带图片的微博

### ISSUE THREAD

**Issue by hiyangyue** [sinaweibosdk/weibo_android_sdk#246]
**旧的新的接口都无法上传图片。**

```
 mStatusesAPI = new StatusesAPI(context, LibShareConstants.WEIBO_API_KEY,token);
 Drawable drawable = context.getResources().getDrawable(R.drawable.app_logo_with_white_corner);
 Bitmap bitmap = ((BitmapDrawable) drawable).getBitmap();
 mStatusesAPI.upload("发送一条带本地图片的微博", bitmap, null, null, mListener);
```

### 旧的接口(statuses/upload) error : 
> {
	"error": "unsupport mediatype (application/x-www-form-urlencoded)",
	"error_code": 10007,
	"request": "/2/statuses/upload.json"
}

回调的error :

> java.io.FileNotFoundException: https://api.weibo.com/2/statuses/upload.json

### 新的接口(statuses/share) error :

回调error : 
> {
	"error": "auth by Null spi!",
	"error_code": 21301,
	"request": "/2/statuses/share.json"
}

回调error :
> java.io.FileNotFoundException: https://api.weibo.com/2/statuses/share.json

**Comment by imknown** [comment]
参看
- https://github.com/sinaweibosdk/weibo_android_sdk/issues/238
- https://github.com/sinaweibosdk/weibo_android_sdk/issues/242

**Comment by hiyangyue** [comment]
@imknown  感谢回复，我看其他人有说 其他的请求框架可以请求，我先试试。
