### ISSUE TITLE
com.sina.weibo.sdk.component.WeiboSdkBrowser ClassNotFoundException

### ISSUE THREAD

**Issue by e-snail** [sinaweibosdk/weibo_android_sdk#252]
我在项目中把新浪SDK中的class打成DEX文件，在需要的用新浪账号登陆的时候再加载DEX。于是，在部分手机上发现有找不到com.sina.weibo.sdk.component.WeiboSdkBrowse这个类的情况，报错ClassNotFoundException。

我的问题是，这个activity是从哪里启动的？新浪SDK的jar中找不到使用这个类的地方。莫非是从动态库里启动的？

**Comment by e-snail** [comment]
这个类到底是干啥的？我把它从Manifest中去掉行不行？
@sinaweibosdk

**Comment by imknown** [comment]
删掉即可

**Comment by e-snail** [comment]
@imknown 你试过吗？

**Comment by imknown** [comment]
@e-snail 我用了这么久微博 SDK, 从来都不写它.

**Comment by e-snail** [comment]
这个好像是没安装微博客户端的情况下被调用的。

**Comment by imknown** [comment]
我手机从来不装微博客户端, web 授权登录 web 分享 也好使.

**Comment by HanteIsHante** [comment]
@imknown   为什么 web 授权登录显示空白页啊? 请问什么造成的?
