### ISSUE TITLE
新版分享成功后 问题

### ISSUE THREAD

**Issue by Luckylll** [sinaweibosdk/weibo_android_sdk#258]
分享成功后，触发分享页面新开一个，点击再返回上一页面，提示分享取消，并不是分享成功

**Comment by zhuhuang521** [comment]
update version 2.0.2

**Comment by Luckylll** [comment]
现在没有新触发界面了，但是分享成功后还是弹分享取消

**Comment by Jungerr** [comment]
分享成功后传回的_weibo_resp_errcode为1，回调了callBack cancel
