### ISSUE TITLE
2.0.1版本SDK分享成功或者取消分享后回调业务方Activity两次onNewIntent问题

### ISSUE THREAD

**Issue by QichaoChen** [sinaweibosdk/weibo_android_sdk#262]
新版SDK 2.0.1调试发现：不管是成功分享还是取消分享WbShareTransActivity会都执行onActivityResult和onNewIntent方法，导致调用方出现两次onNewIntent方法

**Comment by QichaoChen** [comment]
相关问题：#258 #257

**Comment by zhuhuang521** [comment]
update version 2.0.2
