### ISSUE TITLE
微博卸载后，判断是否安装客户端不正确

### ISSUE THREAD

**Issue by Jungerr** [sinaweibosdk/weibo_android_sdk#266]
SDk的源码中WeiboAppManager是单例的，而WbAppInfo做了缓存处理。
所以，卸载微博后，通过WbAppInfo来判断是否安装客户端就不正确了。
而这个错误的状态判断，导致我无法及时清除SDK创建的名为"com_sina_weibo_sdk"的SharedPreferences文件。
最终导致我无法修复 SDK的卸载微博后不能调起网页分享的bug。

相关源码：

    public static synchronized WeiboAppManager getInstance(Context context) {
        if(sInstance == null) {
            sInstance = new WeiboAppManager(context);
        }

        return sInstance;
    }

    public synchronized WbAppInfo getWbAppInfo() {
        if(this.wbAppInfo == null) {
            this.wbAppInfo = this.queryWbInfoInternal(this.mContext);
        }
        return this.wbAppInfo;
    }

**Comment by imknown** [comment]
重新安装亦有此问题. 所以我没做缓存, 每次都是 暴力 new 一个.

**Comment by HanteIsHante** [comment]
@Jungerr  @imknown   请教一下，你们是怎么实现web 分享的?  我的web 授权为什么页面显示空白?用这个混合的授权，只能吊起本地客户端，web 端就调用不出来

**Comment by MrHangVIP** [comment]
sina 真的不负责任，除了问题都不解决。这么多issues也没人管。我也是服。

**Comment by MrHangVIP** [comment]
我目前是这么做的。自己做客户端是否安装的判断如果安装直接调用web分享。

**Comment by MrHangVIP** [comment]
Field field = null;
		try {
			field =WeiboAppManager.class.getDeclaredField("wbAppInfo");
		} catch (NoSuchFieldException e) {
			e.printStackTrace();
		}
		field.setAccessible(true);
		try {
			field.set(WeiboAppManager.getInstance(mActivity),null);//重置为null
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}

我们可以通过反射来重置这个appInfo的信息
