### ISSUE TITLE
java.lang.NoSuchFieldException

### ISSUE THREAD

**Issue by ezfantasy** [sinaweibosdk/weibo_android_sdk#268]
多次切换不同的帐号 进行授权登录操作会出现（版本openDefault-2.0.3）
05-08 19:52:42.966 26121-26121/? W/System.err: java.lang.NoSuchFieldException: No field mLastSrvView in class Landroid/view/inputmethod/InputMethodManager; (declaration of 'android.view.inputmethod.InputMethodManager' appears in /system/framework/framework.jar:classes2.dex)
05-08 19:52:42.966 26121-26121/? W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
05-08 19:52:42.966 26121-26121/? W/System.err:     at com.sina.weibo.utils.bh.a(FixLeakUtils.java:43)
05-08 19:52:42.966 26121-26121/? W/System.err:     at com.sina.weibo.bundlemanager.c.a.callActivityOnDestroy(InstrumentationHook.java:347)
05-08 19:52:42.967 26121-26121/? W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3825)
05-08 19:52:42.968 26121-26121/? W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3856)
05-08 19:52:42.968 26121-26121/? W/System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:153)
05-08 19:52:42.968 26121-26121/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
05-08 19:52:42.968 26121-26121/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
05-08 19:52:42.968 26121-26121/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-08 19:52:42.968 26121-26121/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5438)
05-08 19:52:42.968 26121-26121/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-08 19:52:42.968 26121-26121/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
05-08 19:52:42.968 26121-26121/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by blxuc** [comment]
你好，请问这个问题你是怎么解决的？我这也出现了同样的问题

**Comment by blxuc** [comment]
你好，请问这个问题你是怎么解决的？我这也出现了同样的问题
