### ISSUE TITLE
com.sina.weibo.remotessoservice

### ISSUE THREAD

**Issue by MrHangVIP** [sinaweibosdk/weibo_android_sdk#270]
隐式打开service 在5.0 报错

**Comment by MrHangVIP** [comment]
Service Intent must be explicit: Intent { act=com.sina.weibo.remotessoservice }

**Comment by MrHangVIP** [comment]
intent = new Intent("com.sina.weibo.remotessoservice");
            return context.bindService(intent, this.mConnection, 1);

  at com.sina.weibo.sdk.auth.sso.SsoHandler.bindRemoteSSOService(SsoHandler.java:285)

**Comment by sinaweibosdk** [comment]
请升级到最新的sdk版本中
