### ISSUE TITLE
正式版本调用 web 授权，为什么没有登陆框，只显示一个空白页面，上方提示微博登录

### ISSUE THREAD

**Issue by HanteIsHante** [sinaweibosdk/weibo_android_sdk#273]

**Comment by beiying** [comment]
我也出现了这种情况，logcat会打印：E/ActivityThread: Failed to find provider info for com.sina.weibo.sdkProvider，不知道是什么原因，楼主解决了吗

**Comment by SeekingForever** [comment]
我的总是提示net：： ERR_TIMED_OUT，但我的网络是通的，不知lz有没有解决

**Comment by HanteIsHante** [comment]
没有解决啊，不知什么原因造成的

**Comment by HanteIsHante** [comment]
检查一下  SCOPE  是否正确，同 WeiBo  demo  对比下
