### ISSUE TITLE
2.0.3arr的fragment的onActivityResult方法拿不到回调

### ISSUE THREAD

**Issue by woniu0936** [sinaweibosdk/weibo_android_sdk#274]

**Comment by WTree** [comment]
你试试通过Activity 把onActivityResult 传递给Fragment

**Comment by 742340082** [comment]
遇到同样问题，有知道解决的吗？

**Comment by jialanmo** [comment]
启动是从fragment所属的activity走的，回调到activity的onActivityResult上了，需要传给fragment
希望改正
