### ISSUE TITLE
能不能同步到  jcenter

### ISSUE THREAD

**Issue by Nohere** [sinaweibosdk/weibo_android_sdk#279]
能不能同步到  jcenter，不然依赖都要加个url 很麻烦

**Comment by imknown** [comment]
`maven { url "https://dl.bintray.com/thelasterstar/maven/" }` 就是 jCenter..

**Comment by Nohere** [comment]
@imknown 没有add to jcenter 。需要额外配这个url,这个很蛋疼。

**Comment by imknown** [comment]
@Nohere 应该是放到 jCenter 了, 但是不知道问什么 抽了. 我推测是改名了..

**Comment by Nohere** [comment]
@imknown 那么能不能再搞一下，把它弄上去

**Comment by imknown** [comment]
@Nohere 应该可以吧.. 不过我觉得 你应该催不动官方去行动...

**Comment by yongjhih** [comment]
```gradle
    compile 'com.infstory:weibo-android-sdk:3.1.4'
```

ref. https://github.com/8tory/weibo-android-sdk

**Comment by wang-qian** [comment]
可以从https://dl.bintray.com/thelasterstar/maven/com/sina/weibo/sdk/core/ 下载你想要的版本的aar文件,然后上传到自己公司的maven私服.
