### ISSUE TITLE
分享卡屏

### ISSUE THREAD

**Issue by liyuangen** [sinaweibosdk/weibo_android_sdk#289]
微博第一次分享返回APP出现卡屏，原因：界面表明覆盖了一层包名为com.sina.weibo的FrameLayout，第二次分享就不会出现，杀死微博后重新分享再次出现

**Comment by zhimeiyue** [comment]
加下面那段代码试试：

	@Override
	protected void onNewIntent(Intent intent) {
		super.onNewIntent(intent);
		shareHandler.doResultIntent(intent,this);
	}

**Comment by zhouxinzhijian** [comment]
加了，没用啊
