### ISSUE TITLE
Android 网页分享 分享成功返回后的2个bug

### ISSUE THREAD

**Issue by zhangzeyu** [sinaweibosdk/weibo_android_sdk#295]
操作：ALL IN ONE方式分享成功后倒数3秒自动关闭之前手动点返回。
bug1：走分享取消回调（之前已有人反馈）。
bug2：两三秒后重新调起了分享页面。
注：官方demo也有这两个问题。其他人是否也遇到相同的问题？

**Comment by sinaweibosdk** [comment]
新版本中即将解决

**Comment by lijun952048910** [comment]
请问最新版已经解决了么
