### ISSUE TITLE
Android O Change

### ISSUE THREAD

**Issue by Andyang1010** [sinaweibosdk/weibo_android_sdk#299]
Hi   
       由于Android O发生了较大改变,导致之前的很多code无法继续适配O,例如:BroadCast,Service,之前的写法在O手机就无法运行, 
目前我们正在修改自己code,不过为了更好的使用SDK,特此把在开发中遇到的一些问题提出来,      
在code中我们收到的一些WB自定义broadcast(no signature permission protection) 我们在O上接收不到
`https://developer.android.google.cn/preview/behavior-changes.html`

**Comment by sinaweibosdk** [comment]
感谢提醒
