### ISSUE TITLE
微博分享 WbSdk初始化问题

### ISSUE THREAD

**Issue by Larnoo** [sinaweibosdk/weibo_android_sdk#302]
` WbSdk.install(this,new AuthInfo(appKey, redirectUrl, scope));`

我只用SDK做微博分享（只做调用客户端的分享），需要传递`redirectUrl`,`socpe`参数吗？
如果需要传递`redirectUrl`,`socpe`分别需要传什么值？

**Comment by sinaweibosdk** [comment]
阅读接入文档
