### ISSUE TITLE
微博客户端未登录的情况下取消分享无法拿到回调

### ISSUE THREAD

**Issue by YuZhiLiang** [sinaweibosdk/weibo_android_sdk#303]
**SDK版本3.14:**

**Bug1:**
我们的APP拉起未登录的微博客户端进行分享，此时微博客户端会打开登录页面，此时不登录，点击左上角的关闭按钮，微博退出，我们的APP没有收到回调

**Bug2:**
我们的APP拉起未登录的微博客户端进行分享，此时微博客户端会打开登录页面，使用电话号码加短信验证码登录微博，登录成功后我们的分享没有执行，且我们的APP被清栈，在微博中点击返回键不会返回到我们的APP而是进入到桌面

**Comment by sinaweibosdk** [comment]
接入最新的sdk版本 2.0.8
