### ISSUE TITLE
打包混淆要过滤哪些东西？

### ISSUE THREAD

**Issue by cvvbbo** [sinaweibosdk/weibo_android_sdk#304]
要过滤哪些东西？？求告知？？

**Comment by cvvbbo** [comment]
打开了最基础的mindtypeable生成的包直接不能运行，还是说混淆要再在开放平台申重新填md5的秘钥?原来的第一个md5打包没有开任何东西？求告知，现在不敢乱来，怕出错

**Comment by sinaweibosdk** [comment]
-keep class com.sina.weibo.sdk.** { *; } 请阅读readme里的介绍

**Comment by AITUncle** [comment]
> -keep class com.sina.weibo.sdk.** { *; } 请阅读readme里的介绍

真实6啊，真个sdk都keep住，sdk内也没混淆

**Comment by AITUncle** [comment]
> -keep class com.sina.weibo.sdk.** { *; } 请阅读readme里的介绍

真实6啊，整个sdk都keep住，sdk内也没混淆。
新浪的技术，也就这样
