### ISSUE TITLE
替换自己申请的appkey后授权web登录界面是空白的

### ISSUE THREAD

**Issue by JtangXian** [sinaweibosdk/weibo_android_sdk#305]
sso授权web 登录界面只有title 跟关闭按钮 没有用户名密码输入框， 没有错误提示，请问是什么情况
![image](https://user-images.githubusercontent.com/10399088/28812114-b02dd892-76c5-11e7-8ba2-89a479243525.png)

**Comment by sinaweibosdk** [comment]
需要保证appkey,package,签名一致
