### ISSUE TITLE
为什么要在onNewIntent里面处理逻辑

### ISSUE THREAD

**Issue by dwrstc** [sinaweibosdk/weibo_android_sdk#310]
最新的sdk文档里面提到：
处理分享回调，重写onNewIntent 方法

你们怎么能确保sdk使用者的onNewIntent没有其它逻辑呢;每次分享完毕，或者取消分享，都会走一遍onNewIntent会出现很多不可预测的问题

**Comment by maocanmao** [comment]
你可以自行建立一个Activity来统一处理weibo的回调
