### ISSUE TITLE
Google Play Store rejected app with weibo sdk

### ISSUE THREAD

**Issue by andrewkkchan** [sinaweibosdk/weibo_android_sdk#313]
![screen shot 2017-08-21 at 2 31 09 pm](https://user-images.githubusercontent.com/3039405/29507812-590070f6-8684-11e7-916b-9a1a6c7daed5.png)

**Comment by plrthink** [comment]
any updates? I'm facing the same issue

**Comment by tianzhijiexian** [comment]
what?
