### ISSUE TITLE
crash with sdk 4.1 when start WbShareToStoryActivity

### ISSUE THREAD

**Issue by eaggle** [sinaweibosdk/weibo_android_sdk#317]
E/AndroidRuntime(30239): Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.example.kkadapter.NewSerializable)
E/AndroidRuntime(30239): 	at android.os.Parcel.readSerializable(Parcel.java:2384)
E/AndroidRuntime(30239): 	at android.os.Parcel.readValue(Parcel.java:2203)
E/AndroidRuntime(30239): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
E/AndroidRuntime(30239): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
E/AndroidRuntime(30239): 	at android.os.BaseBundle.getString(BaseBundle.java:918)
E/AndroidRuntime(30239): 	at android.content.Intent.getStringExtra(Intent.java:5060)
E/AndroidRuntime(30239): 	at com.sina.weibo.sdk.share.WbShareToStoryActivity.onCreate(SourceFile:41)
E/AndroidRuntime(30239): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime(30239): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(30239): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)

**Comment by MerlinYu** [comment]
It's so strange ,I also meet but I didn't create this class
