### ISSUE TITLE
so文件找不到，libs下面也加了没用啊

### ISSUE THREAD

**Issue by melody1993** [sinaweibosdk/weibo_android_sdk#321]
dlopen failed: library "/system/lib64/libweibosdkcore.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace

**Comment by wudkj** [comment]
我也遇到了这个问题,官方没有任何回复,我的解决方法是:
在main目录下新建jniLibs(有就不要建了)
然后将下载的weibo github 包解压后得到的so目录下的所有文件夹和文件都复制进去

**Comment by Aheadboy** [comment]
![image](https://user-images.githubusercontent.com/8358046/49210662-a4f8ae00-f3f8-11e8-9791-ad3b26788c7f.png)


![image](https://user-images.githubusercontent.com/8358046/49210676-acb85280-f3f8-11e8-8baa-ea2212bb07bd.png)
官网！
