### ISSUE TITLE
微博分享so文件在三星手机上报错

### ISSUE THREAD

**Issue by Asmewill** [sinaweibosdk/weibo_android_sdk#323]
/data/app/com.google.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit

**Comment by WanghongLin** [comment]
现在普遍都是64位 arm 的机器，微博Android sdk的最新版本的aar `core-4.1.3-openDefaultRelease.aar` 竟然里面还是没有 `arm64-v8a` 的目录。

然后却在aar里面包含了 x86 这种非常少人用的架构。

这么大一个公司，就这么维护sdk的？

还是这个sdk是一群不懂技术人的在维护的？
