### ISSUE TITLE
4.1版本分享crash的问题

### ISSUE THREAD

**Issue by eaggle** [sinaweibosdk/weibo_android_sdk#325]
09-21 11:46:14.281 28547-28547/com.tencent.weishi E/crashimpl.onCrashSaving,: arg0:false,arg1:java.lang.NullPointerException:Attempt to invoke virtual method 'void android.os.Handler.removeMessages(int)' on a null object reference,arg2:com.sina.weibo.sdk.share.WbShareTransActivity.onNewIntent(WbShareTransActivity.java:191),arg3:com.sina.weibo.sdk.share.WbShareTransActivity.onNewIntent(WbShareTransActivity.java:191)
                                                                              android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1308)
                                                                              android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1320)
                                                                              android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2968)
                                                                              android.app.ActivityThread.performNewIntents(ActivityThread.java:2983)
                                                                              android.app.ActivityThread.handleNewIntent(ActivityThread.java:2999)
                                                                              android.app.ActivityThread.-wrap14(Unknown Source:0)
                                                                              android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
                                                                              android.os.Handler.dispatchMessage(Handler.java:105)
                                                                              android.os.Looper.loop(Looper.java:164)
                                                                              android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                              java.lang.reflect.Method.invoke(Native Method)
                                                                              com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                              com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                              ,arg4-10000,arg5:1505965573991

**Comment by eaggle** [comment]
the same

**Comment by fanjihuan** [comment]
4.1.5版本，出现相同问题

**Comment by eaggle** [comment]
知道原因了。之前版本的xml里头多声明了
<intent-filter>
                <action android:name="com.sina.weibo.sdk.action.ACTION_SDK_REQ_ACTIVITY" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
删掉就ok了
