### ISSUE TITLE
视频没法分享

### ISSUE THREAD

**Issue by glorinli** [sinaweibosdk/weibo_android_sdk#339]
12-04 11:23:09.563 28668-28668/? W/System.err: java.lang.NoSuchFieldException: No field mAppContextImpl in class Landroid/hardware/SystemSensorManager; (declaration of 'android.hardware.SystemSensorManager' appears in /system/framework/framework.jar)
12-04 11:23:09.564 28668-28668/? W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
12-04 11:23:09.564 28668-28668/? W/System.err:     at com.sina.weibo.panorama.utils.ManufacturerCompact.detachActivityFromSensorManager(ManufacturerCompact.java:25)
12-04 11:23:09.564 28668-28668/? W/System.err:     at com.sina.weibo.panorama.a.onCreate(ControllerFragment.java:30)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.Fragment.performCreate(Fragment.java:2335)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2036)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.FragmentController.dispatchCreate(FragmentController.java:165)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.Activity.onCreate(Activity.java:1004)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.support.v4.app.BaseFragmentActivityDonut.onCreate(BaseFragmentActivityDonut.java:39)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:278)
12-04 11:23:09.564 28668-28668/? W/System.err:     at com.sina.weibo.ScreenOrientationBaseActivity.onCreate(ScreenOrientationBaseActivity.java:119)
12-04 11:23:09.564 28668-28668/? W/System.err:     at com.sina.weibo.BaseActivity.onCreate(BaseActivity.java:256)
12-04 11:23:09.564 28668-28668/? W/System.err:     at com.sina.weibo.composerinde.BaseComposerActivity.onCreate(BaseComposerActivity.java:37)
12-04 11:23:09.564 28668-28668/? W/System.err:     at com.sina.weibo.composerinde.WeiboBaseComposerActivity.onCreate(WeiboBaseComposerActivity.java:176)
12-04 11:23:09.564 28668-28668/? W/System.err:     at com.sina.weibo.composerinde.OriginalComposerActivity.onCreate(OriginalComposerActivity.java:202)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.Activity.performCreate(Activity.java:6847)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
12-04 11:23:09.564 28668-28668/? W/System.err:     at com.sina.weibo.bundlemanager.b.a.callActivityOnCreate(InstrumentationHook.java:233)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-04 11:23:09.564 28668-28668/? W/System.err:     at android.os.Looper.loop(Looper.java:163)
12-04 11:23:09.565 28668-28668/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6337)
12-04 11:23:09.565 28668-28668/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-04 11:23:09.565 28668-28668/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
12-04 11:23:09.565 28668-28668/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by jeepc** [comment]
老哥看看这个能不能解决：https://github.com/sinaweibosdk/weibo_android_sdk/issues/383
