### ISSUE TITLE
微博SDK4.1.5版本的WeiboSdkWebActivity对象存在intent攻击漏洞，麻烦确认下

### ISSUE THREAD

**Issue by Tiger3590** [sinaweibosdk/weibo_android_sdk#346]
微博SDK4.1.5版本的WeiboSdkWebActivity对象存在intent攻击漏洞，麻烦确认下
测试命令：adb shell am start-activity xxxxx/com.sina.weibo.sdk.web.WeiboSdkWebActivity
xxxx替换为集成了sdk的apk包名即可

**Comment by yangzhiqian** [comment]
这个问题最后解决了吗？

**Comment by ddddyyy** [comment]
测试命令 未成功啊
