### ISSUE TITLE
分享回调成功，但是微博客户端却进入草稿箱，提示错误码 8995

### ISSUE THREAD

**Issue by victorygao** [sinaweibosdk/weibo_android_sdk#347]
如题，Android平台微博分享，app收到api回调，表示分享成功，但是打开微博客户端app，该分享进入草稿箱，并提示 :  (8995)app auth fail for appKey&sign&package，请问是什么问题？

**Comment by lofty14** [comment]
哈喽，哥们，这个问题解决了吗，我的也是这个问题，签名比对几次了，没问题，肯定不是签名的问题

**Comment by keshuangjie** [comment]
同样约到这个问题，找不到解决方案

**Comment by keshuangjie** [comment]
找到原因了 appkey放在meta-data中获取的时候因为长数字问题转换成String出问题了@lofty14 你可以debug检查下会不会也是这个原因导致的

**Comment by 852172891** [comment]
appkey放在meta-data ，可能会转化为科学计数法，可以加 ‘ \ ’ 处理一下。但是还是 报签名错误。

**Comment by 852172891** [comment]
找到原因了，微博开放平台：填写 Android包名多了个空格。8995 错误提示， app auth fail for appKey&sign&package 。检查这三个参数可以了，保证微博开放平台和客户端填写的一致。
