### ISSUE TITLE
你们文档可以同步一下吗？感觉太混乱了

### ISSUE THREAD

**Issue by zcweng** [sinaweibosdk/weibo_android_sdk#360]
你们文档可以同步一下吗？感觉太混乱了，不要误导我们这些开发者好么

**Comment by zcweng** [comment]
https://github.com/sinaweibosdk/weibo_android_sdk/blob/master/%E6%96%B0%E6%96%87%E6%A1%A3/%E5%BE%AE%E5%8D%9ASDK%204.0%E6%96%87%E6%A1%A3.pdf  居然是404啊

**Comment by zcweng** [comment]
4.1的文档，里面写的aar版本却是2.0.3

**Comment by droidwolf** [comment]
文档写的屎一样

**Comment by titanseason** [comment]
发布aar的方式，也跟屎一样。
要是每个第三方SDK都把发布的内容放到特殊的maven仓库下面，一个app要写一堆的 `maven { url "" }`
