### ISSUE TITLE
!!! 微博分享取消大概率出现异常:取消微博分享返回后,有透明Activity未关闭,导致APP界面无法点击日志如下: 

### ISSUE THREAD

**Issue by yandeqing** [sinaweibosdk/weibo_android_sdk#362]
04-20 10:53:08.745 W/Bundle  ( 5132): Key android.intent.extra.STREAM expected ArrayList but value was a android.net.Uri$StringUri.  The default value <null> was returned.
04-20 10:53:08.746 W/Bundle  ( 5132): Attempt to cast generated internal exception:
04-20 10:53:08.746 W/Bundle  ( 5132): java.lang.ClassCastException: android.net.Uri$StringUri cannot be cast to java.util.ArrayList
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.os.Bundle.getParcelableArrayList(Bundle.java:916)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.content.Intent.getParcelableArrayListExtra(Intent.java:6354)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.composerinde.element.PicElement.a(PicElement.java:300)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.composerinde.manager.e.a(ComposerManager.java:367)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.composerinde.manager.BaseWeiboComposerManager.a(BaseWeiboComposerManager.java:110)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.composerinde.OriginalComposerActivity.c(OriginalComposerActivity.java:1186)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.composerinde.OriginalComposerActivity.a(OriginalComposerActivity.java:1136)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.sdk.internal.b.a(SdkController.java:376)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.composerinde.WeiboBaseComposerActivity.onInitActivity(WeiboBaseComposerActivity.java:287)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.composerinde.OriginalComposerActivity.onInitActivity(OriginalComposerActivity.java:856)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.BaseActivity.doInit(BaseActivity.java:674)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.BaseActivity.doCheckLogin(BaseActivity.java:442)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.composerinde.BaseComposerActivity.onCreate(BaseComposerActivity.java:41)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.composerinde.WeiboBaseComposerActivity.onCreate(WeiboBaseComposerActivity.java:184)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.composerinde.OriginalComposerActivity.onCreate(OriginalComposerActivity.java:250)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.app.Activity.performCreate(Activity.java:6873)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.sina.weibo.bundlemanager.b.a.callActivityOnCreate(InstrumentationHook.java:225)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2713)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2821)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.os.Looper.loop(Looper.java:181)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at android.app.ActivityThread.main(ActivityThread.java:6294)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at java.lang.reflect.Method.invoke(Native Method)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
04-20 10:53:08.746 W/Bundle  ( 5132): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

**Comment by chinapumpkin** [comment]
我在微博网页版分享的时候遇到了和你一样的问题。sdk版本为4.2.7.原因是WeiboSdkWebActivity关闭的时候通过ShareWebViewClient回调，其中的sendSdkResponse 方法，通过隐式intent 发送，com.sina.weibo.sdk.action.ACTION_SDK_REQ_ACTIVITY。 这个方法在AndroidManifest 中注册，会调用WbShareTransActivity。因为我们使用了插件框架，没有在launcher的manifest 中注册导致无法调用WbShareTransActivity。 这种情况只有一步步跟踪，查看callback为什么没有回调，才能找到原因

**Comment by yuan7016** [comment]
the same problem.how to fix it?
