### ISSUE TITLE
使用AndroidWebView:65.0.3325.109登录微博账号后账号崩溃FATAL:jni_android.cc(232)，必现。SDK版本是4.2.7

### ISSUE THREAD

**Issue by shenguojun** [sinaweibosdk/weibo_android_sdk#363]
--------- beginning of crash
04-23 14:50:31.435 25300-25025/? A/google-breakpad: -----BEGIN BREAKPAD MICRODUMP-----
    V AndroidWebView:65.0.3325.109
04-23 14:50:31.436 25300-25025/? A/google-breakpad: O A arm 04 armv8l OnePlus/OnePlus3/OnePlus3:8.0.0/OPR1.170623.032/04101010:user/release-keys
    P browser
    R 00000006 SIGABRT 000061C1
    G 
04-23 14:50:31.438 25300-25025/? A/google-breakpad: H 12C00000 FFFF1000 005D 349BC000 74F70000 0C:14 0D:10 0E:0D 0F:06 10:08 11:05 12:07 13:02 14:02 15:03 16:06 1A:01 1B:01 1C:02 1D:01
04-23 14:50:31.439 25300-25025/? A/google-breakpad: S 0 FF9B6D28 FF9B6000 00005000

    -----END BREAKPAD MICRODUMP-----
04-23 14:50:32.372 9150-9217/? E/qti_sensors_hal: processInd: pickup data: state: 0.000000 flag: 2.000000 SAM TS: 3495311847 HAL TS:237737023116630 elapsedRealtimeNano:237737061585281

04-23 14:50:33.719 25025-25025/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 25025 (udao.reciteword)
04-23 14:50:33.845 25312-25312/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'OnePlus/OnePlus3/OnePlus3:8.0.0/OPR1.170623.032/04101010:user/release-keys'
    Revision: '0'
    ABI: 'arm'
    pid: 25025, tid: 25025, name: udao.reciteword  >>> com.youdao.reciteword <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-23 14:50:33.849 25312-25312/? A/DEBUG: Abort message: '[FATAL:jni_android.cc(232)] Please include Java exception stack in crash report
    '
        r0 00000000  r1 000061c1  r2 00000006  r3 00000008
        r4 000061c1  r5 000061c1  r6 ff9b6d38  r7 0000010c
        r8 ff9b6d75  r9 ff9b6d74  sl ff9b71cc  fp ff9b71d0
        ip 00000000  sp ff9b6d28  lr f43de9a7  pc f440f10c  cpsr 200d0010
04-23 14:50:33.851 25312-25312/? A/DEBUG: backtrace:
        #00 pc 0004b10c  /system/lib/libc.so (tgkill+12)
        #01 pc 0001a9a3  /system/lib/libc.so (abort+54)

**Comment by LKDont** [comment]
我也遇到这个问题，解决办法有点粗暴：
1、解压openDefault-4.2.7.aar
2、反编译classes.jar，得到java源代码
3、在Android Studio中新建一个module，将java代码、assets、jni、res、AndroidManifest.xml这些文件复制到module中
4、在WeiboSdkWebActivity中添加代码：
```
    @Override
    protected void onDestroy() {
        try {
            ((ViewGroup) webView.getParent()).removeView(webView);
            webView.destroy();
            webView = null;
        } catch (Exception e) {
            e.printStackTrace();
        }
        super.onDestroy();
    }
```

参考：https://stackoverflow.com/questions/31416568/could-someone-help-me-with-this-crash-report
