### ISSUE TITLE
关于WbShareCallback的问题

### ISSUE THREAD

**Issue by sonicdjgh** [sinaweibosdk/weibo_android_sdk#367]
之前老版的|SDK中，必须让Activity继承IWeiboHandler.Response类，才能正常响应分享回调。如果另外单独定义一个IWeiboHandler.Response类来使用，就没法响应回调。这个样做法，虽然节省了开发，但是对于集成来说，在不需要使用微博分享的情况下，还必须要引入微博的jar包。

不知道新版SDK中的WbShareCallback是不是也是同样的设计？请问能否优化这部分代码，使之可以单独定义WbShareCallback类然后使用？

**Comment by tianzhijiexian** [comment]
它并不是强迫activity实现这个接口的啊，你可以定义内部类实现这个接口并传入的，和activity没有关系。
