### ISSUE TITLE
文档地址404

### ISSUE THREAD

**Issue by DespairK** [sinaweibosdk/weibo_android_sdk#368]
文档地址404什么鬼？
https://github.com/sinaweibosdk/weibo_android_sdk/blob/master/%E6%96%B0%E6%96%87%E6%A1%A3/%E5%BE%AE%E5%8D%9ASDK%204.0%E6%96%87%E6%A1%A3.pdf

**Comment by wangyeming** [comment]
新浪微博最重要的分享SDK做的就是一坨屎

**Comment by tianzhijiexian** [comment]
这么简单的问题都没有人修复，真的是对微博太失望了
