### ISSUE TITLE
intent攻击下报空指针异常

### ISSUE THREAD

**Issue by parallelyk** [sinaweibosdk/weibo_android_sdk#376]
麻烦尽快修复该问题，WeiboSdkWebActivity下加入对bundle的判空
private void initLoad() {
        Bundle bundle = this.getIntent().getExtras();
        int type = bundle.getInt("type", -1);
        ...
}

[activity]com.huawei.appmarket/com.sina.weibo.sdk.web.WeiboSdkWebActivity
06-05 18:35:28.555 E/AndroidRuntime(23123): FATAL EXCEPTION: main
06-05 18:35:28.555 E/AndroidRuntime(23123): Process: com.huawei.appmarket, PID: 23123
06-05 18:35:28.555 E/AndroidRuntime(23123): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.huawei.appmarket/com.sina.weibo.sdk.web.WeiboSdkWebActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.BaseBundle.getInt(java.lang.String, int)' on a null object reference
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at android.os.Handler.dispatchMessage(Handler.java:105)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at android.os.Looper.loop(Looper.java:199)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at android.app.ActivityThread.main(ActivityThread.java:6524)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at java.lang.reflect.Method.invoke(Native Method)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
06-05 18:35:28.555 E/AndroidRuntime(23123): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.BaseBundle.getInt(java.lang.String, int)' on a null object reference
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at com.sina.weibo.sdk.web.WeiboSdkWebActivity.initLoad(:99)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at com.sina.weibo.sdk.web.WeiboSdkWebActivity.onCreate(:90)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at android.app.Activity.performCreate(Activity.java:6910)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
06-05 18:35:28.555 E/AndroidRuntime(23123): 	... 10 more
[#####] E/AndroidRuntime : More Details See : [dropbox] /data/system/dropbox/system_app_crash@1528194928573.txt
[*****] E/AndroidRuntime : We have deteced an AndroidRuntime Exception.

**Comment by richzjc** [comment]
how to solve this issue? can you tell me
