### ISSUE TITLE
关于AidTask和AidTask4Plug的IMEI获取

### ISSUE THREAD

**Issue by kevinqzj** [sinaweibosdk/weibo_android_sdk#377]
AidTask和AidTask4Plug有TelephonyManager.getDeviceId()的调用，
现在Google对IMEI获取和上报监管比较严，可能会导致在Google Play上面的应用被下架。而其实Android 6.0以后如果应用没动态请求权限的话，这里也获取不到IMEI，请问是否可以移除掉getDeviceId？

**Comment by xu-duqing** [comment]
当前不仅仅 Google , 国内的监管也非常严格. 针对三方获取 IMEI 都要求下架, 这个问题改如何解决 @sinaweibosdk
