### ISSUE TITLE
Android 5.0平台上出现Service Intent must be explicit

### ISSUE THREAD

**Issue by gunner4life** [sinaweibosdk/weibo_android_sdk#38]
Android5.0之后，Service Intent必须是显式的声明(explicit)，而新浪微博的authorize方法中调用方式是implicit的，所以会直接导致Crash。麻烦你们尽快解决这问题并更新sdk，否则在5.0平台上无法使用，谢谢！
![2014-11-12 3 32 58](https://cloud.githubusercontent.com/assets/2338218/5006685/77df6d5a-6a81-11e4-8ed4-b557610ce17e.png)

**Comment by nos19880918** [comment]
同样遇到这个问题，怎么解决？

**Comment by yangpeiyong** [comment]
这个问题官方sdk怎么还没有解决呢？
