### ISSUE TITLE
SDK分享图片就会{"error":"auth by Null spi!","error_code":21301,"request":"/2/statuses/share.json"}

### ISSUE THREAD

**Issue by DespairK** [sinaweibosdk/weibo_android_sdk#381]
使用/share.json接口分享带上图片就会出现21301的bug，不加图片就完全没问题，能给看一下到底是什么情况吗？
加你们的群没反应，联系开发人员也没人回答，这个sdk难道被放弃了？

**Comment by dingquantracy** [comment]
> 使用/share.json接口分享带上图片就会出现21301的bug，不加图片就完全没问题，能给看一下到底是什么情况吗？
> 加你们的群没反应，联系开发人员也没人回答，这个sdk难道被放弃了？

同样的问题，求解答

**Comment by dingquantracy** [comment]
> 使用/share.json接口分享带上图片就会出现21301的bug，不加图片就完全没问题，能给看一下到底是什么情况吗？
> 加你们的群没反应，联系开发人员也没人回答，这个sdk难道被放弃了？

解决了。仅供参考，我是参考了php sdk中的实现

`export const share = async (access_token, data) => {
  const params = {
    access_token,
    status: data.content
  }

  let formData = new FormData()
  for (let name in params) {
    formData.append(name, params[name])
  }
  **formData.append('pic', data.pic, {
    filename: 'share.jpg',
    contentType: 'image/unknown'
  })**

  const res = await nodeFetch('https://api.weibo.com/2/statuses/share.json', {
    method: 'POST',
    body: formData
  }).then(res => res.json())

  return Response.json({ id: res.idstr })
}`

**Comment by imwangji** [comment]
@dingquantracy  看起来PHP SDK中的操作和我的也没什么区别啊，可是我的就不行。
