### ISSUE TITLE
无法分享视频

### ISSUE THREAD

**Issue by zachaxy** [sinaweibosdk/weibo_android_sdk#383]
使用的是 demo 中提供的代码，没有做改动，点击视频分享，一直分享失败

**Comment by zachaxy** [comment]
api >= 23
读写权限除了要在 manifest 文件中声明，还要动态的申请权限，否则分享失败，
demo 中没有做相应处理

**Comment by jeepc** [comment]
补充：不管是图片、多图、视频都必须带上文本，也就是：
weiboMultiMessage.textObject = getTextObj(shareContent.getSummary());

**Comment by umiiwa** [comment]
> 补充：不管是图片、多图、视频都必须带上文本，也就是：
> weiboMultiMessage.textObject = getTextObj(shareContent.getSummary());

你好，能麻烦说得详细一点吗？怎们动态申请权限，以及你说的这一句加在哪里呢？不知道shareContent对应什么
