### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.netease.mint/com.sina.weibo.sdk.component.WeiboSdkBrowser}

### ISSUE THREAD

**Issue by maoqis** [sinaweibosdk/weibo_android_sdk#386]
版本3.1.4

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.netease.mint/com.sina.weibo.sdk.component.WeiboSdkBrowser}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.os.Bundle.getSerializable(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

源码相关：
WeiboSdkBrowser createBrowserRequestParam 中 data获取key为key_launcher 的value 未做非空判断。

private BrowserRequestParamBase createBrowserRequestParam(Bundle data) {
        this.isFromGame = false;
        BrowserRequestParamBase result = null;
        BrowserLauncher launcher = (BrowserLauncher)data.getSerializable("key_launcher");
        if (launcher == BrowserLauncher.AUTH) {
            AuthRequestParam authRequestParam = new AuthRequestParam(this);
            authRequestParam.setupRequestParam(data);
            this.installAuthWeiboWebViewClient(authRequestParam);
            return authRequestParam;
        } else {
            if (launcher == BrowserLauncher.SHARE) {
                ShareRequestParam shareRequestParam = new ShareRequestParam(this);
                shareRequestParam.setupRequestParam(data);
                this.installShareWeiboWebViewClient(shareRequestParam);
                result = shareRequestParam;
            } else if (launcher == BrowserLauncher.WIDGET) {
                WidgetRequestParam widgetRequestParam = new WidgetRequestParam(this);
                widgetRequestParam.setupRequestParam(data);
                this.installWidgetWeiboWebViewClient(widgetRequestParam);
                result = widgetRequestParam;
            } else if (launcher == BrowserLauncher.GAME) {
                this.isFromGame = true;
                GameRequestParam gameRequestParam = new GameRequestParam(this);
                gameRequestParam.setupRequestParam(data);
                this.installWeiboWebGameClient(gameRequestParam);
                result = gameRequestParam;
            }

            return (BrowserRequestParamBase)result;
        }
    }

**Comment by gewasirio** [comment]
也有这个问题，怎么解的，升级就没事了吗
