### ISSUE TITLE
WbShareTransActivity存在拉起客户端任意私有组件的问题

### ISSUE THREAD

**Issue by andywangfly** [sinaweibosdk/weibo_android_sdk#387]
###  问题现象
我们的客户端集成Weibo SDK（版本是0041005000）实现分享到微博的功能，经过安全测试发现，第三方恶意应用可以通过传入intent给客户端的Weibo SDK中的WbShareTransActivity，拉起客户端的任意非暴露组件。

###  问题原因
我们的客户端没有用到WbShareTransActivity，但是 SDK中的AndroidMainfest.xml文件将WbShareTransActivity设置为暴露组件（隐式），无权限控制。这样第三方应用可以直接访问。
 
![image](https://user-images.githubusercontent.com/26439958/44845473-36cd0f80-ac80-11e8-9e65-9d1ae4306836.png)

###  攻击过程
![image](https://user-images.githubusercontent.com/26439958/44845558-7136ac80-ac80-11e8-8c43-6055f6d7133d.png)

###  问题引入点
在WbShareTransActivity的gotoWeiboComposer方法中，从inent中获取到要拉起的activity的package、action、activity，通过startActivity拉起。而WbShareTransActivity是暴露组件，intent是外界可控传入的，导致可以拉起任意非暴露组件。

请尽快修复，感谢 :-)

**Comment by sinaweibosdk** [comment]
这里是有限制的，只能拉起某个Activity，否则会报错。
