### ISSUE TITLE
4.3.0 去掉了armeabi-v7a？

### ISSUE THREAD

**Issue by coolegos** [sinaweibosdk/weibo_android_sdk#389]
如题，还增加了一个`libutility.so`

**Comment by liulinjie1990823** [comment]
4.1.4还是有三种架构的，4.3.0就只有armeabi了
![image](https://user-images.githubusercontent.com/8141393/48767842-96244400-ecf2-11e8-9c7c-ea3233dde3de.png)

大哥们走点心，去加上

**Comment by kgbky** [comment]
@coolegos libutility这个so库要去哪里下载

**Comment by coolegos** [comment]
@kgbky 使用新版本
