### ISSUE TITLE
4.3.0SDK，分享后接收不到回调消息

### ISSUE THREAD

**Issue by weixueandroid** [sinaweibosdk/weibo_android_sdk#390]
4.3.0AAR版本的SDK，实现了WbShareCallback的接口，但是接收不到回调消息是什么原因，相关设置按照demo上来的

**Comment by wwwjiandan** [comment]
I have same problem too

**Comment by weixueandroid** [comment]
> I have same problem too
解决方法：https://blog.csdn.net/weixue9/article/details/82668740

**Comment by centerzx** [comment]
真心蛋疼！！！！！！！无回调！！！！！！新浪的大佬们，加油呀！

**Comment by sinaweibosdk** [comment]
/*    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        shareHandler.doResultIntent(intent,this);
    }*/

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        shareHandler.doResultIntent(data,this);
    }

**Comment by weixueandroid** [comment]
> /* @override
> protected void onNewIntent(Intent intent) {
> super.onNewIntent(intent);
> shareHandler.doResultIntent(intent,this);
> }*/
> 
> ```
> @Override
> protected void onActivityResult(int requestCode, int resultCode, Intent data) {
>     super.onActivityResult(requestCode, resultCode, data);
>     shareHandler.doResultIntent(data,this);
> }
> ```
这个返回的data数据为null

**Comment by soul-ferry** [comment]
我使用RxJava时在onSuccess中调用wbShareHandler?.shareMessage()不会执行当前Activity的onActivityResult方法，但是不使用RxJava直接分享时可以。大佬能不能解答一下

**Comment by weixueandroid** [comment]
> 我使用RxJava时在onSuccess中调用wbShareHandler?.shareMessage()不会执行当前Activity的onActivityResult方法，但是不使用RxJava直接分享时可以。大佬能不能解答一下

这个不清楚

**Comment by hamberluo** [comment]
> @wwwjiandan
> 解决方法：https://blog.csdn.net/weixue9/article/details/82668740

这个不能算解决方法，属于规避方法，新浪微博在 4.3.0 的版本里面应该是去掉了回调逻辑，跟微信去掉分享成功的回调一样，不清楚是否和政策有关，现阶段还是不要依赖回调，自己手动触发结果返回比较好。

**Comment by FrancisShi** [comment]
> /* @override
> protected void onNewIntent(Intent intent) {
> super.onNewIntent(intent);
> shareHandler.doResultIntent(intent,this);
> }*/
> 
> ```
> @Override
> protected void onActivityResult(int requestCode, int resultCode, Intent data) {
>     super.onActivityResult(requestCode, resultCode, data);
>     shareHandler.doResultIntent(data,this);
> }
> ```

宁愿回答issue 就是不更新文档 👍
