### ISSUE TITLE
微博极速版无法正常授权登陆

### ISSUE THREAD

**Issue by Dragonwrath** [sinaweibosdk/weibo_android_sdk#396]
微博普通版正常授权
微博网页版正常授权
极速版登陆，在授权页出现网络错误，请点击按钮重试，点击无提示
点击确定按钮，提示21301，invalid accessToken
极速版版本 1.4.5
已测试手机HUAWEI 荣耀7 Api23
魅族 Note6 Api25
ps:官方DEMO也是同样的提示

**Comment by addappcn** [comment]
又他妈的关闭
