### ISSUE TITLE
Demo 中 WeiboPageUtils 找不到？

### ISSUE THREAD

**Issue by jackyglony** [sinaweibosdk/weibo_android_sdk#403]
Demo 中 WeiboPageUtils 找不到？

**Comment by ZhangMingHua001** [comment]
这demo小学生写的吧

**Comment by ZhangMingHua001** [comment]
给个编译不过的demo，6的飞起

**Comment by xyz-fly** [comment]
版本编译版本还旧的要死，lib还有历史引用，感觉就是用文本编辑器改了下gradle，行吧，这些我都忍了，编译不过真的服服的，还找不到替换的类是哪个，没见过哪个维护开源版本维护成这样的，这也算是长见识 了，比烂服你们大厂的

**Comment by docwei2050** [comment]
到现在还是找不到

**Comment by weifans** [comment]
哈哈哈、依然找不到

**Comment by MrTaohf** [comment]
这个啥时候解决一下啊

**Comment by GoombaCN** [comment]
洛阳铲 现在还是找不到 手动滑稽
