### ISSUE TITLE
新浪微博起调私有组件

### ISSUE THREAD

**Issue by pokerfacett** [sinaweibosdk/weibo_android_sdk#406]
com.sina.weibo.sdk.share.WbShareTransActivity，该组件对外导出，并接受任意参数，起调私有组件，影响众多app，请紧急修复，防止pr风险。。。。sina-sso-4.2.7

**Comment by ruicbAndroid** [comment]
> > com.sina.weibo.sdk.share.WbShareTransActivity，该组件对外导出，并接受任意参数，起调私有组件，影响众多app，请紧急修复，防止pr风险。。。。sina-sso-4.2.7
> 
> 请使用4.3.6

你好，使用 4.3.6+ 版本，依然存在该问题，能通过以下代码依然能呼起 WbShareTransActivity：

`
Intent intent = new Intent();
intent.setComponent(new ComponentName("com.test.weibodemo", "com.sina.weibo.sdk.share.WbShareTransActivity"));
intent.putExtra(“random_serializable_extra", new SerializableObject());
startActivity(intent);
`
区别于之前报错`weibo sdk was not initall!....`，新版本能唤起且解析出错`Parcelable encountered ClassNotFoundException reading a Serializable object`

是我使用问题？还是SDK存在缺陷？麻烦处理下，多谢。
