### ISSUE TITLE
使用网页分享时http://service.weibo.com/share/mobilesdk_uppic.php返回了{     "code": 0,     "data": "" }。upload pic faild

### ISSUE THREAD

**Issue by soul-ferry** [sinaweibosdk/weibo_android_sdk#408]

**Comment by soul-ferry** [comment]
readme中提供的demo APK也是同样的问题。

**Comment by soul-ferry** [comment]
@sinaweibosdk 你好，可以看一下这个问题吗，谢谢

**Comment by 270350674** [comment]
我们也有这样的问题，请问您解决了吗

**Comment by chinapumpkin** [comment]
我也遇到了同样的问题，请问最后解决了吗？

**Comment by soul-ferry** [comment]
> 我们也有这样的问题，请问您解决了吗
没解决，准备去掉这个功能

**Comment by aishang5wpj** [comment]
> > 我们也有这样的问题，请问您解决了吗
> > 没解决，准备去掉这个功能

调用下面的代码把图片信息去掉即可，这样在web页面就分享不了图片，但是分享文字还是可以的

`
 if (!WbSdk.isWbInstall(activity)) {
            message.imageObject = null;
 }
`

**Comment by mdyoyo** [comment]
@sinaweibosdk 麻烦看下这个问题，用4.3.6还是没有解决呢
