### ISSUE TITLE
4.3版本后，横屏模式，会多次弹出分享页面

### ISSUE THREAD

**Issue by tobeanyway** [sinaweibosdk/weibo_android_sdk#409]
感觉横竖屏切换时，分享页面存在2次调用，可能生命周期哪里控制有问题

**Comment by aishang5wpj** [comment]
我也碰到这个问题了

**Comment by shuzhili** [comment]
> 
> 
> 感觉横竖屏切换时，分享页面存在2次调用，可能生命周期哪里控制有问题

您好这个问题你们解决了么

**Comment by aishang5wpj** [comment]
@sinaweibosdk  不解决就关闭？？？？
