### ISSUE TITLE
App多进程，从非主进程分享，不能拉起微博

### ISSUE THREAD

**Issue by killerJava** [sinaweibosdk/weibo_android_sdk#414]
必现，比如从web进程拉起微博分享，结果不能弹出新浪微博的分享界面

**Comment by aishang5wpj** [comment]
微博校验sdk是否初始化是在主进程的，如果发起分享在子进程，初始化也在子进程，那分享不了，太坑了

**Comment by aishang5wpj** [comment]
@sinaweibosdk  不解决不回复就关闭？？？
