### ISSUE TITLE
4.3.6 so库没有 armeabi-v7a 和 x86 与文档描述不符

### ISSUE THREAD

**Issue by NemoHzy** [sinaweibosdk/weibo_android_sdk#415]
尤其前一个，对现在打包影响很大，希望尽快处理一下

**Comment by gaobq** [comment]
从 4.3.4版本开始就这样了 我也和你遇到一样问题
导致部分机型报了/lib/arm/libweibosdkcore.so" is 64-bit instead of 32-bit

建议你用4.3.4的版本
