### ISSUE TITLE
BUGLY上报空指针和加载SO失败

### ISSUE THREAD

**Issue by Mozziehh** [sinaweibosdk/weibo_android_sdk#421]
#18393564 java.lang.UnsatisfiedLinkError
Couldn't load weibosdkcore from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wuba-1.apk", zip file "/data/data/com.wuba/code_cache/secondary-dexes/com.wuba-1.apk.classes2.zip", zip file "/data/data/com.wuba/code_cache/secondary-dexes/com.wuba-1.apk.classes3.zip", zip file "/data/data/com.wuba/code_cache/secondary-dexes/com.wuba-1.apk.classes4.zip", zip file "/data/data/com.wuba/code_cache/secondary-dexes/com.wuba-1.apk.classes5.zip", zip file "/data/data/com.wuba/code_cache/seco

com.sina.weibo.sdk.net.HttpManager.void <clinit>()(HttpManager.java:42)

设备：小米 HM NOTE 1W  
版本号 ：4.2.7.4

**Comment by Mozziehh** [comment]
# Thread-8(548)

java.lang.NullPointerException

Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference

解析原始

com.sina.weibo.sdk.net.HttpManager.java.lang.String readConnectResponse(java.net.HttpURLConnection,boolean)(HttpManager.java:141)
--
2 com.sina.weibo.sdk.net.HttpManager.java.lang.String requestHttpExecute(android.content.Context,java.lang.String,java.lang.String,com.sina.weibo.sdk.net.WeiboParameters)(HttpManager.java:104)
3 com.sina.weibo.sdk.net.HttpManager.java.lang.String openUrl(android.content.Context,java.lang.String,java.lang.String,com.sina.weibo.sdk.net.WeiboParameters)(HttpManager.java:62)
4 com.sina.weibo.sdk.utils.AidTask.java.lang.String loadAidFromNet()(AidTask.java:403)
5 com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)
6 com.sina.weibo.sdk.utils.AidTask$2.void run()(AidTask.java:235)
7 java.lang.Thread.run(Thread.java:764)

版本号 ：4.2.7.4

**Comment by colin-phang** [comment]
我们应用也有类似问题：
## **java.lang.UnsatisfiedLinkError

dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxxx.xxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxxx.xxx/lib/arm, /data/app/com.xxxx.xxx-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libweibosdkcore.so"**

1 java.lang.Runtime.loadLibrary0(Runtime.java:984)
--
2 java.lang.System.loadLibrary(System.java:1530)
3 com.sina.weibo.sdk.net.HttpManager.<clinit>(SourceFile:42)
4 com.sina.weibo.sdk.net.HttpManager.openUrl(SourceFile:62)
5 com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(SourceFile:403)
6 com.sina.weibo.sdk.utils.AidTask.access$200(SourceFile:49)
7 com.sina.weibo.sdk.utils.AidTask$2.run(SourceFile:235)
8 java.lang.Thread.run(Thread.java:761)
