### ISSUE TITLE
关于默认so类型的支持问题

### ISSUE THREAD

**Issue by sonicdjgh** [sinaweibosdk/weibo_android_sdk#430]
尊敬的开发者：

     你好，希望SDK能够默认支持全部的so类型，如果有特殊需求，我自己再加过滤，你这样默认只有三种，别家sdk都是默认全部类型，我觉得好烦。。。

**Comment by leanjiang** [comment]
同觉得烦！！

**Comment by chungpinglau** [comment]
是的，麻烦

**Comment by bewareofbears** [comment]
没人维护了.连 so 编译 多扩展几个平台都不愿意.
没救了

**Comment by CYPChenYanPIng** [comment]
> 尊敬的开发者：
> 
> ```
>  你好，希望SDK能够默认支持全部的so类型，如果有特殊需求，我自己再加过滤，你这样默认只有三种，别家sdk都是默认全部类型，我觉得好烦。。。
> ```

你是怎么解决的这个问题，我遇到一个错误java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", couldn't find "libwind.so"
就是在执行WbSdk.install(appContext, info);方法报错
