### ISSUE TITLE
微博通过WebView的形式授权登录时，直接进入了redirectURI，而不是登陆界面

### ISSUE THREAD

**Issue by leanjiang** [sinaweibosdk/weibo_android_sdk#432]
我们线上一部分用户反馈，微博未安装客户端时，通过WebView登陆，直接进入了我们填的redirectURL，而不是登陆界面
sdk版本 4.1.0
![image](https://user-images.githubusercontent.com/3284486/50879488-0e1b0a80-1416-11e9-8783-972ae39900bb.png)

大部分手机都能通过WebView正常登陆，只有极少部分才会这样。
华为P10  Android 8.0
nexus 5X  Android 7.0

麻烦大大看下是啥情况

**Comment by cxcxcxcx** [comment]
Android 9 吗？我在升级到 TargetSdk 28 后好像解决了问题

**Comment by jixiangxiang** [comment]
我也遇到了相关的问题，微博的人有在解决吗

**Comment by sinaweibosdk** [comment]
请使用最新版本
