### ISSUE TITLE
微博使用微信登录，然后app 使用微博登录，有时会报错，错误码：21301，不能稳定复现

### ISSUE THREAD

**Issue by bad-mask** [sinaweibosdk/weibo_android_sdk#437]
![image](https://user-images.githubusercontent.com/26804743/52692262-678ad200-2f9e-11e9-88f2-bdabb9ab8086.png)

**Comment by zhangkevd** [comment]
直接就关掉了？

**Comment by zhangqifan1** [comment]
俺也一样

**Comment by addappcn** [comment]
这他妈的服务，什么都没有回复直接关闭 ，辣鸡
