### ISSUE TITLE
Could not find :openDefault-4.3.6:.

### ISSUE THREAD

**Issue by fenggit** [sinaweibosdk/weibo_android_sdk#439]
Could not find :openDefault-4.3.6:.

repositories {
    flatDir {
        dirs 'libs'
    }
}

implementation(name:'openDefault-4.3.6', ext:'aar')

求解

**Comment by bewareofbears** [comment]
典型的不看文档

implementation('com.sina.weibo.sdk:core:4.2.5:openDefaultRelease@aar'）

跟
buildscript {
    repositories {
        jcenter()
        google()
        maven {
            url "https://dl.bintray.com/thelasterstar/maven/"
            name 'SinaWeibo'
        }
    }
}

**Comment by fenggit** [comment]
> 典型的不看文档
> 
> implementation('com.sina.weibo.sdk:core:4.2.5:openDefaultRelease@aar'）
> 
> 跟
> buildscript {
> repositories {
> jcenter()
> google()
> maven {
> url "https://dl.bintray.com/thelasterstar/maven/"
> name 'SinaWeibo'
> }
> }
> }

你不看我发代码吗？我用的是本地aar，用的是微博sdk里面的，不想用远程的，implementation(name:'openDefault-4.3.6', ext:'aar')
