### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1 web授权微博登录的时候crash

### ISSUE THREAD

**Issue by foreverflame** [sinaweibosdk/weibo_android_sdk#440]
![image](https://user-images.githubusercontent.com/15818301/53938109-1d52c780-40ea-11e9-8298-37bb3bf63cad.png)

**Comment by foreverflame** [comment]
我初始化的时候scope = “all” ，如下：
![image](https://user-images.githubusercontent.com/15818301/53938183-51c68380-40ea-11e9-9d41-477d6f76bc90.png)

**Comment by sinaweibosdk** [comment]
最新版本已经修复
