### ISSUE TITLE
web授权时检查网络状态问题

### ISSUE THREAD

**Issue by mdyoyo** [sinaweibosdk/weibo_android_sdk#441]
用4.3.7版本进行web授权时，会弹窗提示没有网络权限，在源码中发现NetworkHelper.hasInternetPermission()方法在4.3.7版本中的实现改为了用checkCallingPermission判断，看官方文档中说“if you are not currently processing an IPC, this function will always fail”，我理解这个使用场景应该和IPC无关，所以返回了false
之前版本中使用的checkCallingOrSelfPermission是没问题的，官方文档中说明“This is the same as {@link #checkCallingPermission}, except it grants your own permissions if you are not currently processing an IPC”，也就是说对非IPC场景做了兼容
麻烦看下这个问题呢，多谢

**Comment by Biekangdong** [comment]
这个解决了吗？

**Comment by xyz-fly** [comment]
同样遇到该问题：
    public static boolean hasInternetPermission(Context context) {
        if (context != null) {
            return 0 == context.checkCallingPermission("android.permission.INTERNET");
        } else {
            return true;
        }
    }

**Comment by hamberluo** [comment]
回退到 4.3.6 了

**Comment by huirong628** [comment]
这个问题这周会发版本解决

**Comment by sinaweibosdk** [comment]
这个问题这周会发版本解决
