### ISSUE TITLE
weibo内置 accessibility、accessibilityTraversal代码执行漏洞

### ISSUE THREAD

**Issue by cnhappier** [sinaweibosdk/weibo_android_sdk#443]
com.sina.weibo.sdk.web.WeiboSdkWebActivity没有移除漏洞代码。导致存在远程代码执行漏洞。

需要为webview添加以下代码。

//未知 api
removeJavascriptInterface("accessibility");
removeJavascriptInterface("accessibilityTraversal");

说明：https://www.jianshu.com/p/2c69f19e8316

**Comment by sinaweibosdk** [comment]
最新版本已经修改。
