### ISSUE TITLE
使用openDefault-4.3.7.aar，手机没有微博客户端时，调用授权登录接口提示“Application requires permission to access the Internet"

### ISSUE THREAD

**Issue by ByaneChen** [sinaweibosdk/weibo_android_sdk#448]
使用openDefault-4.3.7.aar，手机没有微博客户端时，调用授权登录接口SsoHandler.authorize提示“Application requires permission to access the Internet"，接入4.3.6版本没有问题，App已经申请了网络权限。

**Comment by hiliving** [comment]
+1

**Comment by hiliving** [comment]
你用4.3.6就没事了
