### ISSUE TITLE
GooglePlay需要应用支持64位，请微博提供arm64-v8a及x86_64的so包

### ISSUE THREAD

**Issue by yuCharles** [sinaweibosdk/weibo_android_sdk#451]
GooglePlay强制所有应用支持64位操作系统，请微博提供arm64-v8及x86-64的so包

感谢

**Comment by sinaweibosdk** [comment]
x86-64 这个稍后会支持

**Comment by zhenian** [comment]
> x86-64 这个稍后会支持

稍后是什么时候？？

应该提供所以 abi， 具体发包时，需要用到什么直接添加 filter 就行

**Comment by yuCharles** [comment]
> x86-64 这个稍后会支持

好的，先集成arm64了

**Comment by zhenian** [comment]
催更：  请微博提供arm64-v8a及x86_64的so包

**Comment by wuhh2016** [comment]
哪个版本支持？

**Comment by zhenian** [comment]
催更： 请微博提供 x86_64的so包。 测试 android Q 需要模拟器

**Comment by titanseason** [comment]
请将各个CPU对应的so，直接打包到aar中，而不是让我们二次下载！！！！
如果用户需要，可以自行配置 abiFilters过滤不需要的so，而不是你们不打包

**Comment by houxg** [comment]
4.3.7加上了`arm64-v8a`，4.3.9又去掉了？

**Comment by zhenian** [comment]
> 4.3.7加上了`arm64-v8a`，4.3.9又去掉了？
> Google Play的时间限制是2019-08-01之前，留个你们的时间不多了

@sinaweibosdk 是否可以表现得专业一些？？？？

做SDK开发的，有源码，提供所有平台的 so 包不麻烦吧

armeabi
armeabi­v7a
arm64­v8a
x86
x86_64
mips
mips64
