### ISSUE TITLE
首页里的官方文档404了

### ISSUE THREAD

**Issue by yuCharles** [sinaweibosdk/weibo_android_sdk#452]
首页里的官方文档404了

[微博Android平台SDK文档V4.1.pdf](https://github.com/sinaweibosdk/weibo_android_sdk/blob/master/%E6%96%B0%E6%96%87%E6%A1%A3/%E5%BE%AE%E5%8D%9ASDK%204.0%E6%96%87%E6%A1%A3.pdf)

**Comment by yuan7016** [comment]
the same problem

**Comment by yuCharles** [comment]
首页文档还是404为什么关掉了。。
