### ISSUE TITLE
首页的客服QQ，微博同学，你们认真的么？

### ISSUE THREAD

**Issue by yuCharles** [sinaweibosdk/weibo_android_sdk#453]
```
v4.3.8

1.修复若干bug 2.默认只支持armeabi架构 3.使用4.3.8时，请联系客服进行包名报备，否则会出现crash。联系方式QQ（879073189）
```

然后我搜了下这个QQ

![image](https://user-images.githubusercontent.com/6228325/57918403-4dc49800-78c9-11e9-9336-407c24b86d10.png)

**Comment by sinaweibosdk** [comment]
客服QQ写错了，已更新，879073159
