### ISSUE TITLE
4.3.8版本是来搞笑的吗？ 还需要找客服验证？不验证一直crash，这个客服响应也很慢，没加人，看上去一点都不专业，醉了醉了

### ISSUE THREAD

**Issue by sk-huang** [sinaweibosdk/weibo_android_sdk#454]
couldn't find "libwind.so"

**Comment by yuan7016** [comment]
服了

**Comment by xinledanding** [comment]
服了

**Comment by sinaweibosdk** [comment]
请联系879073159

**Comment by 378063465** [comment]
没人回 ， 什么情况

**Comment by 378063465** [comment]
什么客服， 加群没人回， 加客服不理你

**Comment by 378063465** [comment]
> 服了

大兄弟，怎么解决的

**Comment by sk-huang** [comment]
> > 服了
> 
> 大兄弟，怎么解决的

临时降级到4.3.6，那个号是他们微博的qq群的群主的号，号码隐藏了，搜索不到的，只能在群里找得到他，回复很慢，都不一定让你通过群

**Comment by 378063465** [comment]
> > > 服了
> > 
> > 
> > 大兄弟，怎么解决的
> 
> 临时降级到4.3.6，那个号是他们微博的qq群的群主的号，号码隐藏了，搜索不到的，只能在群里找得到他，回复很慢，都不一定让你通过群
ok，已经解决了。自己使用的支持库他们默认有些不支持需要我们从他们代码里把自己需要的支持库复制过来

**Comment by YouCii** [comment]
呵呵呵
