### ISSUE TITLE
内部使用的activity应该手动设置exported = false

### ISSUE THREAD

**Issue by yan460227804** [sinaweibosdk/weibo_android_sdk#455]
WbShareToStoryActivity,  WbShareTransActivity是内部使用的activity，manifest标签中带有intent-filter，那么exported会默认true，外部其他应用也可以调起来，会造成安全问题，需要手动设置为exported = false

**Comment by sinaweibosdk** [comment]
这个是产品需要，里面涉及到的安全问题已经解决。
