### ISSUE TITLE
weibo_android_sdk什么时候能支持Gradle？

### ISSUE THREAD

**Issue by firebear** [sinaweibosdk/weibo_android_sdk#46]
现在需要导入android studio成为一个模块，源码不能同步更新。
如果能用一行gradle配置搞定就太好了。

dependencies {
...
    compile 'com.sina.weibo.sdk:3.0.0'
}

**Comment by gengjiawen** [comment]
+1

**Comment by david-loman** [comment]
+1

**Comment by jwilljacob** [comment]
SDK 中使用了.so，可能是个问题

**Comment by yongjhih** [comment]
See Also #67

**Comment by yongjhih** [comment]
See Also:

https://github.com/8tory/weibo-android-sdk
https://github.com/8tory/weibo-android-sdk-core
