### ISSUE TITLE
error： 50111262 msg:参数错误

### ISSUE THREAD

**Issue by weifans** [sinaweibosdk/weibo_android_sdk#460]
D/WeiboSsoSdk: load aid error!
D/WeiboSsoSdk: loadAidFromNet JSONException Msg : error： 50111262 msg:参数错误

请问这是什么参数不对？

**Comment by weifans** [comment]
QQ群添加了不通过。
发送邮件提示邮件空间不足。

请问还有其他技术支持吗？

**Comment by weifans** [comment]
我是用的SDK4.3.8，一直报这个错误。
加了QQ群，原来需要找群主报备一下才能用。新浪真是太会玩了。

**Comment by sinaweibosdk** [comment]
对更新造成的困扰非常抱歉，请联系客服879073159

**Comment by huangyongxin1986** [comment]
请问这个问题怎么解决呀，我也碰到了

**Comment by weifans** [comment]
@huangyongxin1986 加我微信吧 帮你看一下 6557785

**Comment by orient33** [comment]
同样遇到,,找不到文档来处理/解决这个问题..
