### ISSUE TITLE
UnsatisfiedLinkError for couldn't find "libweibosdkcore.so"

### ISSUE THREAD

**Issue by pipBug** [sinaweibosdk/weibo_android_sdk#461]
device: Android 7.0 level 24
abi: arm64-v8a
maven: implementation "com.sina.weibo.sdk:core:4.3.7:openDefaultRelease@aar"

![image](https://user-images.githubusercontent.com/13911593/58535534-d70c9080-8220-11e9-9f2b-b2605ee11225.png)

在以上设备上出现 Crash

**Comment by sinaweibosdk** [comment]
请使用最新版本4.3.9

**Comment by pipBug** [comment]
请问 v4.3.9 是否需要进行包名报备？
