### ISSUE TITLE
【V4.3.0及以上】横屏App分享存在严重Bug: 分享内容重复/分享页面重复打开/退出分享再次自动打开分享页

### ISSUE THREAD

**Issue by jianweizhou** [sinaweibosdk/weibo_android_sdk#462]
【分析】  横屏App分享到微博，会发生屏幕旋转也就是ConfigureChange，导致WbShareTransActivity重建，4.3.0及以后版本未处理这种情况导致必现Bug

【解决方案】  目前想到两种BugFix：
1. Manifest activity添加onConfigureChange声明，建议所有activity都添加，避免activity重建      2.activity重建提前return，比如WbShareTransActivity#onCreate中 onSaveInstance!=null 时提前return

麻烦大佬尽快修复下！~~

**Comment by jianweizhou** [comment]
自己动手丰衣足食，Manifest声明增加了screenSize后问题解决，即android:configChanges="orientation|keyboardHidden|screenSize"。

奉上自己修改的aar。

[weibo-core-4.3.1-landscape.aar.zip](https://github.com/sinaweibosdk/weibo_android_sdk/files/3256117/weibo-core-4.3.1-landscape.aar.zip)

**Comment by ixiaow** [comment]
也可以使用下面的方式替换WbShareTransActivity中的属性：
```
<!--替换微博sdk中的配置-->
        <activity
            android:name="com.sina.weibo.sdk.share.WbShareTransActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            tools:replace="configChanges" />
```

**Comment by yrickwong** [comment]
> 
> <activity
>     android:name="com.sina.weibo.sdk.share.WbShareTransActivity"
>     android:configChanges="orientation|keyboardHidden|screenSize"
>     tools:replace="configChanges" />

在哪里配置？  自己App的 Manifest吗？  这样不会提示冲突吗？
