### ISSUE TITLE
so库未打包至aar，导致crash

### ISSUE THREAD

**Issue by titanseason** [sinaweibosdk/weibo_android_sdk#466]
目前aar中只打包了armeabi的so库，其他架构的CPU就会找不到so库而闪退

请将各个CPU对应的so，直接打包到aar中，而不是让开发者二次下载！！！！
如果开发者需要，可以自行配置 abiFilters过滤不需要的so，而不是你们不打包

**Comment by titanseason** [comment]
下载你们额外的so，有多麻烦，自己试过吗？要dowload整个项目！！！！！

**Comment by hpuhsp** [comment]
同样的问题，希望引起官方重视！！！4.3.7版本后既然增加了ARM64支持64位，为何还不把so打进aar?

**Comment by gaobq** [comment]
4.3.9 aar还不支持 64bit 最近有新版本放出来吗
不用使用者自己集成64bit的so吧?

 8月1号也快了 也给使用者留一个集成so后测试修bug的时间吧
