### ISSUE TITLE
4.3.9无限闪退

### ISSUE THREAD

**Issue by princeHe** [sinaweibosdk/weibo_android_sdk#471]
按照官方文档配置，不管是通过maven仓库还是直接下载aar包，都无限闪退，报找不到so库。

**Comment by LittleWindSXF** [comment]
新版本增加了libwind.so，需要自己集成到项目中：
https://github.com/sinaweibosdk/weibo_android_sdk/tree/master/so/arm64-v8a

**Comment by princeHe** [comment]
为什么不打进aar包里呢？文档中也没有说明，文档的描述是包含了armeabi,armeabi-v7a, arm64-v8a的啊。。。
