### ISSUE TITLE
4.3.9vivo和锤子手机出现初始化sdk错误，导致app闪退

### ISSUE THREAD

**Issue by junglehang** [sinaweibosdk/weibo_android_sdk#472]
14:57:39.359   4859      4889      E   AndroidRuntime: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
14:57:39.359   4859      4889      E   AndroidRuntime: at android.os.Handler.<init>(Handler.java:200)
14:57:39.359   4859      4889      E   AndroidRuntime: at android.os.Handler.<init>(Handler.java:114)
14:57:39.359   4859      4889      E   AndroidRuntime: at android.location.LocationManager$ListenerTransport$1.<init>(LocationManager.java:227)
14:57:39.359   4859      4889      E   AndroidRuntime: at android.location.LocationManager$ListenerTransport.<init>(LocationManager.java:227)
14:57:39.359   4859      4889      E   AndroidRuntime: at android.location.LocationManager.wrapListener(LocationManager.java:875)
14:57:39.359   4859      4889      E   AndroidRuntime: at android.location.LocationManager.requestLocationUpdates(LocationManager.java:889)
14:57:39.359   4859      4889      E   AndroidRuntime: at android.location.LocationManager.requestLocationUpdates(LocationManager.java:465)
14:57:39.359   4859      4889      E   AndroidRuntime: at com.weibo.ssosdk.MfpBuilder$LocationInfo.init(MfpBuilder.java:156)
14:57:39.359   4859      4889      E   AndroidRuntime: at com.weibo.ssosdk.MfpBuilder$LocationInfo.access$400(MfpBuilder.java:106)
14:57:39.359   4859      4889      E   AndroidRuntime: at com.weibo.ssosdk.MfpBuilder.init(MfpBuilder.java:170)
14:57:39.359   4859      4889      E   AndroidRuntime: at com.weibo.ssosdk.WeiboSsoSdk.initConfig(WeiboSsoSdk.java:115)
14:57:39.359   4859      4889      E   AndroidRuntime: at com.sina.weibo.sdk.sso.WeiboSsoManager.init(WeiboSsoManager.java:37)
14:57:39.359   4859      4889      E   AndroidRuntime: at com.sina.weibo.sdk.WbSdk.install(WbSdk.java:33)
14:57:39.359   4859      4889      E   AndroidRuntime: at com.hiq178.unicorn.global.MyApplication$1.run(MyApplication.java:148)
14:57:39.359   4859      4889      E   AndroidRuntime: at java.lang.Thread.run(Thread.java:818)

**Comment by sinaweibosdk** [comment]
4.4.0已经修复
