### ISSUE TITLE
【安全问题】使用了不安全的加密算法ECB

### ISSUE THREAD

**Issue by LittleWindSXF** [sinaweibosdk/weibo_android_sdk#476]
各位weibo sdk的开发者好，请关注以下问题，谢谢：
在AAR的类com.sina.weibo.sdk.utils.AidTask中，使用了不安全的ECB加密算法：
Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");

希望能尽快在下个版本解决此问题，升级为使用更安全的加密算法，感谢~

**Comment by sinaweibosdk** [comment]
请使用最新版本
