### ISSUE TITLE
WbSdk.install时ANR

### ISSUE THREAD

**Issue by pinguo-baidengfeng** [sinaweibosdk/weibo_android_sdk#478]
问题描述：
网络不好时，初始化SDK导致ANR.  sdk版本号: 4.3.9

复现步骤：
step 1: 在Vivo X21A （Android 9.0)上使用其他手机（比如手机B）的热点
step2: 让手机B的热点不真正链接到网络，这时在Vivo X21A上无法访问网络。
step3: 调用Wbsdk.install就ANR了。

**Comment by sinaweibosdk** [comment]
请使用最新版本4.4.0检查该问题。

**Comment by pinguo-baidengfeng** [comment]
4.4.0同样有这个问题。我看了下代码：

**Comment by pinguo-baidengfeng** [comment]
4.4.0同样有这个问题。代码中：

**Comment by pinguo-baidengfeng** [comment]
4.4.0同样有这个问题。看这段代码：
                Thread t = new Thread(new Runnable() {
                    public void run() {
                        try {
                            WeiboSsoSdk.this.updateInfo("", 1);
                        } catch (Exception var2) {
                            ;
                        }

                    }
                });
                t.start();
                t.join();
在updateInfo(...)中会发送一个post请求，该请求有几秒的timeout。这样在主线程join这个线程，导致整个install()方法耗时较多。

我没办法，最后在自己应用层的代码里新启动个线程调用WbSdk.install()，自己额外加锁保证了下线程安全...

**Comment by v7lin** [comment]
微博最近在搞什么 。。。 4.4.2 上依然存在 ANR

**Comment by PiYun01** [comment]
这个anr SDK都没修复怎么就关了啊

**Comment by v7lin** [comment]
微博SDK开发就是来搞笑的 ...
