### ISSUE TITLE
【必现崩溃】【兼容性】部分机型出现微博分享失败，并导致APP崩溃

### ISSUE THREAD

**Issue by LittleWindSXF** [sinaweibosdk/weibo_android_sdk#479]
各位开发者好，有以下问题请帮忙关注下，感谢！

目前发现在荣耀6X机型上，分享失败，并出现必现崩溃，日志如下：
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.sina.weibo.sdk.auth.WbAppInfo.getSupportVersion()' on a null object reference
	at com.sina.weibo.sdk.share.WbShareHandler.shareMessage(SourceFile:84)

**Comment by sinaweibosdk** [comment]
收到，我们尽快解决。

**Comment by LittleWindSXF** [comment]
感谢回复。  
增加点信息：现在发现多款7.0及以下的手机都有这个问题，影响范围较大，需要紧急修复，请问大概什么时候能出新版本修复呢？
盼尽快复，多谢~

**Comment by lightSky** [comment]
@sinaweibosdk  hi，这个问题已经修复了嘛？
