### ISSUE TITLE
error： 50111262 msg:参数错误

### ISSUE THREAD

**Issue by huangyongxin1986** [sinaweibosdk/weibo_android_sdk#482]
D/WeiboSsoSdk: load aid error!
D/WeiboSsoSdk: loadAidFromNet JSONException Msg : error： 50111262 msg:参数错误
对应的HTTP请求地址是https://login.sina.com.cn/visitor/signin，返回结果：{"retcode":50111262,"msg":"参数错误","data":{"errline":100}}
请问这是什么参数不对？

**Comment by sinaweibosdk** [comment]
需要报备下（879073159）

**Comment by orient33** [comment]
@sinaweibosdk   请问改怎么报备
