### ISSUE TITLE
MD5签名生成器

### ISSUE THREAD

**Issue by xiemuyou** [sinaweibosdk/weibo_android_sdk#484]
确定手机已经安装, 输入包名 com.xxx.xxx
点击生成 ---->> MD5 空白, 点击没反应

**Comment by ixiaow** [comment]
可以使用adb命令获取签名：
1. 进入用户目录下，找到.android目录；
2. 执行 keytool -list -v -keystore xxx.jks  （xxx.jks app打包的签名文件路径）
3. 输入打包key密码（不回显），然后就可以看到md5了
