### ISSUE TITLE
分享视频没反应，我用的是最新版的SDK（4.4）

### ISSUE THREAD

**Issue by onedreamyyc** [sinaweibosdk/weibo_android_sdk#485]
以下是分享的视频参数：
VideoSourceObject videoSourceObject = new VideoSourceObject();
        videoSourceObject.title = "视频标题";
        videoSourceObject.description = "描述";
        videoSourceObject.actionUrl = "http://image.520dk.net/kj/5/video/20190712094825eovQ3Z.mp4";
        Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.drawable.ic_71_71);
        videoSourceObject.setThumbImage(bitmap);
下面是调用分享后出现的日志：
![video_error](https://user-images.githubusercontent.com/22291176/61946406-17944a80-afd5-11e9-8ef6-ae7257747652.png)

**Comment by onedreamyyc** [comment]
网上以及官方都没找到关于这个视频分享的相关资料 官方QQ群也进不去，哪位同志知道指点一下，万分感谢，急。。。

**Comment by Cmdone** [comment]
是因为不支持网络视频吧。。。

**Comment by sinaweibosdk** [comment]
视频只支持本地
