### ISSUE TITLE
微博登陆在魅族4上失败

### ISSUE THREAD

**Issue by qluan** [sinaweibosdk/weibo_android_sdk#49]
现象：调用微博登陆后，都会跳转到web页面要求输入用户名、密码，输入完成点击确定，又还是如此，一直循环。

展示没有发现其他机器存在这个问题

**Comment by sinaweibosdk** [comment]
我们用魅族4手机上测试了，没有复现该问题，能帮忙将"点击确定"后相应的log贴下么，以方便我们定位问题。
