### ISSUE TITLE
这是什么Log，能否取消？

### ISSUE THREAD

**Issue by weifans** [sinaweibosdk/weibo_android_sdk#490]
D/ssosdk: 1: 
    lo
    00:00:00:00:00:00
    2: 
    bond0
    46:b6:d5:fd:81:98
    3: 
    dummy0
    56:20:3c:e6:26:43
    4: 
    ip_vti0
    0.0.0.0
    5: 
    ip6_vti0
    ::
    6: 
    sit0
    0.0.0.0
    7: 
    ip6tnl0
    ::
    8: 
    rmnet_ipa0
    9: 
    rmnet_data0
    10: 
    rmnet_data1
    11: 
    rmnet_data2
    12: 
    rmnet_data3
    13: 
    rmnet_data4
    14: 
    rmnet_data5
    15: 
    rmnet_data6
    16: 
    rmnet_data7
    17: 
    rmnet_data8
    18: 
    rmnet_data9
    19: 
    rmnet_data10
    20: 
    r_rmnet_data0
    21: 
    r_rmnet_data1
    22: 
    r_rmnet_data2
D/ssosdk: 23: 
    r_rmnet_data3
    24: 
    r_rmnet_data4
    25: 
    r_rmnet_data5
    26: 
    r_rmnet_data6
    27: 
    r_rmnet_data7
    28: 
    r_rmnet_data8
    29: 
    wlan0
    d8:ce:3a:8b:16:aa
    30: 
    wlan1
    d8:ce:3a:0b:16:aa
    31: 
    p2p0
    da:ce:3a:0c:16:aa

**Comment by sinaweibosdk** [comment]
4.4.3fixed
