### ISSUE TITLE
微博SDK4.4.1在4.4手机上web分享失败

### ISSUE THREAD

**Issue by fights** [sinaweibosdk/weibo_android_sdk#492]
微博SDK：4.4.1
场景一：
手机：红米2A（4.4.4），三星SM-G9008V（4.4.2）
带有图片分享，未安装微博客户端（web分享情况），点击分享，微博SDK会首先上传图片到服务端，ShareWebViewRequestParam#doExtraTask()方法时，网络请求报错：
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. 造成分享失败

场景二：
手机：5.0以上手机
依然是微博SDK上传图片时，服务端返回结果success，但是没有picId信息，造成分享失败。

附上微博SDK中的源码：
![image](https://user-images.githubusercontent.com/22186822/65128229-a64ca300-da2b-11e9-8357-e1197f4e230c.png)

**Comment by dunwen** [comment]
+1, 一样的问题，上传图片接口返回 code 0，没有 data，导致分享失败

**Comment by maofuqiang** [comment]
我更新完 4.4.1 也遇到此问题。
![image](https://user-images.githubusercontent.com/12031603/66892528-85717080-f01e-11e9-8a58-8935177a76dd.png)

**Comment by cn00** [comment]
从3.0开始web分享就时好是不好，iOS那边也是，解决办法就是建议用户再装个微博客户端吧

**Comment by maofuqiang** [comment]
> 从3.0开始web分享就时好时不好，图片传不过去，iOS那边也是，解决办法就是建议用户再装个微博客户端吧

我这个问题是 微博那边没有把我公司APP包名添加白名单，导致微博不识别我们APP，添加后测试可以。（PS：哈哈哈，其实我对微博web分享倒是无所谓，现在谁手机上还不装个微博APP，主要是测试追着不放）

**Comment by dunwen** [comment]
> > 从3.0开始web分享就时好时不好，图片传不过去，iOS那边也是，解决办法就是建议用户再装个微博客户端吧
> 
> 我这个问题是 微博那边没有把我公司APP包名添加白名单，导致微博不识别我们APP，添加后测试可以。（PS：哈哈哈，其实我对微博web分享倒是无所谓，现在谁手机上还不装个微博APP，主要是测试追着不放）

+1 测试追着不放
