### ISSUE TITLE
使用google service之后 调用WbSdk.install 报错: visitor login failed

### ISSUE THREAD

**Issue by lefan14** [sinaweibosdk/weibo_android_sdk#494]
com.weibo.ssosdk.WeiboSsoSdk.getAid(WeiboSsoSdk.java:363)
com.sina.weibo.sdk.sso.WeiboSsoManager.initAid(WeiboSsoManager.java:42)
com.sina.weibo.sdk.sso.WeiboSsoManager.init(WeiboSsoManager.java:37)
com.sina.weibo.sdk.WbSdk.install(WbSdk.java:33)

**Comment by sahabe1** [comment]
@lefan14 have you fixed this issues

**Comment by sinaweibosdk** [comment]
4.4.3fixed.
