### ISSUE TITLE
release版本日志打印了用户的MAC地址

### ISSUE THREAD

**Issue by BarbaPedro** [sinaweibosdk/weibo_android_sdk#499]
版本：openDefault 4.4.1
实际打印日志：11-01 14:45:08.939 16681 17709 D ssosdk  : 8a:xx:e4:xx:23:19
打印日志的代码：SDK里的libwind.so文件，发现print_linkinfo 函数打印了MAC地址

该函数打印是debug日志，但实际正式版本打印了，望修复。

**Comment by sinaweibosdk** [comment]
最新的版本已经删除了该日志。
