### ISSUE TITLE
①第一次分享提示失败，但第二次之后才成功，是怎么回事？②有时点击微博分享，没有跳转成功，也就是点击无反应

### ISSUE THREAD

**Issue by sinaweibosdk** [sinaweibosdk/weibo_android_sdk#5]
目前有个比较土的解决办法，就是提前初始化微博，如在oncreate里不管用不用，先调用
mWeiboAPI = WeiboSDK.createWeiboAPI(mActivity, KEY_SINA);
mWeiboAPI.registerApp();

最好能控制这个两行代码能执行很久之后再调用mWeiboAPI.sendRequest(mActivity, req)，起始就是很早很早就准备了微博的初始化和注册。

目前这个解决方案好像也解决了，首次点击分享（此时没有登录微博），登录后又返回到第三方应用而没有跳到分享界面问题，

**Comment by crystalyuan** [comment]
onCreate 时调用
mWeiboAPI = WeiboSDK.createWeiboAPI(mActivity, KEY_SINA);
mWeiboAPI.registerApp();
用户点击分享 sendRequest
我没有反应啊，不跳转不报错，这是啥子情况？

**Comment by BTyang** [comment]
目前这个解决方案好像也解决了，首次点击分享（此时没有登录微博），登录后又返回到第三方应用而没有跳到分享界面问题

问题还是存在。。

**Comment by MrUncleYzw** [comment]
最新版的为啥还是有这个问题啊啊啊啊啊，疯了

**Comment by lntmny** [comment]
3.1.4 同样有这种问题，  demo 中  music 的图片不是 png 却带个 png 扩展名，还有好几张  nine-path 都没处理， 编译都通不过。

**Comment by Freerain9** [comment]
找到这个问题的解决方法了  是因为  你只是做了 分享 而没有做 授权。所以 你的分享 依赖于app的登陆状态，而不是自己保存。
