### ISSUE TITLE
weibo sdk was not initall

### ISSUE THREAD

**Issue by huma8848888** [sinaweibosdk/weibo_android_sdk#501]
线上崩溃，都是按照官方文档流程操作的，线上竟然出了这个bug，有人知道为什么吗：
weibo sdk was not initall! please use: WbSdk.install() in your app Application or your main Activity. when you want to use weibo sdk function, make sure call WbSdk.install() before this function

**Comment by jjkopen** [comment]
先执行WbSdk.install初始化，再执行其他方法
