### ISSUE TITLE
升级到4.4.2之后 打开应用闪退java.lang.String com.weibo.ssosdk.WeiboSsoSdk$VisitorLoginInfo.getAid()

### ISSUE THREAD

**Issue by xiaorenwu94666** [sinaweibosdk/weibo_android_sdk#504]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.weibo.ssosdk.WeiboSsoSdk$VisitorLoginInfo.getAid()' on a null object reference

**Comment by sinaweibosdk** [comment]
4.4.3版本已经修复。
