### ISSUE TITLE
WbSdk初始化ANR

### ISSUE THREAD

**Issue by PiYun01** [sinaweibosdk/weibo_android_sdk#506]
java.lang.Object.wait(Native method) )at java.lang.Object.wait(Object.java:422) )at java.lang.Thread.join(Thread.java:1262) )at java.lang.Thread.join(Thread.java:1338) )at com.weibo.ssosdk.WeiboSsoSdk.getAid(WeiboSsoSdk.java:360) )at com.sina.weibo.sdk.sso.WeiboSsoManager.initAid(WeiboSsoManager.java:42) )at com.sina.weibo.sdk.sso.WeiboSsoManager.init(WeiboSsoManager.java:37) )at com.sina.weibo.sdk.WbSdk.install(WbSdk.java:33) )
--

**Comment by Rannver** [comment]
同遇到，有解决办法么。。。之前尝试过开一个线程初始化但是会报crash。。放在主线程又会ANR。。real难受。。
