### ISSUE TITLE
follow_app_official_microblog   不生效的问题

### ISSUE THREAD

**Issue by zhang-yuehuan** [sinaweibosdk/weibo_android_sdk#507]
hello,  我们有一个授权页关注app微博运营官号的需求，发现按照文档设置了follow_app_official_microblog  这个scope, 授权页也还是没有勾选运营号的样子。求助一下各位大大们。期待回复~ 3Q

**Comment by sinaweibosdk** [comment]
这个需要联系平台的负责人，我这边只是负责SDK的接入。
