### ISSUE TITLE
JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1029720)

### ISSUE THREAD

**Issue by coffee3689** [sinaweibosdk/weibo_android_sdk#509]
你好，请教一个问题，我集成了 2019 微博 sdk，然后在分享 web 类型到新浪微博的时候报错了，按照理论来说，我之前分享到微信的图片都能到2.2M，现在1M左右都不能分享，是不是我使用方式有误，，能帮我看下什么原因吗

`JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1029720)
 E/ActivityTaskManager: Second failure launching com.sina.weibo.sdk.share.ShareTransActivity, giving up
    android.os.TransactionTooLargeException: data parcel size 1029720 bytes`

thanks,
have a nice day!

**Comment by sinaweibosdk** [comment]
请问你是怎么分享web的？
