### ISSUE TITLE
无网络的情况下打开app，sdk打印如下日志，并且会导致app启动很慢

### ISSUE THREAD

**Issue by leestars** [sinaweibosdk/weibo_android_sdk#510]
sdk版本是v4.4.1
D/ssosdk: 1: 
D/ssosdk: lo
D/ssosdk: 00:00:00:00:00:00
D/ssosdk: 2: 
D/ssosdk: dummy0
D/ssosdk: 6a:ab:8f:37:44:16
D/ssosdk: 3: 
D/ssosdk: sit0
D/ssosdk: 0.0.0.0
D/ssosdk: 4: 
D/ssosdk: rmnet0
D/ssosdk: 5: 
D/ssosdk: rmnet_data0
D/ssosdk: 6: 
D/ssosdk: rmnet_data1
D/ssosdk: 7: 
D/ssosdk: rmnet_data2
D/ssosdk: 8: 
D/ssosdk: rmnet_data3
D/ssosdk: 9: 
D/ssosdk: rmnet_data4
D/ssosdk: 10: 
D/ssosdk: rmnet_data5
D/ssosdk: 11: 
D/ssosdk: rmnet_data6
D/ssosdk: 12: 
D/ssosdk: rmnet_data7
D/ssosdk: 13: 
D/ssosdk: r_rmnet_data0
D/ssosdk: 14: 
D/ssosdk: r_rmnet_data1
D/ssosdk: 15: 
D/ssosdk: r_rmnet_data2
D/ssosdk: 16: 
D/ssosdk: r_rmnet_data3
D/ssosdk: 17: 
D/ssosdk: r_rmnet_data4
D/ssosdk: 18: 
D/ssosdk: r_rmnet_data5
D/ssosdk: 19: 
D/ssosdk: r_rmnet_data6
D/ssosdk: 20: 
D/ssosdk: r_rmnet_data7
D/ssosdk: 21: 
D/ssosdk: r_rmnet_data8

D/ssosdk: build_post_msg() succ: data=SB%2BY1XDZVYrnM0Idp77tHftNChX2d%2FnlrG7SFFbLHwf0uznjteLvMim1P3pR5CRhpddORc5z%0AhReWkNM9rGpsldNmnKTBf%2B0hXF19ajTOdejLfll9JS31ttKnSfVaVfR2djCMLiPN86csD05w%0A1RYugucuaAE0TrC4k3Vyev%2FLeIHjEnsiz0ppbxFwrtVmd%2FNbsmoyhe2vrAyAUMO8H5%2F5ZEl1%0AyNGDYY8HiqSOWsgwa%2FzEtM79zOgBghD7drAZk1TY2%2BwtwfjJ2AOFu3slxPQg4f0K6eYTi%2Bk1%0AnxC4HKeMrJNAgTaVQXTVKOSdCKU36nJbqO9Knf8L77wogNpmHXnCPLxJwQFqejyzhfHQ1oF6%0A5YFuYNF%2ByAFVYRgj1FTLZWvBvKaC%2BURDspV7Y8Arnm33kkvi7XsXSE1cpP4Ho%2FpIdLfj47Ck%0Arzc5gTnCHArmzqM7tsn2zi3guQkkqv2NsFwHQKTqqRqE61IaGGEO9IzjI2MrtG8R8Vg6dA1D%0AXMxYIXixFkqV7WRS3X5bs9w%2FQEHyOz9xRN6WvZM5CLSpnMyZU77a7qeBabco63kbVR%2FE0%2BWc%0AdancrX1WcB5n7YdxwYRaM5myOLCacLrUxUwW7%2FhySP8PId0b4QAnjyX%2FlAVcUiDx6%2FrMPFoh%0AzSUScgNT7JNv%2FlPwumRnUARAv2A1eVxUu3U%2FLw3eeMobbdFVxSMIFaLod1jB7uXMmjk6B%2B0x%0AmZ7KoipoCJxuT9CDkmmsb3QQAgfKVllnhNB7YHaeeyisv7ER3TQGMsrkh9gsED13vjNmtV6j%0AW%2BzJEtWdQcRN9xpNYBKL%2FXJlnzyrubDEOdtivqXOm0by9u7M5NK15jlEYAtoXPB3JlC0LKCe%0AqYAFyijh3Hp%2Fd5MvtECcmfItIahy6J4ezXNRn%2BJoV%2Fl

接着就报错了
 java.lang.Exception: visitor login failed
     at com.weibo.ssosdk.WeiboSsoSdk.getAid(WeiboSsoSdk.java:363)
     at com.sina.weibo.sdk.sso.WeiboSsoManager.initAid(WeiboSsoManager.java:4
     at com.sina.weibo.sdk.sso.WeiboSsoManager.init(WeiboSsoManager.java:37)
     at com.sina.weibo.sdk.WbSdk.install(WbSdk.java:33)

**Comment by sinaweibosdk** [comment]
请使用最新版本
