### ISSUE TITLE
新浪微博存在http明文传输用户高敏感信息问题

### ISSUE THREAD

**Issue by Hearmen** [sinaweibosdk/weibo_android_sdk#514]
集成了微博 sdk 的应用在实际使用时，可以监控到 http 数据包明文传递用户 MAc 地址，imei 号等高敏感信息。请处理

`
http://sdkclick.mobile.sina.cn/interface/sdk/sdkclick.php?wua=DD097B3D49F553FB9010D715F6C689213B750281EFC29B2D2965DB96CC9B7983592D9CAF8274FB27EEFB006A4BF49E23E260C86F43B96917068BBBED10711486AF6F6989769F1BFA4DE4D3D86EE1B4BB0B23790627403B70BC819154FD6774497D771A79D0EF7ABCB1AC24BCDD9AFC7C3C98E62185F5BC8D9C91A0B048C556BE503F46282E4844C3FBDF6C3134FB19D2669B5689D1D98A274BDB285BDF3F0C45&tokenid=0&skin=default&type=1&mac=04%3A79%3A70%3A59%3AED%3AE2&platform=android&uid=2533109777&ref=1&adword=&sdkversion=5.0.0&adid=w_ad_5e0ee526174d6&wm=9006_2001&from=10A0095010&radio_type=UNKNOWN&info=180150000%2B180150001%40773509208671362341&dinfo=-1000_-1000&c=android&aduserid=97B2CA02EAC8B500&net_type=1&i=743d3d5&adurl=wbad%3A%2F%2Fclosead&adwordid=12376904603401%3B10064%3B0cbf09e7713c72ca9e314bb4a7564e57%3B0%3BWB19123820%3B253310977715781237%3B1578123769&cdma_type=-1000&posid=pos5135551ba2245&size=1200x1836&cinfo=DBB202E09B04241B790B7F29CE7D9E970EA95AE7004056F4666502EBE9B700352D8A952BD629DB805366AB129682E1A192DABF4A7C3699CC&nettype=1&imei=4QU0118302000025
`

**Comment by sinaweibosdk** [comment]
4.4.4 解决
