### ISSUE TITLE
麻烦问下9.12新版appcompat库依赖是必须的么

### ISSUE THREAD

**Issue by stentz** [sinaweibosdk/weibo_android_sdk#515]
发现新版AAR里面res下有几个资源，其中styles里面的SDKTheme引用了Theme.AppCompat.Light.NoActionBar，不知道是否必须得，代码里是否也有引用appcompat?
![QQ图片20200110145703](https://user-images.githubusercontent.com/2967536/72132313-93ceee80-33b9-11ea-882f-e7d255f5127b.png)

**Comment by stentz** [comment]
@sinaweibosdk

**Comment by MrZhaobh** [comment]
同问
