### ISSUE TITLE
何时重新提供x86和x86-64的so库？

### ISSUE THREAD

**Issue by lcdlyxrqy** [sinaweibosdk/weibo_android_sdk#520]
已经好几个版本没有提供了，基于x86的安卓平台还是有一定数量的，而且测试时安卓模拟器也最好使用x86的镜像，否则性能很成问题。
能否尽快提供？不要一味无回答地关闭issue了谢谢。

**Comment by MrLiu199** [comment]
同求，为什么不能提供x86的so呢，是技术上难以实现么，至少也得告知一下原因呢。
