### ISSUE TITLE
新浪微博分享图片失败

### ISSUE THREAD

**Issue by tonlion** [sinaweibosdk/weibo_android_sdk#523]
请问新浪微博在图片大小或分辨率上有什么限制，麻烦明示出来，我现在使用最新的SDK，分享1M以内的图片会存在闪退的问题。

具体图片在下方，麻烦提供一下解决方案。

![bradley](https://user-images.githubusercontent.com/12855249/77146396-e87f9b80-6ac5-11ea-8781-4000485e768e.jpg)

**Comment by chenyanmo** [comment]
同问，长图如何限制
