### ISSUE TITLE
联系不上

### ISSUE THREAD

**Issue by micadalee** [sinaweibosdk/weibo_android_sdk#525]
3个Q群，一个拒绝，两个没回复，发邮件也没回复，咱也不知道咋能联系上，是没人维护了？

**Comment by tonlion** [comment]
我也是，各种途径联系之后，都没反应，闪退问题官方都不重视。

**Comment by micadalee** [comment]
> 我也是，各种途径联系之后，都没反应，闪退问题官方都不重视。

这可能是接的所有SDK里最有个性的一个，然而还不得不接，如果有选择，我直接选择第三方

**Comment by iimondo** [comment]
文档地址404，也不维护？？

**Comment by zcychinese** [comment]
已经放弃微博了，官方对文档的维护简直惨不忍睹。
