### ISSUE TITLE
分享到微博以后取消，大概率出现一个滚动条无限滚动

### ISSUE THREAD

**Issue by reallychenchi** [sinaweibosdk/weibo_android_sdk#527]
分享到微博以后取消，大概率出现一个滚动条无限滚动，只有手工按一下返回，才能关闭这个滚动条界面，否则不能做任何操作。

**Comment by horizonless** [comment]
请问这个问题后来有解决么？遇到一样的问题

**Comment by charles-yinyu** [comment]
转发界面，点击取消，选择保存草稿，收不到回调，界面停留在SinaTransActivity，有个圈圈一直在转动。

**Comment by sinaweibosdk** [comment]
10.7.0修复该问题
