### ISSUE TITLE
分享失败问题

### ISSUE THREAD

**Issue by life2smile** [sinaweibosdk/weibo_android_sdk#530]
问题：
（1）分享的时候可以唤起微博客户端（10.4.1版本），但是分享后提示，“有内容发送失败，已存入草稿箱”，但是点击进草稿箱后无任何内容。然后，使用网页版微博可以分享成功。
（2）sdk版本：com.sina.weibo.sdk:core:9.12.0:openDefaultRelease

**Comment by micadalee** [comment]
9.12.0，微博未登录，分享时取消，返回桌面，再点击APP图标，APP会重启，demo也如此，你可以试下

**Comment by horizonless** [comment]
操作步骤：
    1、安装微博
    2、退出微博登陆
    3、选择分享微博
    4、不登陆账号，取消分享
    5、home切到后台再点击游戏
以上步骤就会闪退，其实home键出去，再点回来就基本闪退。 
保存到草稿箱是有一个activity -> 
`com.sina.weibo.sdk.share.ShareTransActivity` 这个没关掉导致一个loading转圈的页面
解决方法就是，`OnResume`里面自己判定帮SDK`finish()`很蛋疼但能解决。。。

这个闪退找到了个解决办法
处理方法: ` intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|FLAG_ACTIVITY_MULTIPLE_TASK);` 
在做ShareActivity的时候新开一个TASK，结束后weibo SDK杀掉整个TASK，不会影响到自己本身App的TASK，就不会crash了

微博SDK问题真的很蛋疼
