### ISSUE TITLE
微博用户未登入情况下进行客户端分享

### ISSUE THREAD

**Issue by ZhZhZhen** [sinaweibosdk/weibo_android_sdk#531]
接入的是9.12的sdk，
1、未登入情况下如果在微博登入页面直接点击左上角X，会导致一个无限loading出现在页面上
使用demo也有这种情况。。
2、登入情况下，点击取消，询问是否保存草稿，如果点击保存，返回后也会出现无限loading

**Comment by ZhZhZhen** [comment]
另外还想请教如何处理网页端微博分享时的页面退出动画，现在离开页面的动画看起来好诡异。。

**Comment by horizonless** [comment]
loading 你可以手动后退，或者OnResume的时候杀掉activity解决。本身SDK的问题，从来没解决过好像。。。

**Comment by ZhZhZhen** [comment]
> loading 你可以手动后退，或者OnResume的时候杀掉activity解决。本身SDK的问题，从来没解决过好像。。。

**Comment by ZhZhZhen** [comment]
吐槽一下，从网页端返回，从客户端登入授权页返回，从选择保存草稿/不保存草稿返回，怎么会有这么多种的页面关闭动画，直接统一不用动画不是简单明白= =

**Comment by sinaweibosdk** [comment]
下个版本统一解决。
