### ISSUE TITLE
9.12.0跳转微博分享后，直接回到桌面。自有app（demo）会被重建

### ISSUE THREAD

**Issue by ljcace** [sinaweibosdk/weibo_android_sdk#534]
9.12.0跳转微博分享，然后去点击home键回到桌面，点击自有app或demo，此时自有app或demo会被重建，重新启动打开app的启动页。

回到桌面不去点击自有app或demo，再次点击微博：
未登录情况下，重新回到微博登录页，然后点X，自有app或demo同样会被重建，而无法返回分享页
登录情况下，点击取消或发送，自动返回，自有app或demo不会被重建，正常返回到分享页

**Comment by sinaweibosdk** [comment]
已经解决，在下个版本上体现。
