### ISSUE TITLE
微博分享时，http协议明文传输用户个人数据

### ISSUE THREAD

**Issue by HiMovie** [sinaweibosdk/weibo_android_sdk#536]
![20200710-153354(WeLinkPC)](https://user-images.githubusercontent.com/58999859/87128963-2433b080-c2c3-11ea-858f-ea5fea0907e5.png)

上述接口，使用http协议明文传输，上传数据中包含mac地址等个人数据。
请问微博sdk有整改计划吗？

**Comment by sinaweibosdk** [comment]
请问这个是用的哪个版本？
