### ISSUE TITLE
Web（H5）分享时，图片分享不出去

### ISSUE THREAD

**Issue by MrZhaobh** [sinaweibosdk/weibo_android_sdk#538]
使用最新的v10.7.0分享单图时，已经初始化，也进行过web授权，但是分享时一直会提示“分享失败：图片内容不合适，禁止上传”。
这里图片有大小的限制还是什么别的限制，我看demo中使用的图片是952KB的，我换了一张7KB的图 同样也无法分享？？

**Comment by yutfa** [comment]
我也是这个问题，应该不是大小问题，是安卓系统版本适配问题，11以上
