### ISSUE TITLE
为何api中没有WeiboAuth这个类

### ISSUE THREAD

**Issue by Dorothy00** [sinaweibosdk/weibo_android_sdk#54]
3.0.0的文档里说明的授权方法要用到WeiboAuth这个类,但是api里根本没有这个类,是为什么呢?  还是说这个类在新版sdk中已经移除了?  那要用何种方式授权呢(非sso)

**Comment by 0xC000005** [comment]
我也遇到这个了。。

**Comment by pkliang** [comment]
AuthInfo
