### ISSUE TITLE
FileProvider Uri 文件分享失败

### ISSUE THREAD

**Issue by amd110** [sinaweibosdk/weibo_android_sdk#541]
为了适配Android N 以上版本目录权限问题，在创建Uri 时使用 FileProvider.getUriForFile(context, context.getPackageName() + ".fileprovider", file); 方法分享视频文件时报错。而直接使用 Uri.fromFile方法则正常
fileUri = content://xxx(PackageName).fileprovider/external_storage_root/download/faceMagic.mp4
系统版本： Android 7.0
SDK 版本：10.7.0

java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:358)
System.err:     at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
System.err:     at com.sina.weibo.sdk.c.b.a(SourceFile:168)
System.err:     at com.sina.weibo.sdk.c.b.c(SourceFile:138)
System.err:     at com.sina.weibo.sdk.c.b.b(SourceFile:36)
System.err:     at com.sina.weibo.sdk.share.d.a(SourceFile:72)
System.err:     at com.sina.weibo.sdk.share.d.doInBackground(SourceFile:16)
System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
System.err:     at java.lang.Thread.run(Thread.java:919)

**Comment by lu-xu** [comment]
现在还不支持FileProvider吗？

**Comment by amd110** [comment]
> 现在还不支持FileProvider吗？

都没人维护了，一堆的问题百年不更新了
