### ISSUE TITLE
魅族4，打开WeiboSdkBrowser这个Activity是报如下错误，导致回调推出应用

### ISSUE THREAD

**Issue by wangxf103435** [sinaweibosdk/weibo_android_sdk#55]
01-30 16:29:00.732: E/ActivityThread(10221): Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked ServiceConnection com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$Connection@43257d60 that was originally bound here
01-30 16:29:00.732: E/ActivityThread(10221): android.app.ServiceConnectionLeaked: Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked ServiceConnection com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$Connection@43257d60 that was originally bound here
01-30 16:29:00.732: E/ActivityThread(10221):    at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1009)
01-30 16:29:00.732: E/ActivityThread(10221):    at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:903)
01-30 16:29:00.732: E/ActivityThread(10221):    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1718)
01-30 16:29:00.732: E/ActivityThread(10221):    at android.app.ContextImpl.bindService(ContextImpl.java:1701)
01-30 16:29:00.732: E/ActivityThread(10221):    at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
01-30 16:29:00.732: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient.doBindService(SelfBrailleClient.java:125)
01-30 16:29:00.732: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient.access$1000(SelfBrailleClient.java:43)
01-30 16:29:00.732: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$SelfBrailleHandler.handleRebindService(SelfBrailleClient.java:260)
01-30 16:29:00.732: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$SelfBrailleHandler.handleMessage(SelfBrailleClient.java:245)
01-30 16:29:00.732: E/ActivityThread(10221):    at android.os.Handler.dispatchMessage(Handler.java:110)
01-30 16:29:00.732: E/ActivityThread(10221):    at android.os.Looper.loop(Looper.java:193)
01-30 16:29:00.732: E/ActivityThread(10221):    at android.app.ActivityThread.main(ActivityThread.java:5332)
01-30 16:29:00.732: E/ActivityThread(10221):    at java.lang.reflect.Method.invokeNative(Native Method)
01-30 16:29:00.732: E/ActivityThread(10221):    at java.lang.reflect.Method.invoke(Method.java:515)
01-30 16:29:00.732: E/ActivityThread(10221):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
01-30 16:29:00.732: E/ActivityThread(10221):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
01-30 16:29:00.732: E/ActivityThread(10221):    at dalvik.system.NativeStart.main(Native Method)
01-30 16:29:00.738: E/ActivityThread(10221): Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked ServiceConnection com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$Connection@43a280d8 that was originally bound here
01-30 16:29:00.738: E/ActivityThread(10221): android.app.ServiceConnectionLeaked: Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked ServiceConnection com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$Connection@43a280d8 that was originally bound here
01-30 16:29:00.738: E/ActivityThread(10221):    at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1009)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:903)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1718)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.app.ContextImpl.bindService(ContextImpl.java:1701)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient.doBindService(SelfBrailleClient.java:125)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient.<init>(SelfBrailleClient.java:99)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.accessibility.AccessibilityInjector$TextToSpeechWrapper.<init>(AccessibilityInjector.java:399)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.accessibility.AccessibilityInjector.addAccessibilityApis(AccessibilityInjector.java:278)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.accessibility.JellyBeanAccessibilityInjector.addAccessibilityApis(JellyBeanAccessibilityInjector.java:86)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.accessibility.AccessibilityInjector.addOrRemoveAccessibilityApisIfNecessary(AccessibilityInjector.java:160)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.ContentViewCore.setInjectedAccessibility(ContentViewCore.java:2995)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.ContentViewCore.setAccessibilityState(ContentViewCore.java:2986)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.ContentViewCore.onAttachedToWindow(ContentViewCore.java:1528)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.org.chromium.android_webview.AwContents.onAttachedToWindow(AwContents.java:1729)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.webview.chromium.WebViewChromium.onAttachedToWindow(WebViewChromium.java:1781)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.webkit.WebView.onAttachedToWindow(WebView.java:2133)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.View.dispatchAttachedToWindow(View.java:13163)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2613)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2620)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2620)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2620)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2620)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1780)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6951)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.Choreographer.doCallbacks(Choreographer.java:591)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.Choreographer.doFrame(Choreographer.java:560)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.os.Handler.handleCallback(Handler.java:808)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.os.Handler.dispatchMessage(Handler.java:103)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.os.Looper.loop(Looper.java:193)
01-30 16:29:00.738: E/ActivityThread(10221):    at android.app.ActivityThread.main(ActivityThread.java:5332)
01-30 16:29:00.738: E/ActivityThread(10221):    at java.lang.reflect.Method.invokeNative(Native Method)
01-30 16:29:00.738: E/ActivityThread(10221):    at java.lang.reflect.Method.invoke(Method.java:515)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
01-30 16:29:00.738: E/ActivityThread(10221):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
01-30 16:29:00.738: E/ActivityThread(10221):    at dalvik.system.NativeStart.main(Native Method)
01-30 16:29:00.740: E/ActivityThread(10221): Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked ServiceConnection com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$Connection@44c02670 that was originally bound here
01-30 16:29:00.740: E/ActivityThread(10221): android.app.ServiceConnectionLeaked: Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked ServiceConnection com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$Connection@44c02670 that was originally bound here
01-30 16:29:00.740: E/ActivityThread(10221):    at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1009)
01-30 16:29:00.740: E/ActivityThread(10221):    at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:903)
01-30 16:29:00.740: E/ActivityThread(10221):    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1718)
01-30 16:29:00.740: E/ActivityThread(10221):    at android.app.ContextImpl.bindService(ContextImpl.java:1701)
01-30 16:29:00.740: E/ActivityThread(10221):    at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
01-30 16:29:00.740: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient.doBindService(SelfBrailleClient.java:125)
01-30 16:29:00.740: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient.access$1000(SelfBrailleClient.java:43)
01-30 16:29:00.740: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$SelfBrailleHandler.handleRebindService(SelfBrailleClient.java:260)
01-30 16:29:00.740: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$SelfBrailleHandler.handleMessage(SelfBrailleClient.java:245)
01-30 16:29:00.740: E/ActivityThread(10221):    at android.os.Handler.dispatchMessage(Handler.java:110)
01-30 16:29:00.740: E/ActivityThread(10221):    at android.os.Looper.loop(Looper.java:193)
01-30 16:29:00.740: E/ActivityThread(10221):    at android.app.ActivityThread.main(ActivityThread.java:5332)
01-30 16:29:00.740: E/ActivityThread(10221):    at java.lang.reflect.Method.invokeNative(Native Method)
01-30 16:29:00.740: E/ActivityThread(10221):    at java.lang.reflect.Method.invoke(Method.java:515)
01-30 16:29:00.740: E/ActivityThread(10221):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
01-30 16:29:00.740: E/ActivityThread(10221):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
01-30 16:29:00.740: E/ActivityThread(10221):    at dalvik.system.NativeStart.main(Native Method)
01-30 16:29:00.742: E/ActivityThread(10221): Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@454886b0 that was originally bound here
01-30 16:29:00.742: E/ActivityThread(10221): android.app.ServiceConnectionLeaked: Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@454886b0 that was originally bound here
01-30 16:29:00.742: E/ActivityThread(10221):    at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1009)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:903)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1718)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.app.ContextImpl.bindService(ContextImpl.java:1701)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.speech.tts.TextToSpeech.connectToEngine(TextToSpeech.java:687)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:657)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:610)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:584)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.accessibility.AccessibilityInjector$TextToSpeechWrapper.<init>(AccessibilityInjector.java:398)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.accessibility.AccessibilityInjector.addAccessibilityApis(AccessibilityInjector.java:278)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.accessibility.JellyBeanAccessibilityInjector.addAccessibilityApis(JellyBeanAccessibilityInjector.java:86)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.accessibility.AccessibilityInjector.addOrRemoveAccessibilityApisIfNecessary(AccessibilityInjector.java:160)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.ContentViewCore.setInjectedAccessibility(ContentViewCore.java:2995)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.ContentViewCore.setAccessibilityState(ContentViewCore.java:2986)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.org.chromium.content.browser.ContentViewCore.onAttachedToWindow(ContentViewCore.java:1528)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.org.chromium.android_webview.AwContents.onAttachedToWindow(AwContents.java:1729)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.webview.chromium.WebViewChromium.onAttachedToWindow(WebViewChromium.java:1781)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.webkit.WebView.onAttachedToWindow(WebView.java:2133)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.View.dispatchAttachedToWindow(View.java:13163)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2613)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2620)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2620)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2620)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2620)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1780)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6951)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.Choreographer.doCallbacks(Choreographer.java:591)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.Choreographer.doFrame(Choreographer.java:560)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.os.Handler.handleCallback(Handler.java:808)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.os.Handler.dispatchMessage(Handler.java:103)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.os.Looper.loop(Looper.java:193)
01-30 16:29:00.742: E/ActivityThread(10221):    at android.app.ActivityThread.main(ActivityThread.java:5332)
01-30 16:29:00.742: E/ActivityThread(10221):    at java.lang.reflect.Method.invokeNative(Native Method)
01-30 16:29:00.742: E/ActivityThread(10221):    at java.lang.reflect.Method.invoke(Method.java:515)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
01-30 16:29:00.742: E/ActivityThread(10221):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
01-30 16:29:00.742: E/ActivityThread(10221):    at dalvik.system.NativeStart.main(Native Method)
01-30 16:29:00.743: E/ActivityThread(10221): Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked ServiceConnection com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$Connection@459087a8 that was originally bound here
01-30 16:29:00.743: E/ActivityThread(10221): android.app.ServiceConnectionLeaked: Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked ServiceConnection com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$Connection@459087a8 that was originally bound here
01-30 16:29:00.743: E/ActivityThread(10221):    at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1009)
01-30 16:29:00.743: E/ActivityThread(10221):    at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:903)
01-30 16:29:00.743: E/ActivityThread(10221):    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1718)
01-30 16:29:00.743: E/ActivityThread(10221):    at android.app.ContextImpl.bindService(ContextImpl.java:1701)
01-30 16:29:00.743: E/ActivityThread(10221):    at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
01-30 16:29:00.743: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient.doBindService(SelfBrailleClient.java:125)
01-30 16:29:00.743: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient.access$1000(SelfBrailleClient.java:43)
01-30 16:29:00.743: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$SelfBrailleHandler.handleRebindService(SelfBrailleClient.java:260)
01-30 16:29:00.743: E/ActivityThread(10221):    at com.android.org.chromium.com.googlecode.eyesfree.braille.selfbraille.SelfBrailleClient$SelfBrailleHandler.handleMessage(SelfBrailleClient.java:245)
01-30 16:29:00.743: E/ActivityThread(10221):    at android.os.Handler.dispatchMessage(Handler.java:110)
01-30 16:29:00.743: E/ActivityThread(10221):    at android.os.Looper.loop(Looper.java:193)
01-30 16:29:00.743: E/ActivityThread(10221):    at android.app.ActivityThread.main(ActivityThread.java:5332)
01-30 16:29:00.743: E/ActivityThread(10221):    at java.lang.reflect.Method.invokeNative(Native Method)
01-30 16:29:00.743: E/ActivityThread(10221):    at java.lang.reflect.Method.invoke(Method.java:515)
01-30 16:29:00.743: E/ActivityThread(10221):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
01-30 16:29:00.743: E/ActivityThread(10221):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
01-30 16:29:00.743: E/ActivityThread(10221):    at dalvik.system.NativeStart.main(Native Method)

**Comment by RockyLin** [comment]
魅族...之前也是用这个。
