### ISSUE TITLE
FileProvider的name和authorities名称都太通用了

### ISSUE THREAD

**Issue by ncmonl** [sinaweibosdk/weibo_android_sdk#552]
FileProvider的name和authorities名称都太通用了，太容易和其他SDK冲突，建议使用继承FileProvider的方式，并且authorities也命名为一个特别一点的方便接入一些。

**Comment by sinyu1012** [comment]
+1

**Comment by OstAlex** [comment]
+2

**Comment by z2058550226** [comment]
+10086 估计大伙都遇到manifest merge错误了。推荐官方看下[https://stackoverflow.com/questions/42893846/androidmanifest-merge-error-using-fileprovider](这个)

**Comment by shenghaiyang** [comment]
+1
