### ISSUE TITLE
麻烦加上隐私收集信息和相关权限

### ISSUE THREAD

**Issue by rosuH** [sinaweibosdk/weibo_android_sdk#553]
近期监管部门对第三方 SDK 的检查有所收紧，需要提供相关 SDK 权限以及收集的信息。其他公司的 SDK 都有明确的隐私协议和相关说明，但是贵司这个 SDK 并没有。希望能快点加上，方便使用者披露。

相关链接：[关于35款App存在个人信息收集使用问题的通告](https://mp.weixin.qq.com/s/KGFSSM9yuIxs9Wrv2tR24w)

**Comment by GstXu** [comment]
收集到了吗 兄弟 最近我也需要这方面信息

**Comment by rosuH** [comment]
> 收集到了吗 兄弟 最近我也需要这方面信息

没有。可以去看看市面上其他使用了这个 SDK 的厂商是怎么写的。

**Comment by GstXu** [comment]
> > 收集到兄弟最近我也需要这方面信息
> 
> 没有。可以去看看其他用了SDK的厂家是怎么写的。

嗯看到友盟的了...  太难了
