### ISSUE TITLE
【严重】不在ExternalFilesDir内的图片不能通过Uri分享！

### ISSUE THREAD

**Issue by OstAlex** [sinaweibosdk/weibo_android_sdk#556]
com.sina.weibo.sdk.utils.FileUtil#getRealFilePath 的实现有问题。
一般分享图不会放在file里面，放在cache文件夹里面的情况比较多。

这样会导致com.sina.weibo.sdk.utils.FileUtil#isImageFile出问题。

建议通过ContentResolver获取uri的DisplayName或者ParcelFileDescriptor。来判断该Uri是否是图片。

**Comment by kongxiaojun** [comment]
看起来是这段代码的问题，com.sina.weibo.sdk.c.b
    public static String d(Context context, Uri uri) {
        String uri2 = uri.toString();
        return new File(context.getExternalFilesDir((String) null), uri2.substring(uri2.lastIndexOf("/"))).getAbsolutePath();
    }
