### ISSUE TITLE
WebpageObject 分享 分享成功后，无法看到传过去的title，description ，url

### ISSUE THREAD

**Issue by yanglee0801** [sinaweibosdk/weibo_android_sdk#564]
WeiboMultiMessage message = new WeiboMultiMessage();
        WebpageObject webpageObject = new WebpageObject();
        webpageObject.identify = Utility.generateGUID();
        webpageObject.description = defaultText;
        webpageObject.defaultText = defaultText;
        webpageObject.actionUrl = url;
        webpageObject.title = title;
        webpageObject.setThumbImage(bitmap);
        message.mediaObject = webpageObject;
        shareHandler.shareMessage(message, false);

分享成功后，仅能看到用户本身输入的文案，其他的都不可见

**Comment by zhangyujiu** [comment]
请问解决了吗，我也是这个问题
