### ISSUE TITLE
Oauth2AccessToken parseAccessToken() : java.lang.NumberFormatException

### ISSUE THREAD

**Issue by brian512** [sinaweibosdk/weibo_android_sdk#570]
![image](https://user-images.githubusercontent.com/6830867/106558401-9d943880-655e-11eb-9d6c-9aea8badb057.png)
![image](https://user-images.githubusercontent.com/6830867/106558492-cd434080-655e-11eb-9203-5a91d8bf1b56.png)

**Comment by solochen** [comment]
我这出现一样的问题，看微博的代码try catch了，实际场景是不会造成APP崩溃，但异常信息还是会上报给bugly

**Comment by JasonKid** [comment]
吐了。
用的是com.sina.weibo.sdk:core:10.11.0这个版本的SDK
不用在onActivityResult进行mWBAPI.authorizeCallback，就不会报错
而且之前注册的onComplete回调仍然会进行。

浪费我几个小时，为什么没有文档啊啊啊啊啊啊

**Comment by solochen** [comment]
微博的大哥们这个问题能不能尽快修一修啊，真是要人命~~

**Comment by brian512** [comment]
把aar里的这个工具类替换掉

https://blog.csdn.net/ifmvo/article/details/85791614

**Comment by solochen** [comment]
11.6.0终于修复啦~

**Comment by jimmysuncpt** [comment]
> 11.6.0终于修复啦~

![wecom-temp-efd16213fed63c216e9562393e00cc58](https://user-images.githubusercontent.com/20553676/134669776-72e428ba-98bb-4da8-b2ed-2f117e45db53.png)

代码还有 bug，压根就没有修复，还给 catch 住了。。。
