### ISSUE TITLE
微博APP在新设备上登录后，微博SDK Demo进行授权登录会报empty access token

### ISSUE THREAD

**Issue by MrLiu199** [sinaweibosdk/weibo_android_sdk#572]
现象：微博APP在新设备上登录时，会触发短信验证，验证登录成功后，微博SDK Demo进行授权登录时会报empty access token。
微博SDK版本：10.10.0
另外：重启微博APP再重新授权登录可解决问题，但是体验不好，麻烦解决一下。

**Comment by winxinxinxin** [comment]
同遇此问题 。10.10.0版本
