### ISSUE TITLE
使用目前最新的SDK仍会导致编译目标平台为安卓12的app无法在安卓12系统上安装

### ISSUE THREAD

**Issue by ForgottenR** [sinaweibosdk/weibo_android_sdk#573]
以安卓12为目标平台编译且使用目前最新的SDK，在安卓12模拟器上仍然无法安装app，logcat报错

> 2021-03-14 06:26:12.411 525-577/? W/PackageManager: Failed parse during installPackageLI: /data/app/vmdl2065532058.tmp/base.apk (at Binary XML file line #142): com.sina.weibo.sdk.share.ShareResultActivity: Targeting S+ (version 10000 and above) requires that an explicit value for android:exported be defined when intent filters are present

这是在该SDK中注册的activity导致的问题，是安卓12的行为变化导致的结果，麻烦开发者尽快适配安卓12。
在此附上相关资料：
https://developer.android.com/about/versions/12/behavior-changes-12#exported

**Comment by FOnlyJack** [comment]
> ShareResultActivity
自己临时编辑下aar清单文件代码 我也遇到这问题了
