### ISSUE TITLE
Android Studio 使用微博SDK Demo的问题总结

### ISSUE THREAD

**Issue by RockyLin** [sinaweibosdk/weibo_android_sdk#58]
weibo SDK 用Eclipse导入之后，将debug.keystore配置好，然后可以正常地分享。但是从Eclipse迁移到Android Studio会有一些问题：
1.用Eclipse导出build.gradle;
2.用Android Studio import non-Android Studio project. 完成之后会提示plugin版本太低，根据提示升级。
3.之后会报告说有几个图片不是png格式的。但是一看后缀，确实是png格式的。可能图片之前是jpg格式的，转格式的时候出了点问题（奇怪的是Eclipse没有报错）。解决办法：把报错的图片重新处理成png格式。
4.好了之后试着再运行会报.9.png错误。把报错的图片重新用Android Studio自带的.9图片处理功能处理一下（奇怪的是Eclipse也没报这个问题，难着Android Studiio的检查功能增强了？）。
5.然后应该可以正常运行了吧... 还没有....再运行会报找不class之类的问题（这个错误当时没有记录，抱歉）。后来查看了github上的Issues问题列表，又问了微博SDK群的管理员KissOF LoVe，可能是jni库没有配置好。在Elipse里是能够正常运行的， 到了Android Studio之后就有问题了。Google了一下，发现在Android Studio中需要自己设置路径。我把"ameabi, mips, x86"这几个文件夹放在libs文件夹下， 所以在WeiboSDKDemo的build.gradle文件中， 加了一行  jniLibs.srcDirs = ['libs']， 指明了jni库放在libs下面（如果是放在新建的文件夹中，后面的‘libs'需要换成那个文件夹的名字。这一行加的位置在android->sourceSets->main下面。那里定义了java.srcDirs, resources.srcDirs等路径（导入Android Studio时自动生成的）
6.找不到Class的问题消失了，应该好了吧...结果又报了multi-dex...这个问题，github Issues早就有人提出了解决方案，KissOF LoVe也确认了解决方案：WeiboSDK工程下的libs下面有个weibosdkcore.jar.用rar直接打开，找到com/sina/weibo/sdk/BuildConfig 把这个类手动删了.（windows下的rar是直接可以打开jar包，而不用改后缀，保存之后，后缀还是jar. 我试了用Mac 把缀改成zip, 解压处理完后之后再压成zip， 改为jar，但是jar里面多了一下MacOS_的文件夹，放到demo里面运行报错。可能我的方法有问题。最后用windows 修改了jar包)。 
7.到此编译问题解决，可以成功运行。但是还不能分享。因为debug.keystore还没有设置，默认的debug运行模式下安装的apk是不能分享，会提示sso package error. 解决办法：在android studio中打开project structure, 选中Modules下面的WeiboSDKDemo, 再点击右边的signing, 在Store File中设置好WeiboSDK文件夹中的debug.keystore(下载的weibo_android_sdk文件里就有）.
至此问题解决。以上办法是本人在操作过程中遇到的问题，仅供参考。感谢KissOF LoVe，qq群新浪微博AndroidSDK，github上各位提供问题解决办法的人帮助。

**Comment by geeksammao** [comment]
点赞！解决了我的问题

**Comment by CoderHanXin** [comment]
非常感谢，参考你的总结，我终于把项目跑起来了。
我上传了一份 Android Studio 的 WeiboSdkDemo：https://github.com/CoderHanXin/WeiboSdkDemo

**Comment by yongjhih** [comment]
See also:

* https://github.com/8tory/weibo-android-sdk
* https://github.com/8tory/weibo-android-sdk-core

**Comment by DerekAndroid** [comment]
many thanks
