### ISSUE TITLE
mave库不能下载，报错403

### ISSUE THREAD

**Issue by flutter-youni** [sinaweibosdk/weibo_android_sdk#581]
Could not HEAD 'https://dl.bintray.com/thelasterstar/maven/com/sina/weibo/sdk/core/4.2.7/core-4.2.7.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project

**Comment by WangStormstout** [comment]
+1

**Comment by 323daibiao** [comment]
建议迁移AAR到公司maven仓库

**Comment by OtherSun** [comment]
新浪sdk估计都没人维护了，jcenter关闭都不提前更新这块

**Comment by sohnyi** [comment]
有人解决这个问题了吗？

**Comment by Be90nia** [comment]
有其他源可以使用么?

**Comment by OtherSun** [comment]
![Uploading 微信图片编辑_20210508163423.jpg…]()

**Comment by WangStormstout** [comment]
我使用了aar

**Comment by jiangwenbin** [comment]
+1,谁有maven可以共享下吗

**Comment by sohnyi** [comment]
> 我使用了aar

暂时使用了 aar 进行编译，但是其他小伙伴之前都下载下来了，不清楚后面团队如何处理

**Comment by james602152002** [comment]
jcenter跑路后麻烦的要命，
好多依赖都要一个个找。。。

**Comment by blindmonk** [comment]
+1

**Comment by Edward-going** [comment]
对啊，md这是个问题

**Comment by shirensong** [comment]
> > 我使用了aar
> 
> 暂时使用了 aar 进行编译，但是其他小伙伴之前都下载下来了，不清楚后面团队如何处理

请问你是怎么编译通过的？我这边出现这样的错误：

   > Failed to transform openDefault-4.4.4-.aar (:openDefault-4.4.4:) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=integration}.
      > Execution failed for AarResourcesCompilerTransform: .gradle/caches/transforms-2/files-2.1/69b1312954fc8fa6bee580275121edf9/openDefault-4.4.4.
         > .gradle/caches/transforms-2/files-2.1/69b1312954fc8fa6bee580275121edf9/openDefault-4.4.4/AndroidManifest.xml

**Comment by xx-li** [comment]
谁有maven可以共享下吗？

**Comment by lijunghua** [comment]
+1

**Comment by bailiangjin** [comment]
+1

**Comment by renhuan** [comment]
+1

**Comment by gdoudeng** [comment]
+1

**Comment by good-good-study** [comment]
可以将官网的.aar文件放在Jitpack仓库里，： https://jitpack.io/#good-good-study/SinaWeiboSdk/10.10.0

**Comment by shirensong** [comment]
> 可以将官网的.aar文件放在Jitpack仓库里，： https://jitpack.io/#good-good-study/SinaWeiboSdk/10.10.0

 > Could not resolve com.github.good-good-study:SinaWeiboSdk:10.10.0.
         > Could not parse POM https://jitpack.io/com/github/good-good-study/SinaWeiboSdk/10.10.0/SinaWeiboSdk-10.10.0.pom
            > Missing required attribute: dependency groupId

**Comment by good-good-study** [comment]
我也遇到了同样的情况，现在https://www.jitpack.io 和&nbsp;https://jitpack.io 都不能正常下载。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sinaweibosdk/weibo_android_sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 中午11:04
***@***.***&gt;;
抄送:&nbsp;"⑨⑨ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [sinaweibosdk/weibo_android_sdk] mave库不能下载，报错403 (#581)





  
可以将官网的.aar文件放在Jitpack仓库里，： https://jitpack.io/#good-good-study/SinaWeiboSdk/10.10.0
   
Could not resolve com.github.good-good-study:SinaWeiboSdk:10.10.0.
 &gt; Could not parse POM https://jitpack.io/com/github/good-good-study/SinaWeiboSdk/10.10.0/SinaWeiboSdk-10.10.0.pom
 &gt; Missing required attribute: dependency groupId

**Comment by shirensong** [comment]
> 可以将官网的.aar文件放在Jitpack仓库里，： https://jitpack.io/#good-good-study/SinaWeiboSdk/10.10.0

你好，我遇到这个问题：
  > Could not resolve com.github.good-good-study:SinaWeiboSdk:10.10.0.
         > Could not parse POM https://jitpack.io/com/github/good-good-study/SinaWeiboSdk/10.10.0/SinaWeiboSdk-10.10.0.pom
            > Missing required attribute: dependency groupId

**Comment by good-good-study** [comment]
整了一天，终于把.aar放在了maven上面，奶奶的，大家可以安心使用了，10.10.1的版本对应的就是 新浪微博官方10.10.0 

AndroidStudio build.gradle 添加依赖即可：
//新浪微博sdk
implementation 'io.github.good-good-study:sina-weibo-sdk:10.10.1'

**Comment by good-good-study** [comment]
整了一天，终于把.aar放在了maven上面，奶奶的，大家可以安心使用了，10.10.1的版本对应的就是 新浪微博官方10.10.0




AndroidStudio build.gradle 添加依赖即可：
//新浪微博sdk
implementation 'io.github.good-good-study:sina-weibo-sdk:10.10.1'

































------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sinaweibosdk/weibo_android_sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 中午11:18
***@***.***&gt;;
抄送:&nbsp;"⑨⑨ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [sinaweibosdk/weibo_android_sdk] mave库不能下载，报错403 (#581)





  
可以将官网的.aar文件放在Jitpack仓库里，： https://jitpack.io/#good-good-study/SinaWeiboSdk/10.10.0
  
你好，我遇到这个问题：
  
Could not resolve com.github.good-good-study:SinaWeiboSdk:10.10.0.
 &gt; Could not parse POM https://jitpack.io/com/github/good-good-study/SinaWeiboSdk/10.10.0/SinaWeiboSdk-10.10.0.pom
 &gt; Missing required attribute: dependency groupId

**Comment by good-good-study** [comment]
> +1,谁有maven可以共享下吗

AndroidStudio build.gradle 添加依赖即可：
//新浪微博sdk
implementation 'io.github.good-good-study:sina-weibo-sdk:10.10.1'

**Comment by wangwei66666** [comment]
能不能换个仓库啊，这么大一公司

**Comment by wangwei66666** [comment]
maven弄一下历史版本啊，这么大一公司
