### ISSUE TITLE
分享，登录，回调出错

### ISSUE THREAD

**Issue by xym5809** [sinaweibosdk/weibo_android_sdk#585]
分享成功后，留在微博，然后将微博退到后台，进入自己的app ,会提示分享已取消，

登录：如果微博处于未登录状态，然后在自己的app点击第三方登录，选择微博，在微博登录页面输入账号密码，会一直停留在登录页面，无其他反应。

版本 10.7.0/10.8.0

**Comment by woying456** [comment]
我也复现了，我用的10.9.0
