### ISSUE TITLE
请适配Android11啊啊啊啊啊啊

### ISSUE THREAD

**Issue by yswheye** [sinaweibosdk/weibo_android_sdk#588]
targetSdkVersion改成30，demo都分享不了。Android11无法分享图片。
需要通过uri来分享，请适配啊。
微博是没人开发了么，好多年不更新了。。。。。。。

**Comment by Yexi** [comment]
可以分享，在清单文件添加    
    

        <queries>    
                
            <package android:name="com.sina.weibo" />    
        </queries>

**Comment by yswheye** [comment]
不行的，小图片转imageData是可以 没问题。但是大图需要通过FileProvider uri来分享，目前还不支持

**Comment by 378063465** [comment]
是啊 ImageObject  getFileSize 没有判断 startWith("content")完全没支持， FileProvider , 而且感觉11.8 sdk 代码这么像微信呢【doge】

**Comment by ChuckSuperBB** [comment]
> 不行的，小图片转imageData是可以 没问题。但是大图需要通过FileProvider uri来分享，目前还不支持

setImagePath 走本地图片

**Comment by yswheye** [comment]
> > 不行的，小图片转imageData是可以 没问题。但是大图需要通过FileProvider uri来分享，目前还不支持
> 
> setImagePath 走本地图片

也不太行啊，因为filepath是uri

**Comment by yswheye** [comment]
应该像微信的api一样imageObject.imagePath = uri就支持的
