### ISSUE TITLE
 Start weibo client's composer fail. please init sdk before use it. Wb.install()

### ISSUE THREAD

**Issue by yangqingyuan** [sinaweibosdk/weibo_android_sdk#594]
调用微博分享接口的时候会出现这个错误（ Start weibo client's composer fail. please init sdk before use it. Wb.install()）
（1）10.10.0版本不会出现
（2）11.6.0版本出现
（3）出现的条件是微博不在后台运行的情况下（杀进程情况下），调用微博分享

求解救办法！！！

**Comment by ldk123456** [comment]
我也遇到这个情况了，我这边不是微博不在后台运行的情况下触发，是第一次分享的时候出现的。
![69121AC7-31CF-4EDE-9F79-BA50AC687B0C](https://user-images.githubusercontent.com/37365717/125609490-4612db5a-c6b7-498e-b69b-238457f4a356.png)
感觉是这个地方使用线程的问题，标志位a没有及时改为true

**Comment by firzencode** [comment]
升级以后，遇到了同一个问题。
APP 启动的时候预初始化一下 weibo sdk 应该就好了，可以试一下。

**Comment by WcombL** [comment]
> 升级以后，遇到了同一个问题。
> APP 启动的时候预初始化一下 weibo sdk 应该就好了，可以试一下。

你好，请问怎么初始化 sdk。我没有找到Wb.install()在那里。我用的是11.6.0版本

**Comment by jokerwangw** [comment]
各位大佬好，请问最后问题解决了吗？

**Comment by good-good-study** [comment]
@jsyangboy 在调用分享操作的之前，延迟一小会儿调用就好了，新浪微博sdk真是坑啊。

**Comment by duning1204** [comment]
确实，在启动首页的时候，先初始化新浪微博，后续再调用分享才没问题，真的垃圾的一批

**Comment by good-good-study** [comment]
> 确实，在启动首页的时候，先初始化新浪微博，后续再调用分享才没问题，真的垃圾的一批

我现在已经改用了4.4.4的版本了😂

**Comment by 378063465** [comment]
本来想把registerApp放到 application ,还限制 context 必须是 activity ， 垃圾垃圾垃圾

**Comment by SamiuZhong** [comment]
找到解决方案了，init sdk之后延迟一下再申请授权
`
runBlocking {
    delay(400)
}
`

**Comment by yiranshaxiao** [comment]
在主Activity提前初始化，伪代码
```
IWBAPI api = WBAPIFactory.createWBAPI(activity);
AuthInfo authInfo = new AuthInfo(***);
api.registerApp(activity.getApplicationContext(), authInfo);
```

**Comment by bruce3x** [comment]
```kotlin
wbApi.registerApp(context, authInfo, object : SdkListener {
    override fun onInitSuccess() {
        initSuccess = true
    }

    override fun onInitFailure(p0: Exception?) {
    }

})
```

测试下来，在 `onInitSuccess()` 之后去调用授权或者分享就没问题了 👀
