### ISSUE TITLE
v11.6.0授权时Oauth2AccessToken的mExpiresTime为0，isSessionValid()返回false

### ISSUE THREAD

**Issue by ChengJiee** [sinaweibosdk/weibo_android_sdk#603]
v11.6.0授权，WbAuthListener回调onComplete，Oauth2AccessToken的mUid和mAccessToken都正常，但是mExpiresTime为0，isSessionValid()返回false。

**Comment by zhangxueqiang** [comment]
Oauth2AccessToken.class
public static Oauth2AccessToken parseAccessToken(Bundle var0) {
if (var0 != null) {
try {
Oauth2AccessToken var1;
(var1 = new Oauth2AccessToken()).setUid(var0.getString("uid"));
var1.setScreenName(var0.getString("userName"));
var1.setAccessToken(var0.getString("access_token"));
var1.setRefreshToken(var0.getString("refresh_token"));
String var5 = var0.getString("expires_in");
long var2 = 0L;
if (**TextUtils.isEmpty(var5)**) { ---> 这里应该取非操作， if (!TextUtils.isEmpty(var5)) {
var2 = Long.parseLong(var5) * 1000L;
}

            var1.setExpiresTime(var2);
            return var1;
        } catch (Exception var4) {
            var4.printStackTrace();
        }
    }
    return null;
}

**Comment by huopochuan** [comment]
+1 降级为10.10.0版本

**Comment by huopochuan** [comment]
发现授权后无法分享文本和图片

**Comment by huopochuan** [comment]
授权权可以正常分享文本和图片
