### ISSUE TITLE
（8998）文件不存在

### ISSUE THREAD

**Issue by GstXu** [sinaweibosdk/weibo_android_sdk#605]
更新最新sdk 11.6版本
调用分享shareMessage方法 分享到微博  发送页面， 点击发送分享，提示（8998）文件不存在 ， 分享失败！

**Comment by GstXu** [comment]
appkey、MD5啥的理论上都不需要修改把 ，只是更新了sdk版本

**Comment by GstXu** [comment]
已解决
老版本分享文字+图片+网页时， 网页分享对象里没有给webObject.thumbData赋值是可以分享的
11.6版本必须给webObject.thumbData复制，否则报8998

**Comment by JadeWu233** [comment]
想请问您用最新的11.6.0的时候，.so文件是按照他分享的libwind.so、libweibosdkcore.so、libutility.so这些吗，有没有提示需要新的libsharewind.so之类的，谢谢

**Comment by GstXu** [comment]
> 想请问您用最新的11.6.0的，.so文件的时候是按照他分享的libwind.so、libweibosdkcore.so、libutility.so这些吗，有没有提示需要新的libsharewind.so之类的，谢谢

没有添加so文件

**Comment by WANZIzZ** [comment]
赋值是给图标，还是给分享的图片？

**Comment by WANZIzZ** [comment]
如果分享的有图片，可以参考 ImageObject().setImageData 这个方法，获取一个 ByteArray ，然后赋值给 webObject.thumbData ，否则可以使用应用图标，获取 ByteArray 后，赋值给 webObject.thumbData
