### ISSUE TITLE
oauth2AccessToken.isSessionValid()返回false

### ISSUE THREAD

**Issue by zhangxueqiang** [sinaweibosdk/weibo_android_sdk#607]
通过调试发现是微博SDK11.6.0 写错了代码
Oauth2AccessToken.class
 public static Oauth2AccessToken parseAccessToken(Bundle var0) {
        if (var0 != null) {
            try {
                Oauth2AccessToken var1;
                (var1 = new Oauth2AccessToken()).setUid(var0.getString("uid"));
                var1.setScreenName(var0.getString("userName"));
                var1.setAccessToken(var0.getString("access_token"));
                var1.setRefreshToken(var0.getString("refresh_token"));
                String var5 = var0.getString("expires_in");
                long var2 = 0L;
                if (TextUtils.isEmpty(var5)) { ---> 这里应该取非操作， if (!TextUtils.isEmpty(var5)) { 
                    var2 = Long.parseLong(var5) * 1000L;
                }

                var1.setExpiresTime(var2);
                return var1;
            } catch (Exception var4) {
                var4.printStackTrace();
            }
        }
        return null;
    }
以上代码错误导致使用oauth2AccessToken.isSessionValid()时，返回false, 错误的返回accessToken已经失效。

**Comment by dodatw** [comment]
这个低级的错误官方啥时会解决 ? 我也遇到了

**Comment by shomin1983** [comment]
11.6.0 发生的低级错误，11.8.0 发布了还是一样。
可否尽快解决这个问题？

**Comment by chenyuebo** [comment]
11.8.1也有这个问题

**Comment by ouabing** [comment]
暂时只能把 isSessionValid 的限制去掉了，这么严重的问题求修复下
