### ISSUE TITLE
11.6.0 authorizeWeb方法会抛异常：please init sdk before use it. Wb.install() 

### ISSUE THREAD

**Issue by XMeleny** [sinaweibosdk/weibo_android_sdk#608]
在authorizeWeb之前已经调用了sdk的初始化，使用authorizeClient和authorize是没有问题的

**Comment by ArchangelXu** [comment]
+1。看源码，10.10.0最后com.sina.weibo.sdk.a这个类的a()方法会把静态变量a的值置为true，然而11.6.0没有= =
但10.10.0在parseAccessToken的时候没判空，导致没装微博app的时候走web登录崩溃= =
大写的服。虽说一看这项目也算年久失修，但好歹新浪也算大厂吧...搞成这样对得起发的工资吗？
