### ISSUE TITLE
11.6版本，初始化时，为什么不能传Application 非要传Activity

### ISSUE THREAD

**Issue by carvetime** [sinaweibosdk/weibo_android_sdk#612]
![C532D0E4916F419EA7EBEF63190A15B6](https://user-images.githubusercontent.com/30133247/131676425-225ed24c-529c-4694-a73c-f9399af32a9f.jpg)

**Comment by carvetime** [comment]
传ApplicationContext 会初始化失败

**Comment by duning1204** [comment]
确实，这就很蠢了

**Comment by YoungHnhb** [comment]
快升级11.11.1吧，终于改了，哎
