### ISSUE TITLE
你们这provider怎么回事

### ISSUE THREAD

**Issue by tt328307109** [sinaweibosdk/weibo_android_sdk#627]
各种改法都还是冲突，
你们做出来的东西怎么这么难用
错误：
	Attribute provider#androidx.core.content.FileProvider@authorities value=(com.example.xx.fileprovider) from [openDefault-10.10.0.aar] AndroidManifest.xml:64:13-64
	is also present at [:mvpframework] AndroidManifest.xml:39:13-60 value=(com.example.xx.provider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:62:9-70:20 to override.
我的provider：

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths"
                tools:replace="android:resource" />
        </provider>

	我的filepaths：
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    
    
    

    <files-path
        name="msdy_files-path"
        path="." />

    <cache-path
        name="msdy_cache-path"
        path="." />

    

    <external-files-path
        name="msdy_external-files-path"
        path="." />

    <external-cache-path
        name="msdy_external-cache-path"
        path="." />

    <root-path
        name="msdy_root-path"
        path="." />
    
    <external-files-path
        name="share_files"
        path="." />

</paths>

**Comment by yswheye** [comment]
`

<external-files-path
    name="share_files"
    path="." />
`
我想问下，必须加这个路径吗？？？

**Comment by yzjjdcf** [comment]
> ```
> 
> <external-files-path
>     name="share_files"
>     path="." />
> ```
> 
> 
>      
>   
> 
> 我想问下，必须加这个路径吗？？？

同问，这个路径怎么回事为毛我所有解析的uri都到share_files了，必须配置么

**Comment by marekchen** [comment]
可以写一个class继承androidx或者support库的FileProvider
然后再manifest里配置你自己写的类
在分享的时候也使用你自己写的类，不要直接用FileProvider
