### ISSUE TITLE
微博登入 (網路不給力稍後試試C7003)

### ISSUE THREAD

**Issue by Samsu7609** [sinaweibosdk/weibo_android_sdk#63]
使用微博登入(SSO授權 All in One) 網路不給力稍後試試C7003
手機微博版本為5.1.1
![screenshot_2015-03-02-16-24-32](https://cloud.githubusercontent.com/assets/6458119/6439906/ac58c4fe-c112-11e4-9408-5b2f3b5c93b0.png)

請問各位開法者有遇過相同的狀況嗎?

**Comment by Samsu7609** [comment]
我透過Sample code 的 SSO授權(Web) 
可以成功取得授權 --> 使用 OpenAPI -->UserAPI --> 獲取用戶信息 有時候可以成功取得 有時會發生下面狀況
![screenshot_2015-03-02-19-33-03](https://cloud.githubusercontent.com/assets/6458119/6439995/bb8362b2-c113-11e4-8e38-54be7a4afaea.png)

**Comment by pkliang** [comment]
我也遇到这种情况了

**Comment by pkliang** [comment]
根据我的猜测，很有可能是gfw的问题，如果你不在中国大陆的话

**Comment by Samsu7609** [comment]
我在台灣 , 不知道為何 目前又可以使用了..
@pkliang  感謝你的回覆!

**Comment by abertranb** [comment]
I have the same issue, works without Weibo application installed in the device but when you have it raises C7003 error.

Is it the problem related with the source country?
Any suggestion to avoid this problem?

Thanks!

**Comment by anahjanes** [comment]
@abertranb Try this:
-Download Hola VPN client: https://play.google.com/store/apps/details?id=org.hola
-Open Hola Application and set the weibo official using china proxy.
-Try again

**Comment by lgy1425** [comment]
I have same problem. Same code with DemoApp but It makes C7003 error. 
Help me plz

**Comment by johnsonhuang** [comment]
i have the same problem,heop
