### ISSUE TITLE
近日分享到微博后 , callback返回的都是取消

### ISSUE THREAD

**Issue by ExcaliburZ** [sinaweibosdk/weibo_android_sdk#631]
麻烦关注下,很多App都有类似的现象

**Comment by zhewang412** [comment]
我也遇到了同样的问题，近日发现分享成功后会回调到取消里，之前是正常的

**Comment by ExcaliburZ** [comment]
对的,分享的流程不对,中间会被中断,显示你有未发送的内容

**Comment by buqionghuang** [comment]
遇到同样的问题，请问有解决吗

**Comment by ExcaliburZ** [comment]
有微博的开发在吗,可以反馈下这个问题吗?

**Comment by karryoung** [comment]
我也遇到问题了，有解决吗？

**Comment by ExcaliburZ** [comment]
微博的开发麻烦关注下,还是一直有这个问题

**Comment by chiemy** [comment]
测试微博 12.0.0 版本没问题，升级 12.1.2 之后就回调失败了

**Comment by chiemy** [comment]
SDK 11.12.0，微博客户端 12.1.2 ， 可正常回调
