### ISSUE TITLE
Could not GET 'https://dl.bintray.com/rongcloud/maven/com/sina/weibo/sdk/core/4.4.0/core-4.4.0.pom'. Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by keep-z** [sinaweibosdk/weibo_android_sdk#633]
> Could not resolve com.sina.weibo.sdk:core:4.4.0.
         > Could not get resource 'https://dl.bintray.com/rongcloud/maven/com/sina/weibo/sdk/core/4.4.0/core-4.4.0.pom'.
            > Could not GET 'https://dl.bintray.com/rongcloud/maven/com/sina/weibo/sdk/core/4.4.0/core-4.4.0.pom'. Received status code 403 from server: Forbidden

**Comment by fanzhiri** [comment]
https://dl.bintray.com 好像被关闭了
