### ISSUE TITLE
分享源程序签名错误

### ISSUE THREAD

**Issue by hofens** [sinaweibosdk/weibo_android_sdk#635]
大多数人应该会在AndroidManifest中去注册appkey，然后通过getMetaData方式获取，但可能会因为文字过长拿到科学计数法后的字符串，所以微博sdk就会报 分享源程序签名错误 的错误了，或者在微博草稿箱里显示8995 app auth fail for appKey&sign&package

**Comment by ch1035063420** [comment]
请问这个问题应该如何解决呢
