### ISSUE TITLE
微博SDK11.120编译不通过问题

### ISSUE THREAD

**Issue by dengtuo** [sinaweibosdk/weibo_android_sdk#636]
![image](https://user-images.githubusercontent.com/10073978/145927418-15ea12fb-c96f-49d8-8396-a06ac0100020.png)
POM依赖里面有这样一个依赖unspecified 导致编译的时候，拉取不到资源而失败

**Comment by bruce3x** [comment]
之前版本就遇到了 应该可以这样
```
implementation("...") {
        exclude module: "unspecified"
    }
```
