### ISSUE TITLE
分享后不管是取消发布还是发布成功，返回自己的app，都不走回调

### ISSUE THREAD

**Issue by Pink-lll** [sinaweibosdk/weibo_android_sdk#647]
不走onError和onComplete回调，直接走onResume回调，此时app无法点击或滑动，然后需要再次返回才能回到app。相当于WbshareActivity返回后是一个透明的activity

**Comment by Pink-lll** [comment]
目前使用的sdk版本是11.8.1

**Comment by IceWalnut** [comment]
同，解决了吗
