### ISSUE TITLE
严重bug。。。targetSdk 30时，单独分享图片，无法找到已安装的微博客户端，会跳web但是根本不显示图片

### ISSUE THREAD

**Issue by RobotHost** [sinaweibosdk/weibo_android_sdk#649]
targetSdk 30时，单独分享图片，无法找到已安装的微博客户端，会跳web但是根本不显示图片；
和demo一样设置为 29时，可以正常跳转微博客户端。。。
赶紧解决吧哥哥们

**Comment by yanxudong1** [comment]
<queries>
        <package android:name="com.sina.weibo" />
    </queries> 
清单文件配置一下

**Comment by yanxudong1** [comment]
<queries>
        <package android:name="com.sina.weibo" />
    </queries>

**Comment by yanxudong1** [comment]
<queries>
        <package android:name="com.sina.weibo" />
    </queries>

**Comment by yanxudong1** [comment]
`<queries>
        <package android:name="com.sina.weibo" />
    </queries>`

**Comment by yanxudong1** [comment]
清单文件加个配置`<queries>
        <package android:name="com.sina.weibo" />
    </queries>`
