### ISSUE TITLE
POM文件里面为什么有unspecified？

### ISSUE THREAD

**Issue by yzeaho** [sinaweibosdk/weibo_android_sdk#651]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.github.sinaweibosdk</groupId>
  <artifactId>core</artifactId>
  <version>12.3.1</version>
  <packaging>aar</packaging>
  <name>core</name>
  <description>This is Sina Weibo SDK</description>
  <url>https://github.com/sinaweibosdk/weibo_android_sdk</url>
  <licenses>
    <license>
      <name>The Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>sina.mobileclient</id>
      <name>sina.mobileclient</name>
      <email>sina.mobileclient@gmail.com</email>
    </developer>
  </developers>
  <scm>
    <connection>scm:git:github.com/sinaweibosdk/weibo_android_sdk.git</connection>
    <developerConnection>scm:git:ssh://github.com/sinaweibosdk/weibo_android_sdk.git</developerConnection>
    <url>https://github.com/sinaweibosdk/weibo_android_sdk/tree/master</url>
  </scm>
  <dependencies>
    <dependency>
      <groupId/>
      <artifactId>unspecified</artifactId>
      <version/>
    </dependency>
  </dependencies>
</project>
`

你们的POM文件里面为什么有unspecified？一直引用报错，找半天原来是你们的问题，为什么会有这个？显得很不专业。

**Comment by hpcat432** [comment]
请问这个怎么解决？我是在我自己的SDK里依赖weibo，项目依赖SDK时编译不过

**Comment by sinaweibosdk** [comment]
v13.10.4 fixed
