### ISSUE TITLE
uiError:your app is illegal____code:-2

### ISSUE THREAD

**Issue by GongZiZhang** [sinaweibosdk/weibo_android_sdk#655]
uiError:your app is illegal____code:-2  一直返回我的应用非法是什么意思， appkey和签名都对了是正确的

**Comment by 965023780** [comment]
android11以上新增了包可见性权限，微博sdk里会通过PackageManager.resolveActivity()寻找SsoActivity。
解决这个问题，需要在清单文件里用queries申明微博的包名，具体可以看https://developer.android.com/about/versions/11/privacy/package-visibility
