### ISSUE TITLE
小米商店扫描安全问题

### ISSUE THREAD

**Issue by xiaochenzhicheng** [sinaweibosdk/weibo_android_sdk#659]
Lcom/tencent/feedback/activity/WebViewBrowser;->initWebConfig()V ---> WebSettings;->setMi
xedContentMode(Z)V 能否更新下setMi
xedContentMode为MIXED_CONTENT_NEVER_ALLOW？

**Comment by sinaweibosdk** [comment]
v13.10.2  fixed
