### ISSUE TITLE
3.0.1版本Demo在2.3机子上 获取用户信息 有问题，而在4.x的机子是好的。

### ISSUE THREAD

**Issue by yangjinbo** [sinaweibosdk/weibo_android_sdk#66]
帮忙给看下，谢谢！

W/System.err( 7358): com.sina.weibo.sdk.exception.WeiboException: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
W/System.err( 7358):    at com.sina.weibo.sdk.net.HttpManager.requestHttpExecute(HttpManager.java:190)
W/System.err( 7358):    at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:112)
W/System.err( 7358):    at com.sina.weibo.sdk.net.AsyncWeiboRunner$RequestRunner.doInBackground(AsyncWeiboRunner.java:132)
W/System.err( 7358):    at com.sina.weibo.sdk.net.AsyncWeiboRunner$RequestRunner.doInBackground(AsyncWeiboRunner.java:1)
W/System.err( 7358):    at android.os.AsyncTask$2.call(AsyncTask.java:185)
W/System.err( 7358):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
W/System.err( 7358):    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
W/System.err( 7358):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
W/System.err( 7358):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
W/System.err( 7358):    at java.lang.Thread.run(Thread.java:1019)
W/System.err( 7358): Caused by: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
W/System.err( 7358):    at org.apache.harmony.xnet.provider.jsse.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:258)
W/System.err( 7358):    at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
W/System.err( 7358):    at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:381)
W/System.err( 7358):    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
W/System.err( 7358):    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
W/System.err( 7358):    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
W/System.err( 7358):    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
W/System.err( 7358):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
W/System.err( 7358):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
W/System.err( 7358):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
W/System.err( 7358):    at com.sina.weibo.sdk.net.HttpManager.requestHttpExecute(HttpManager.java:180)

**Comment by LuckyJayce** [comment]
我使用的时候也会出现这个异常
