### ISSUE TITLE
Google Play提出代码存在风险

### ISSUE THREAD

**Issue by TokenYc** [sinaweibosdk/weibo_android_sdk#664]
sdk版本：11.11.1
![image](https://user-images.githubusercontent.com/11829523/190050713-278e09ae-27f7-4548-b8ef-dc97bd9996fb.png)

**Comment by cxcxcxcx** [comment]
Deadline 已过，现在使用 Weibo SDK 的 app 没法在 Google Play 上架了。Google 给出了详细的解决方案，不知开发者能处理一下吗？谢谢！

https://support.google.com/faqs/answer/9267555

**Comment by cxcxcxcx** [comment]
Workaround，在 `AndroidManifest.xml` 中加入： `<activity android:exported="false" android:name="com.sina.weibo.sdk.share.ShareTransActivity" tools:replace="android:exported"/>`

**Comment by sinaweibosdk** [comment]
fixed
