### ISSUE TITLE
微博分享功能为啥需要SDCard 读写权限呀？好敏感，如果不是必须要，后续版本可否去除？

### ISSUE THREAD

**Issue by jack0825** [sinaweibosdk/weibo_android_sdk#666]
微博分享功能为啥需要SDCard 读写权限呀，存应用内沙箱目录不可以么？ 这个权限用户比较敏感；
如果不是必须要，建议后续版本考虑去除
？

**Comment by jack0825** [comment]
![image](https://user-images.githubusercontent.com/11957399/200997412-135fe265-1789-4a2e-9b93-688af3bd3150.png)

**Comment by GstXu** [comment]
还有获取设备ID， 现在这些隐私都不让用了，能不能出个新包啊
