### ISSUE TITLE
WebActivity 漏洞

### ISSUE THREAD

**Issue by mister-wang-cn** [sinaweibosdk/weibo_android_sdk#667]
com.sina.weibo.sdk.web.WebActivity 中setMixedContentMode有漏洞风险，能修复下这个问题吗

**Comment by mister-wang-cn** [comment]
![image](https://user-images.githubusercontent.com/66372966/201276322-4e3c838d-92e6-42fc-b590-ef4fac6fb5b3.png)

**Comment by nooooooooooob** [comment]
v13.5.0已修复
