### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by crossle** [sinaweibosdk/weibo_android_sdk#67]
Please support Gradle build, publish to jcenter or mavencentral

**Comment by foolhorse** [comment]
+1

**Comment by kyangc** [comment]
+1

**Comment by FrancisShi** [comment]
尼玛 导个工程都这么麻烦，studio可以支持吗？新浪，用点心好吗

**Comment by yongjhih** [comment]
See Also:

* https://github.com/8tory/weibo-android-sdk
* https://github.com/8tory/weibo-android-sdk-core

**Comment by yongjhih** [comment]
The jcenter and mavenCenral accept only open source project, so weibo-android-sdk-core could not been accepted, we're using jitpack for weibo-android-sdk-core instead of jcenter/mavenCentral.
