### ISSUE TITLE
分享图文imageUrl包含中文字符，图片会丢失

### ISSUE THREAD

**Issue by XutongGithub** [sinaweibosdk/weibo_android_sdk#678]
bug：分享图文imageUrl包含中文字符，图片会丢失
图片地址：https://m3api1.fjdaily.com:9663/xy/image.do?path=%E5%9B%BE%E7%89%87%E5%AD%98%E5%82%A8%3Bxy/202210/31/t2_(133X7X460X334)7f496c6a-9b0e-4830-a4a8-a751745a0f8c_watermark.jpeg

**Comment by sinaweibosdk** [comment]
13.10.4 fixed

**Comment by XutongGithub** [comment]
邮件已收到。谢谢！
