### ISSUE TITLE
jar包里面的类，建议放到sina路径下

### ISSUE THREAD

**Issue by droidXZ** [sinaweibosdk/weibo_android_sdk#682]
sdk提供class.jar， 里面的类混淆了为a/a.class 的形式，如果是采用插件的形式集成，会有冲突，导致方法找不到。建议jar里面的类，放到sina路径下
![20231213-150133](https://github.com/sinaweibosdk/weibo_android_sdk/assets/30231265/f6beab5e-63c7-4704-9402-1448d1d5e087)
![20231213-151501](https://github.com/sinaweibosdk/weibo_android_sdk/assets/30231265/485c00f0-7d6f-4f2d-b82e-f007afb27eca)

**Comment by nooooooooooob** [comment]
v13.10.1  已经修复
