### ISSUE TITLE
加个arm v7的是so库

### ISSUE THREAD

**Issue by jasonrongdevelop** [sinaweibosdk/weibo_android_sdk#69]
无arm v7的是so库，这些机型会奔溃

**Comment by cikichen** [comment]
如果只编译了armeabi的话，在某些机型上会提示找不到weibocore.so导致崩溃，希望能修复这个问题，太蛋疼了

**Comment by jhcpokemon** [comment]
我同样出现这个问题

**Comment by tongcpp** [comment]
拷贝arm目录下的so至arm-v7目录

**Comment by cikichen** [comment]
有时候整个工程结构只有一个armeabi目录的时候，没有v7，这个时候部分机型就会出现找不到v7库崩溃的问题，拷贝so到v7a不是解决方案，因为如果是一个游戏app的话，一个so大小几十兆，如果我多拷贝一份v7a，就会导致apk大小翻倍
