### ISSUE TITLE
clearCookie

### ISSUE THREAD

**Issue by FreeSunny** [sinaweibosdk/weibo_android_sdk#73]
public static void clearCookies(Context context)
  {
    CookieSyncManager.createInstance(context);
    CookieManager cookieManager = CookieManager.getInstance();
    cookieManager.removeAllCookie();
    CookieSyncManager.getInstance().sync();
  }

这样会导致宿主应用的cookie被清理

**Comment by zewenwang** [comment]
+1 分享失败时，应用所有cookie被清除
