### ISSUE TITLE
Failed to find provider info for com.sina.weibo.sdkProvider

### ISSUE THREAD

**Issue by bluesoulx** [sinaweibosdk/weibo_android_sdk#74]
環境: Android Studio 1.2.2
Android Mini SDK: 15
使用版本: 3.1.1

有複製所有的 .so 檔案（沒有修改資料夾格式）到 libs 資料夾
於 AndroidManifest.xml 有加入以下代碼
<activity android:name="com.sina.weibo.sdk.component.WeiboSdkBrowser"
                  android:configChanges="keyboardHidden|orientation"
                  android:windowSoftInputMode="adjustResize"
                  android:exported="false" >
        </activity>

進行 SsoHandler.authorize() 會出現
E/ActivityThread﹕ Failed to find provider info for com.sina.weibo.sdkProvider

在 weibosdkcore_v3.1.1.jar 也沒有發現這個東西
若有可能還請不吝指教，謝謝

**Comment by LinJZong** [comment]
同样的问题，关注中。
起因应该是找不到so文件，最后会报
06-18 14:06:55.945    31739-456/? W/System.err﹕ Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: get_lib_extents[743]:  1932 - /data/data/**/lib/libweibosdkcore.so is not a valid ELF object
已经将so文件放入jniLibs目录下的各个文件夹（包括armeabi-v7a）中。

**Comment by bluesoulx** [comment]
這部份我有再
build.gradle 中的 android 區塊中加入 
sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
應該就不會出現 LinkError
但我就出現了 "Failed to find provider info for com.sina.weibo.sdkProvider"
實在有點苦惱

**Comment by LinJZong** [comment]
请问你加了sourceSets后 是把jniLibs目录下地文件夹放到libs文件夹下吗

**Comment by bluesoulx** [comment]
是的
我就是單純把那些 so 檔案依照他原本有的資料夾結構
放到該 Module 的 libs 資料夾內放置

例如:
app
&nbsp;&nbsp;&nbsp;|--- libs
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--- arm64-v8a
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--- armeabi
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|...

以上這樣
所以我是在 app 的 build.gradle 加入 sourceSets

**Comment by LinJZong** [comment]
谢谢，不过我按你说了，还是没效果。看了下打出来的包，lib内确实包含libweibosdkcore这个so文件的。
不知道是否因为我用了其他so文件的关系。我的项目里用到so文件的地方有Fresco、百度定位、百度推送三个，一共9个so文件

**Comment by bluesoulx** [comment]
![screenshot-20150618](https://cloud.githubusercontent.com/assets/7234072/8225934/c360f658-15cc-11e5-9c1e-365bc3969df4.png)
我是類似上圖這樣的結構

**Comment by enjoyzhao** [comment]
我的也是这个问题，最后在官网上提交获得的签名串（一开始提交的是release版的，测试用的是debug的，所有后来提示packs sing error），然后就正常跳转到网页登录形式了（前提是没有装新浪APP客户端），如果装的话会自动打开APP客户端进行验证。

**Comment by liericiyan** [comment]
这个问题我也碰到了

**Comment by liericiyan** [comment]
我这边重新下载了微博客户端，调用可以直接调起授权了，这个问题好像是因为5.0的版本不支持web授权了，调用web就报错了

**Comment by YannyQin** [comment]
楼主给力，果然是so文件丢失了，填进去就好了，赞赞赞

**Comment by YannyQin** [comment]
赞赞 解决了

**Comment by YangYongQ** [comment]
@YannyQin ,求指点此问题解法

**Comment by zyy086** [comment]
我出現了 "Failed to find provider info for com.sina.weibo.sdkProvider"
在Manifest文件中加入下面的代码就ok了

        <activity android:name="com.sina.weibo.sdk.component.WeiboSdkBrowser"
            android:configChanges="keyboardHidden|orientation"
            android:windowSoftInputMode="adjustResize"
            android:exported="false" >
        </activity>
