### ISSUE TITLE
新浪微博demo客户端分享，会调出两个登录界面？

### ISSUE THREAD

**Issue by 18344478262** [sinaweibosdk/weibo_android_sdk#78]
贵公司的demo程序，当安装有微博客户端却没有登录时，调用微博第三方分享会调出两个客户端登录页面，不论是哪中登录方式，请问这是怎么回事？

**Comment by zhangzhizhi** [comment]
恩，是的。我这边也是这样。

**Comment by jalonray** [comment]
似乎是因为mWeiboShareAPI.sendRequest(Activity, Request, AuthInfo, Token, AuthListener)会再执行一次校验登陆操作，如果分享写在AuthListener里就会走两次
