### ISSUE TITLE
小米 note arm64 崩溃

### ISSUE THREAD

**Issue by jiweibreadtrip** [sinaweibosdk/weibo_android_sdk#79]
06-30 16:37:50.755: I/DEBUG(425): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
06-30 16:37:50.755: I/DEBUG(425): Build fingerprint: 'Xiaomi/leo/leo:5.0.2/LRX22G/V6.5.5.0.LXHCNCD:user/release-keys'
06-30 16:37:50.755: I/DEBUG(425): Revision: '0'
06-30 16:37:50.755: I/DEBUG(425): ABI: 'arm64'
06-30 16:37:50.755: I/DEBUG(425): pid: 23951, tid: 25162, name: Thread-1443  >>> com.breadtrip <<<
06-30 16:37:50.755: I/DEBUG(425): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffff9c05c050
06-30 16:37:50.765: I/DEBUG(425):     x0   ffffffff9c05c050  x1   ffffffff9c05c050  x2   0000007f980fdb60  x3   0000007fb23c2000
06-30 16:37:50.765: I/DEBUG(425):     x4   0000000000000000  x5   0000000000000044  x6   0000000000000045  x7   0000000000000000
06-30 16:37:50.765: I/DEBUG(425):     x8   0000007f98867f40  x9   0000007f99c94070  x10  0000000000000041  x11  0101010101010101
06-30 16:37:50.765: I/DEBUG(425):     x12  0000007f99c94040  x13  00000000ffffffff  x14  0000007f99c94040  x15  00000000002a6040
06-30 16:37:50.765: I/DEBUG(425):     x16  0000007f9c05bfe0  x17  0000007fb230cf24  x18  0000007fb2386080  x19  0000007f99c83720
06-30 16:37:50.765: I/DEBUG(425):     x20  ffffffff9c05c050  x21  0000007f99c0ea69  x22  0000007f99c0ea60  x23  0000007f99c15680
06-30 16:37:50.765: I/DEBUG(425):     x24  0000007f99c15860  x25  0000007f980fd3a8  x26  0000007f980fd3ac  x27  00000000335430a0
06-30 16:37:50.765: I/DEBUG(425):     x28  00000000335430a0  x29  0000000032c01130  x30  0000007f9c049958
06-30 16:37:50.765: I/DEBUG(425):     sp   0000007f980fd320  pc   0000007fb230cf34  pstate 0000000040000000
06-30 16:37:50.765: I/DEBUG(425): backtrace:
06-30 16:37:50.765: I/DEBUG(425):     #00 pc 0000000000015f34  /system/lib64/libc.so (strlen+16)
06-30 16:37:50.765: I/DEBUG(425):     #01 pc 0000000000003954  /data/app/com.breadtrip-2/lib/arm64/libweibosdkcore.so
06-30 16:37:50.765: I/DEBUG(425):     #02 pc 00000000000044d8  /data/app/com.breadtrip-2/lib/arm64/libweibosdkcore.so (Java_com_sina_weibo_sdk_net_HttpManager_calcOauthSignNative+216)
06-30 16:37:50.765: I/DEBUG(425):     #03 pc 00000000005d7614  /data/dalvik-cache/arm64/data@app@com.breadtrip-2@base.apk@classes.dex

**Comment by jiweibreadtrip** [comment]
是我使用有问题还是现在还未支持64位系统？

**Comment by icefoggy** [comment]
新浪你们这么大的公司，这么久了还不解决arm64的问题，真是汗

**Comment by buobao** [comment]
3.1.4版本也闪退，机型 魅族pro6，能否解决下？感激！
