### ISSUE TITLE
64位机器上无法登录授权

### ISSUE THREAD

**Issue by SinTi** [sinaweibosdk/weibo_android_sdk#80]
- 64位测试机上点击微博登录进入微博页面后logcat里会有一行A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0xffffff8b419050 in tid 5852 (Thread-3180)，登录帐号后返回接收不到回调。

- 还有在你们的Demo中进入微博授权，点击里面的button之后，Demo会卡住然后闪退。

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sinaweibosdk** [comment]
这个问题我们目前在解决，是因为我们64位so包有点问题

**Comment by sheltonliu** [comment]
3.0.0版本，有添加64位so包吗？
