### ISSUE TITLE
ARM 用不了

### ISSUE THREAD

**Issue by HKen** [sinaweibosdk/weibo_android_sdk#86]
AidTask.java(229) getAidSync: getAidSync
AidTask.java(178) aidTaskInit: aidTaskInit
Fatal signal 11 (SIGSEGV), code 1, fault addr 0xffffff968ab050 in tid 18161 (Thread-59165)
AidTask.java(193) run: tryLock : false, return

现在好多新型号的手机都运行不了 比如：三星s6 ,魅蓝note2等。

**Comment by tianzhijiexian** [comment]
导入最新的so，并且替换jar为3.1.2即可修复
