### ISSUE TITLE
安卓端没有安装微博客户端时分享{"error":"userinfo error!","pos":"5"}

### ISSUE THREAD

**Issue by DisillusionXuZX** [sinaweibosdk/weibo_android_sdk#90]
在没有安装客户端的情况下分享会报出以下错误：{"error":"userinfo error!","pos":"5"}，求解答。

**Comment by fulingfan** [comment]
![piscesktu84pfulingfan10102015142026](https://cloud.githubusercontent.com/assets/5733832/10409612/17760a76-6f5a-11e5-9ea8-1bf39431cb04.png)

**Comment by jiachenning** [comment]
+1 
has no weibo client in android 5.1, meet same problem
